//
//  OpenPluginRemoveCookieFromURLModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 25772
//  

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginRemoveCookieFromURLRequest
public final class OpenPluginRemoveCookieFromURLRequest: OpenAPIBaseParams {
    
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "url")
    public var url: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_url]
    }
}

// MARK: - OpenPluginRemoveCookieFromURLResponse
public final class OpenPluginRemoveCookieFromURLResponse: OpenAPIBaseResult {
    
    /// description: 删除结果说明
    public let msg: String?
    
    public init(msg: String?) {
        self.msg = msg
        super.init()
    }
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["msg"] = msg
        return result
    }
}
