# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'LarkCombineDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  source 'git@code.byted.org:iOS_Library/lark_source_repo.git'

  # Pods for LarkCombineDemo
  pod 'LarkCombine', :path => '../'

  target 'LarkCombineUnitTests' do
    inherit! :search_paths
  end
end
