# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'LarkNativeSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KADemoAssemble', :path => '../KADemoAssemble'
  pod 'KATabDemo', :path => '../KATab/KATabDemo'
  pod 'KATabInterface', :path => '../KATab/KATabInterface'
  pod 'KAFileDemo', :path => '../KAFile/KAFileDemo'
  pod 'KAFileInterface', :path => '../KAFile/KAFileInterface'
  
  pod 'KALogin', :path => '../KALogin/KALogin'
  pod 'KALoginDemo', :path => '../KALogin/KALoginDemo'
  pod 'AppLink', :path => '../LKAppLinkExternal/external/AppLink'
  pod 'LKAppLinkExternal', :path => '../LKAppLinkExternal/external'
  pod 'LKNativeAppContainer', :path => '../LKNativeAppContainer/external'
  pod 'LKNativeAppExtension', :path => '../LKNativeAppExtension/external'
  pod 'LKNativeAppExtensionAbility', :path => '../LKNativeAppExtensionAbility'
  
  pod 'AFNetworking', '3.1.0'
  pod 'MBProgressHUD', '1.2.0'
  pod 'libwebp', '1.1.0', :inhibit_warnings => true
  pod 'AFNetworking', '3.1.0', :inhibit_warnings => true
  pod 'Masonry', :inhibit_warnings => true
  pod 'JSONModel', :inhibit_warnings => true
  pod 'SocketRocket', :inhibit_warnings => true
end

pre_install do |installer|
  installer.pod_targets.each do |pod_target|
    attributes_hash = pod_target.root_spec.attributes_hash
    pod_target_xcconfig = (attributes_hash['pod_target_xcconfig'] ||= {}) # 保证存在, 使用方可以不用判断默认值了

    pod_target_xcconfig['GCC_PREPROCESSOR_DEFINITIONS'] ||= ''
    pod_target_xcconfig['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= '$(inherited)'

    pod_target_xcconfig['GCC_PREPROCESSOR_DEFINITIONS'] += ' KADEMO=1'
    pod_target_xcconfig['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] += ' KADEMO'

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
