//
//  BaseAssembly.swift
//  Lark
//
//  Auto generated by lark-project.
//  See more: https://bytedance.feishu.cn/docx/doxcnDjV99CCJ2qcihUE453Qaqg
//

import Foundation
import LarkAssembler
import AppContainer
import LKLoadable

final class BaseAssembly: LarkAssemblyInterface {
    lazy var subAssemblies = lazySubAssemblies()

    func getSubAssemblies() -> [LarkAssemblyInterface]? {
        return subAssemblies
    }

    private func lazySubAssemblies() -> [LarkAssemblyInterface] {
        let assemblies = allAssemblies()
        var set = Set<ObjectIdentifier>()
        for ass in assemblies {
            recordAllSubAssemblies(in: &set, for: ass)
        }
        return assemblies.filter { !set.contains(ObjectIdentifier(type(of: $0))) }
    }

    private func recordAllSubAssemblies(in set: inout Set<ObjectIdentifier>, for ass: LarkAssemblyInterface) {
        let subs = ass.getSubAssemblies() ?? []
        guard !subs.isEmpty else { return }
        subs.lazy.forEach {
            set.insert(ObjectIdentifier(type(of: $0)))
            $0.getSubAssemblies()?.forEach { recordAllSubAssemblies(in: &set, for: $0) }
        }
    }
}

import LarkAccount
import LarkAppLinkSDK
import LarkBGTaskScheduler
import LarkBadgeAssembly
import LarkCacheAssembly
import LarkCloudScheme
import LarkAppConfig
import LarkDebug
import LarkLaunchGuide
import ECOInfra
import LarkEmotion
import LarkAccountAssembly
import LarkBaseService
import LarkDynamicResource
import LarkEMM
import LarkGuide
import LarkLiveMod
import LarkMonitor
import LarkNavigationAssembly
import LarkPushTokenUploader
import LarkSceneManagerAssembly
import LarkShareContainer
import LarkSnsShare
import LarkStorageAssembly
import LarkLeanMode
import LarkNavigation
import LarkPrivacyAlert
import LarkRustClientAssembly
import LarkSecurityAudit
import LarkSecurityComplianceInfra
import LarkSetting
import LarkSettingsBundle
import SuiteAppConfig
import LarkSuspendable
import LarkVideoDirector
import ZeroTrust

private func allAssemblies() -> [LarkAssemblyInterface] {
    return [
        AccountAssembly(),
        AppLinkAssembly(),
        BGTaskSchedulerAssembly(),
        BadgeAssembly(),
        CacheManagerAssembly(),
        CloudSchemeAssembly(),
        ConfigAssembly(),
        DebugAssembly(),
        DefaultLaunchGuideDependencyAssembly(),
        ECOCookieAssembly(),
        ECONetworkAssembly(),
        EmotionAssembly(),
        LarkAccountAssembly(),
        LarkBaseServiceAssembly(),
        LarkDynamicResourceAssembly(),
        LarkEMMAssembly(),
        LarkGuideAssembly(),
        LarkLiveAssembly(),
        LarkMonitorAssembly(),
        LarkNavigationAssembly(),
        LarkPushTokenUploaderAssembly(),
        LarkSceneManagerAssembly(),
        LarkShareContainerAssembly(),
        LarkSnsShareAssembly(),
        LarkSnsShareBaseAssembly(),
        LarkStorageAssembly(),
        LaunchGuideAssembly(),
        LeanModeAssembly(),
        NavigationAssembly(),
        PrivacyAlertAssembly(),
        RustClientAssembly(),
        SecurityAuditAssembly(),
        SecurityComplianceInfraAssembly(),
        SettingAssembly(),
        SettingsBundleAssembly(),
        SuiteAppConfigAssembly(),
        SuspendAssembly(),
        VideoDirectorAssembly(),
        ZeroTrustAssembly()
    ]
}
