//
//  OpenPluginSetPageOrientationModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 24942
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginSetPageOrientationRequest
final class OpenPluginSetPageOrientationRequest: OpenAPIBaseParams {

    /// description: 页面方向
    /// orientation = portrait 竖屏
    /// orientation = landscape 横屏
    /// orientation = auto 跟随设备方向
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "orientation")
    public var orientation: OrientationEnum

    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_orientation];
    }

    // MARK: OrientationEnum
    public enum OrientationEnum: String, OpenAPIEnum {

        /// description: 竖屏
        case portrait = "portrait"

        /// description: 横屏
        case landscape = "landscape"

        /// description: 跟随设备方向
        case auto = "auto"

    }
}
