//
//  OpenPluginCheckMFAModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 29996
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginCheckMFARequest
final class OpenPluginCheckMFARequest: OpenAPIBaseParams {
    
    /// description: 业务场景标识
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "mfaScope")
    var mfaScope: String
    
    /// description: 待验证的认证凭据
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "mfaToken")
    var mfaToken: String
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_mfaScope, _mfaToken]
    }
}

// MARK: - OpenPluginCheckMFAResponse
final class OpenPluginCheckMFAResponse: OpenAPIBaseResult {
    
    /// description: token是否有效
    /// status = 1 有效
    /// status = 2 无效
    let status: StatusEnum
    
    init(status: StatusEnum) {
        self.status = status
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["status"] = status.rawValue
        return result
    }

    // MARK: StatusEnum
    enum StatusEnum: Int, OpenAPIEnum {

        /// description: 有效
        case valid = 1

        /// description: 无效
        case invalid = 2

    }
}
