//
//  OpenPluginStartThirdPartyMFAModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 29916
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginStartThirdPartyMFARequest
final class OpenPluginStartThirdPartyMFARequest: OpenAPIBaseParams {
    
    /// description: 发起一次MFA的流程标识，需要通过调用OpenAPI进行获取
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "mfaKey")
    var mfaKey: String
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_mfaKey]
    }
}

// MARK: - OpenPluginStartThirdPartyMFAResponse
final class OpenPluginStartThirdPartyMFAResponse: OpenAPIBaseResult {
    
    /// description: 认证码，完成MFA后下发的一次性code，用于换取mfa_token
    let mfaCode: String
    
    init(mfaCode: String) {
        self.mfaCode = mfaCode
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["mfaCode"] = mfaCode
        return result
    }
}
