//
//  OpenPluginStartMFAModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 29917
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginStartMFARequest
final class OpenPluginStartMFARequest: OpenAPIBaseParams {
    
    /// description: 业务场景标识
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "mfaScope")
    var mfaScope: String
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_mfaScope]
    }
}

// MARK: - OpenPluginStartMFAResponse
final class OpenPluginStartMFAResponse: OpenAPIBaseResult {
    
    /// description: 完成MFA后下发的认证凭据
    let mfaToken: String
    
    init(mfaToken: String) {
        self.mfaToken = mfaToken
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["mfaToken"] = mfaToken
        return result
    }
}
