//
//  APPID.swift
//  LarkLogin
//
//  Created by qihongye on 2019/1/11.
//

import WebKit
import LKCommonsLogging

enum APPID: String {
    case v3LoginType
    /// 填写团队信息，POST
    case v3TenantPrepare
    /// 设置团队页面信息，GET
    case v3RegisterPrepareTenant
    case v3JoinType
    case v3ApplyCode
    case v3VerifyCode
    case v3VerifyPwd
    case v3App
    case v3Create
    case v3IdpAuthUrl
    case v3IdpSSOUrl
    case v3SetPwd
    case v3SetName
    case v4JoinWithQRCode
    case v3OfficialEmailJoin
    case v3BindContact
    case v3IdpVerifyToken
    case v3OneKeyLogin
    case v3OneKeyRegister
    case v3RecoverType
    case v3RecoverAccountCarrier
    case v3RecoverAccountBank
    case v3SetInputCredential
    case v3NotifyFaceVerifySuccess
    case v3RefreshVerifyTicket
    case v3VerifyPolling
    case v3VerifyOtp
    case v3ClientDispatch

    case v4UserList
    case v4UserCenter
    case credentialList
    case v4EnterApp
    case v4LogoutApp
    case v4LogoutToken
    case v4SetPwd
    case v4SetName
    case v4OneKeyLogin
    case v4JoinTenantByCode
    case v4JoinTenantByScan
    case v4VerifyPwd
    case v4EnterEmailCreate
    case v4InitOfficialEmail
    case v4CreateTenant
    case v4ApplyCode
    case v4VerifyCode
    case v4TenantInformation
    case v4RegisterDiscovery
    case v4VerifyOtp
    case v4RetrieveGuideWay
    case v4RetrieveOpThree
    case retrieveChoose
    case retrieveSetCred
    case retrieveAppealGuide
    case upgradeLogin
    case listDevice
    case disableDevice
    case updateDevice
    case applyVerifyToken // 请求 X-Verify-Token
    case applyMFAToken
    case validateMFAToken
    case deprovisionCheck
    case chooseOptIn
    case realNameGuideWay
    case joinTenant
    case checkRefuseInvitation
    case refuseInvitation
    case abTestForUG
    case setSpareCredential
    case checkStatus
    case exemptRemind
    case checkSecPwd
    case verifyMo
    case applyForm
    case submitForm
    case upgradeSessionDid
    case grayConfig
    case fidoBeginRegist
    case fidoFinishRegist
    case fidoBeginAuth
    case fidoFinishAuth
    case fidoPage
    case authenGetAuthInfo
    case authenConfirm

    func apiIdentify() -> String {
        switch self {
        case .v3LoginType:
            return "login/credential"
        case .v3TenantPrepare:
            return "tenant/prepare"
        case .v3RegisterPrepareTenant:
            return "register/prepare_tenant"
        case .v3JoinType:
            return "join_type"
        case .v3ApplyCode:
            return "otp/apply_code"
        case .v3VerifyCode:
            return "otp/verify_code"
        case .v3VerifyPwd:
            return "verify_pwd"
        case .v3App:
            return "app"
        case .v3Create:
            return "create"
        case .v3IdpAuthUrl:
            return "auth_url"
        case .v3IdpSSOUrl:
            return "sso_url"
        case .v3SetPwd:
            return "set_pwd"
        case .v3SetName:
            return "set_name"
        case .v3OfficialEmailJoin:
            return "official_email_join"
        case .v4JoinWithQRCode:
            return "tenant/qr_code"
        case .v3BindContact:
            return "bind_contact"
        case .v3IdpVerifyToken:
            return "verify_token"
        case .v3OneKeyLogin:
            return "login_m_auth"
        case .v3OneKeyRegister:
            return "register_m_auth"
        case .v3RecoverType:
            return "recover/type"
        case .v3RecoverAccountCarrier:
            return "recover/operator"
        case .v3RecoverAccountBank:
            return "recover/bankcard"
        case .v3SetInputCredential:
            return "recover/newmobile"
        case .v3NotifyFaceVerifySuccess:
            return "recover/face"
        case .v3RefreshVerifyTicket:
            return "recover/change"
        case .v3VerifyPolling:
            return "verify_polling"
        case .v3VerifyOtp:
            return "verify_otp"
        case .v3ClientDispatch:
            return "dispatch"
        case .v4UserList:
            return "security/user/list"
        case .v4UserCenter:
            return "security/user/user_center"
        case .credentialList:
            return "security/credential/list"
        case .v4EnterApp:
            return "app"
        case .v4LogoutApp:
            return "logout/app"
        case .v4LogoutToken:
            return "logout/token"
        case .v4SetPwd:
            return "auth/pwd/set"
        case .v4SetName:
            return "tenant/set_name"
        case .v4OneKeyLogin:
            return "login/mobile_auth"
        case .v4JoinTenantByCode:
            return "tenant/tenant_code"
        case .v4JoinTenantByScan:
            return "tenant/tenant_scan"
        case .v4VerifyPwd:
            return "auth/pwd/verify"
        case .v4EnterEmailCreate:
            return "official_email/create"
        case .v4InitOfficialEmail:
            return "official_email/init"
        case .v4CreateTenant:
            return "tenant/create"
        case .v4ApplyCode:
            return "auth/code/apply"
        case .v4VerifyCode:
            return "auth/code/verify"
        case .v4TenantInformation:
            return "tenant/information"
        case .v4RegisterDiscovery:
            return "register/discovery"
        case .v4VerifyOtp:
            return "auth/otp/verify"
        case .v4RetrieveGuideWay:
            return "retrieve/guide_way"
        case .v4RetrieveOpThree:
            return "retrieve/op_three"
        case .retrieveChoose:
            return "retrieve/choose_identity"
        case .retrieveSetCred:
            return "retrieve/reset_cred"
        case .retrieveAppealGuide:
            return "retrieve/appeal_approved_guide"
        case .upgradeLogin:
            return "app/upgrade/login"
        case .listDevice:
            return "device/list"
        case .disableDevice:
            return "device/disable"
        case .updateDevice:
            return "device/update"
        case .applyVerifyToken:
            return "verify_token/apply"
        case .applyMFAToken:
            return "mfa_token/apply"
        case .validateMFAToken:
            return "mfa_token/validate"
        case .deprovisionCheck:
            return "deprovision/check"
        case .chooseOptIn:
            return "auth/choose_opt_in"
        case .realNameGuideWay:
            return "realname/guide_way"
        case .joinTenant:
            return "tenant/invitation_token/join"
        case .checkRefuseInvitation:
            return "tenant/invitation_token/refuse_check"
        case .refuseInvitation:
            return "tenant/invitation_token/refuse"
        case .abTestForUG:
            return "ug_register/abtest"
        case .setSpareCredential:
            return "auth/spare_credential/set"
        case .checkStatus:
            return "status/check_status"
        case .exemptRemind:
            return "status/exempt_remind"
        case .checkSecPwd:
            return "check_sec_pwd"
        case .verifyMo:
            return "auth/mo/verify"
        case .applyForm:
            return "approval/platform/form"
        case .submitForm:
            return "approval/platform/create"
        case .upgradeSessionDid:
            return "did/upgrade/login"
        case .grayConfig:
            return "config/gray"
        case .fidoBeginRegist:
            return "security/fido/registration/begin"
        case .fidoFinishRegist:
            return "security/fido/registration/finish"
        case .fidoBeginAuth:
            return "auth/fido/begin"
        case .fidoFinishAuth:
            return "auth/fido/finish"
        case .fidoPage:
            return "page/fido2"
        case .authenGetAuthInfo:
            return "v1/get_auth_info_inner"
        case .authenConfirm:
            return "v1/confirm_inner"
        }
    }
}
