//
//  BaseAssembly.swift
//  Lark
//
//  Auto generated by lark-project.
//  See more: https://bytedance.feishu.cn/docx/doxcnDjV99CCJ2qcihUE453Qaqg
//

import Foundation
import LarkAssembler
import AppContainer
import LKLoadable

final class BaseAssembly: LarkAssemblyInterface {
    lazy var subAssemblies = lazySubAssemblies()

    func getSubAssemblies() -> [LarkAssemblyInterface]? {
        return subAssemblies
    }

    private func lazySubAssemblies() -> [LarkAssemblyInterface] {
        let assemblies = allAssemblies()
        var set = Set<ObjectIdentifier>()
        for ass in assemblies {
            recordAllSubAssemblies(in: &set, for: ass)
        }
        return assemblies.filter { !set.contains(ObjectIdentifier(type(of: $0))) }
    }

    private func recordAllSubAssemblies(in set: inout Set<ObjectIdentifier>, for ass: LarkAssemblyInterface) {
        let subs = ass.getSubAssemblies() ?? []
        guard !subs.isEmpty else { return }
        subs.lazy.forEach {
            set.insert(ObjectIdentifier(type(of: $0)))
            $0.getSubAssemblies()?.forEach { recordAllSubAssemblies(in: &set, for: $0) }
        }
    }
}

import LarkAIInfra
import LarkAccount
import AnimatedTabBar
import LarkAppLinkSDK
import LarkBadgeAssembly
import LarkCacheAssembly
import LarkCloudScheme
import LarkAppConfig
import LarkDebug
import LarkLaunchGuide
import ECOInfra
import LarkEmotion
import LarkEmotionKeyboard
import LarkSecurityCompliance
import LarkAccountAssembly
import LarkCleanAssembly
import LarkCoreLocation
import LarkDocsIcon
import LarkDynamicResource
import LarkEMM
import LarkFontAssembly
import LarkGuide
import LarkMonitor
import LarkNavigationAssembly
import LarkSceneManagerAssembly
import LarkShareContainer
import LarkSnsShare
import LarkStorageAssembly
import LarkLeanMode
import LarkNavigation
import LarkPrivacyAlert
import LarkRustClientAssembly
import SecSDK
import LarkSecurityAudit
import LarkSecurityComplianceInfra
import LarkSetting
import LarkSettingsBundle
import SuiteAppConfig
import LarkSuspendable
import TangramService
import LarkVideoDirector
import LarkWaterMark
import ZeroTrust

private func allAssemblies() -> [LarkAssemblyInterface] {
    return [
        AccountAssembly(),
        AccountAssembly(),
        AnimatedTabBarAssembly(),
        AnimatedTabBarAssembly(),
        AppLinkAssembly(),
        AppLinkAssembly(),
        BadgeAssembly(),
        BadgeAssembly(),
        CacheManagerAssembly(),
        CacheManagerAssembly(),
        CloudSchemeAssembly(),
        CloudSchemeAssembly(),
        ConfigAssembly(),
        ConfigAssembly(),
        DebugAssembly(),
        DebugAssembly(),
        DefaultLaunchGuideDependencyAssembly(),
        DefaultLaunchGuideDependencyAssembly(),
        ECOCookieAssembly(),
        ECOCookieAssembly(),
        ECONetworkAssembly(),
        ECONetworkAssembly(),
        EmotionAssembly(),
        EmotionAssembly(),
        EmotionKeyboardAssembly(),
        EmotionKeyboardAssembly(),
        FileCryptoAssembly(),
        FileCryptoAssembly(),
        LarkAccountAssembly(),
        LarkCleanAssembly(),
        LarkCoreLocationAssembly(),
        LarkCoreLocationAssembly(),
        LarkDocsIconAssembly(),
        LarkDocsIconAssembly(),
        LarkDynamicResourceAssembly(),
        LarkDynamicResourceAssembly(),
        LarkEMMAssembly(),
        LarkEMMAssembly(),
        LarkFontAssembly(),
        LarkFontAssembly(),
        LarkGuideAssembly(),
        LarkGuideAssembly(),
        LarkInlineAIAssemble(),
        LarkMonitorAssembly(),
        LarkMonitorAssembly(),
        LarkNavigationAssembly(),
        LarkSceneManagerAssembly(),
        LarkSceneManagerAssembly(),
        LarkSecurityComplianceAssembly(),
        LarkSecurityComplianceAssembly(),
        LarkShareContainerAssembly(),
        LarkShareContainerAssembly(),
        LarkSnsShareAssembly(),
        LarkSnsShareAssembly(),
        LarkSnsShareBaseAssembly(),
        LarkSnsShareBaseAssembly(),
        LarkStorageAssembly(),
        LarkStorageAssembly(),
        LaunchGuideAssembly(),
        LaunchGuideAssembly(),
        LeanModeAssembly(),
        LeanModeAssembly(),
        NavigationAssembly(),
        NavigationAssembly(),
        PrivacyAlertAssembly(),
        PrivacyAlertAssembly(),
        RustClientAssembly(),
        RustClientAssembly(),
        SecGuardAssembly(),
        SecGuardAssembly(),
        SecurityAuditAssembly(),
        SecurityAuditAssembly(),
        SecurityComplianceInfraAssembly(),
        SecurityComplianceInfraAssembly(),
        SecurityPolicyAssembly(),
        SecurityPolicyAssembly(),
        SettingAssembly(),
        SettingAssembly(),
        SettingsBundleAssembly(),
        SettingsBundleAssembly(),
        SuiteAppConfigAssembly(),
        SuiteAppConfigAssembly(),
        SuspendAssembly(),
        SuspendAssembly(),
        TangramAssembly(),
        TangramAssembly(),
        VideoDirectorAssembly(),
        VideoDirectorAssembly(),
        WaterMarkAssembly(),
        WaterMarkAssembly(),
        ZeroTrustAssembly(),
        ZeroTrustAssembly()
    ]
}
