reporter: "json"
disabled_rules:
  - skip_public

# paths to include during detecting. `--path` is ignored if present.
included:
  - ./
#  - ./Lark
# #Messenger
#  - ./Pods/LarkChat
#  - ./Pods/LarkChatSetting
#  - ./Pods/LarkContact
#  - ./Pods/LarkFeed
#  - ./Pods/LarkSuspendable
#  - ./Pods/LarkFinance
#  - ./Pods/LarkForward
#  - ./Pods/LarkMessenger
#  - ./Pods/LarkMine
#  - ./Pods/LarkQRCode
#  - ./Pods/LarkThread
#  - ./Pods/LarkUrgent
#  - ./Pods/LarkAttachmentUploader
#  - ./Pods/LarkAudio
#  - ./Pods/LarkCore
#  - ./Pods/LarkMessageCore
#  - ./Pods/LarkMessengerInterface
#  - ./Pods/LarkSDK
#  - ./Pods/LarkFeedBanner
#  - ./Pods/LarkFeedPlugin
#  - ./Pods/LarkEdu
#  - ./Pods/LarkLeanMode
#  - ./Pods/LarkPerf
#  - ./Pods/LarkPushTokenUploader
#  - ./Pods/LarkReleaseConfig
#  - ./Pods/LarkRustClient
#  - ./Pods/LarkRustHTTP
#  - ./Pods/LarkSafety
#  - ./Pods/NotificationUserInfo
#  - ./Pods/SuiteAppConfig
#  - ./Pods/AppContainer
#  - ./Pods/EENotification
#  - ./Pods/ExtensionMessenger
#  - ./Pods/HTTProtocol
#  - ./Pods/LarkAudioKit
#  - ./Pods/LarkBGTaskScheduler
#  - ./Pods/LarkBaseService
#  - ./Pods/LarkCompatible
#  - ./Pods/LarkContainer
#  - ./Pods/LarkCrashSanitizer
#  - ./Pods/LarkInteraction
#  - ./Pods/LarkKeyCommandKit
#  - ./Pods/LarkKeyboardKit
#  - ./Pods/LarkMessageBase
#  - ./Pods/LarkModel
#  - ./Pods/LarkOrientation
#  - ./Pods/LarkPopoverKit
#  - ./Pods/QRCode
#  - ./Pods/LarkScene
#  - ./Pods/LarkTraitCollection
#  - ./Pods/LarkCache
#  - ./Pods/LarkSafeMode
#  - ./Pods/LKContentFix
#  - ./Pods/LarkSplash
#  - ./Pods/LarkExtensionCommon
#  - ./Pods/LarkNotificationServiceExtension
#  - ./Pods/LarkShareExtension
#  - ./Pods/CJPay
#  - ./Pods/TTBridgeUnify
#  - ./Pods/tfccsdk
#  - ./Pods/IESJSBridgeCore
#  - ./Pods/BDTrackerProtocol
#  - ./Pods/SAMKeychain
#  - ./Pods/LarkAppLog
#  - ./Pods/LarkSDKInterface
#  - ./Pods/LarkShareToken
#  - ./Pods/ZeroTrust
#  - ./Pods/CookieManager
#  - ./Pods/LarkTab
#  - ./Pods/LarkZoomable
#  - ./Pods/LarkWaterMark
#  - ./Pods/LarkSuspendable
#  - ./Pods/LarkCombine
#  - ./Pods/LarkSceneManager
#  - ./Pods/LarkPolicySign
#  - ./Pods/LarkRustClientAssembly
#  - ./Pods/BitsPodsPlaceholder
#  - ./Pods/LarkCanvas
#  - ./Pods/LarkEmotionKeyboard
#  - ./Pods/Moment
#  - ./Pods/LarkOpenChat
#  - ./Pods/LarkTTNetInitializor
#  - ./Pods/LarkDynamicResource
#  - ./Pods/LarkFeedback
#  - ./Pods/BDFeedBack
#  - ./Pods/BDLarkAuth
#  - ./Pods/TTFileUploadClient
#  - ./Pods/LarkMinimumMode
#  - ./Pods/LKLoadable
#  - ./Pods/TangramLayoutKit
#  - ./Pods/TangramComponent
#  - ./Pods/TangramUIComponent
#  - ./Pods/LarkBlur
#  - ./Pods/AMapFoundation-NO-IDFA
#  - ./Pods/AMapSearch-NO-IDFA
#  - ./Pods/ByteWebImage
#  - ./Pods/LarkExtensionServices
#  - ./Pods/lib_h_dec
#  - ./Pods/TTFFmpeg
#  - ./Pods/TTNetworkPredict
#  - ./Pods/VCPreloadStrategy
#  - ./Pods/FBRetainCycleDetector
#  - ./Pods/TangramService
#  - ./Pods/TTMLeaksFinder
#  - ./Pods/BootManagerConfig
#  - ./Pods/AFNetworking
#  - ./Pods/AWECloudCommand
#  - ./Pods/BDPreloadSDK
#  - ./Pods/BDXBridgeKit
#  - ./Pods/BDXContainer
#  - ./Pods/BDXLynxKit
#  - ./Pods/BDXMonitor
#  - ./Pods/BDXOptimize
#  - ./Pods/BDXResourceLoader
#  - ./Pods/BDXRouter
#  - ./Pods/BDXSchema
#  - ./Pods/BDXServiceCenter
#  - ./Pods/BulletX
#  - ./Pods/CJPayDebugTools
#  - ./Pods/DebugRouter
#  - ./Pods/IESPrefetch
#  - ./Pods/IESWebViewMonitor
#  - ./Pods/LynxDevtool
#  - ./Pods/TTMd5
#  - ./Pods/TTNetworkDownloader
#  - ./Pods/LarkProfile
#  - ./Pods/LarkPrivacyKit
# #UG
#  - ./Pods/LKLaunchGuide
#  - ./Pods/LarkCustomerService
#  - ./Pods/LarkExtensionMessage
#  - ./Pods/LarkLaunchGuide
#  - ./Pods/LarkSettingsBundle
#  - ./Pods/LarkSnsShare
#  - ./Pods/LarkGuideUI
#  - ./Pods/LarkTour
#  - ./Pods/LarkTourInterface
#  - ./Pods/IESGeckoKit
#  - ./Pods/BDUGShare
#  - ./Pods/BDUGContainer
#  - ./Pods/BDUGLogger
#  - ./Pods/BDUGMonitorInterface
#  - ./Pods/BDUGTrackerInterface
#  - ./Pods/TencentQQSDK
#  - ./Pods/WechatSDK
#  - ./Pods/WeiboSDK
#  - ./Pods/ADFeelGood
#  - ./Pods/BDUGLoggerInterface
#  - ./Pods/LarkAddressBookSelector
#  - ./Pods/LarkGuide
#  - ./Pods/LarkMagic
#  - ./Pods/LarkSecurityAudit
#  - ./Pods/TYRZApiSDK
#  - ./Pods/LarkShareContainer
#  - ./Pods/UGBanner
#  - ./Pods/UGContainer
#  - ./Pods/UGRCoreIntegration
#  - ./Pods/UGReachSDK
#  - ./Pods/UGRule
#  - ./Pods/UGCoordinator
#  - ./Pods/UGSpotlight
# #passport
#  - ./Pods/LarkAccount
#  - ./Pods/LarkWebCache
#  - ./Pods/OfflineResourceManager
#  - ./Pods/LarkCreateTeam
#  - ./Pods/GTMSessionFetcher
#  - ./Pods/AppAuth
#  - ./Pods/GoogleSignIn
#  - ./Pods/GTMAppAuth
#  - ./Pods/BDTuring
#  - ./Pods/BDUGAccountOnekeyLogin
#  - ./Pods/BDUGUnionSDK
#  - ./Pods/EAccountApiSDK
#  - ./Pods/LarkAccountInterface
#  - ./Pods/LarkBytedCert
#  - ./Pods/LarkSSO
# #OpenPlatform
#  - ./Pods/LarkAppLinkSDK
#  - ./Pods/NewLarkDynamic
#  - ./Pods/JsSDK
#  - ./Pods/LarkAppCenter
#  - ./Pods/LarkAppStateSDK
#  - ./Pods/LarkMicroApp
#  - ./Pods/LarkOpenPlatform
#  - ./Pods/LarkTabMicroApp
#  - ./Pods/byted_cert
#  - ./Pods/SocketRocket
#  - ./Pods/Objection
#  - ./Pods/Blockit
#  - ./Pods/EEMicroAppSDK
#  - ./Pods/LarkHelpdesk
#  - ./Pods/LarkOPInterface
#  - ./Pods/LarkPano
#  - ./Pods/LarkWebViewContainer
#  - ./Pods/Lynx
#  - ./Pods/OPBlock
#  - ./Pods/OPFoundation
#  - ./Pods/OPGadget
#  - ./Pods/OPSDK
#  - ./Pods/OPWidget
#  - ./Pods/TTMicroApp
#  - ./Pods/ECOInfra
#  - ./Pods/ECOProbe
#  - ./Pods/LarkOpenAPIModel
#  - ./Pods/LarkOpenCommonPlugins
#  - ./Pods/LarkOpenPluginManager
#  - ./Pods/OPPlugin
#  - ./Pods/ECOProbeMeta
#  - ./Pods/EcosystemShell
#  - ./Pods/EcosystemWeb
#  - ./Pods/WebBrowser
#  - ./Pods/XElement
# #tool
#  - ./Pods/LarkMonitor
#  - ./Pods/VCNVCloudNetwork
#  - ./Pods/BDDataDecoratorTob
#  - ./Pods/BDJSBridgeAuthManager
#  - ./Pods/TTTopSignature
#  - ./Pods/ABRInterface
#  - ./Pods/TTMacroManager
#  - ./Pods/React-jsi
#  - ./Pods/libPhoneNumber-iOS
#  - ./Pods/KeychainAccess
#  - ./Pods/glog
#  - ./Pods/SwiftyJSON
#  - ./Pods/Folly
#  - ./Pods/ReactCommon
#  - ./Pods/MemoryGraphCapture
#  - ./Pods/React-cxxreact
#  - ./Pods/FMDB
#  - ./Pods/React-CoreModules
#  - ./Pods/Differentiator
#  - ./Pods/React-RCTImage
#  - ./Pods/FLAnimatedImage
#  - ./Pods/RxAutomaton
#  - ./Pods/KVOController
#  - ./Pods/RxRelay
#  - ./Pods/Godzippa
#  - ./Pods/NSObject+Rx
#  - ./Pods/React-jsinspector
#  - ./Pods/Action
#  - ./Pods/FBLazyVector
#  - ./Pods/FLEX
#  - ./Pods/oc-opus-codec
#  - ./Pods/ReachabilitySwift
#  - ./Pods/Reveal-SDK
#  - ./Pods/SwiftLint
#  - ./Pods/IESAppLogger_iOS
#  - ./Pods/Stinger
#  - ./Pods/BDWebKit
# #CommonUI
#  - ./Pods/AnimatedTabBar
#  - ./Pods/EditTextView
#  - ./Pods/LarkActionSheet
#  - ./Pods/LarkActivityIndicatorView
#  - ./Pods/LarkAlert
#  - ./Pods/LarkAlertController
#  - ./Pods/LarkAudioView
#  - ./Pods/LarkButton
#  - ./Pods/LarkCamera
#  - ./Pods/LarkDatePickerView
#  - ./Pods/LarkEmotion
#  - ./Pods/LarkLocationPicker
#  - ./Pods/LarkMenuController
#  - ./Pods/LarkPageController
#  - ./Pods/LarkReactionDetailController
#  - ./Pods/LarkReactionView
#  - ./Pods/LarkSwipeCellKit
#  - ./Pods/PresentContainerController
#  - ./Pods/RichLabel
#  - ./Pods/RoundedHUD
#  - ./Pods/SelectMenu
#  - ./Pods/LarkBanner
#  - ./Pods/LarkSplitViewController
#  - ./Pods/LarkPrivacyAlert
#  - ./Pods/lottie-ios
#  - ./Pods/SnapKit
#  - ./Pods/Masonry
#  - ./Pods/Yoga
#  - ./Pods/MBProgressHUD
#  - ./Pods/ActionPanel
#  - ./Pods/AvatarComponent
#  - ./Pods/LarkAssetsBrowser
#  - ./Pods/LarkAvatarComponent
#  - ./Pods/LarkBizAvatar
#  - ./Pods/LarkImageEditor
#  - ./Pods/LarkListItem
#  - ./Pods/LarkSegmentedView
#  - ./Pods/UniverseDesignColor
#  - ./Pods/UniverseDesignFont
#  - ./Pods/UniverseDesignTabs
#  - ./Pods/UniverseDesignTheme
#  - ./Pods/UniverseDesignActionPanel
#  - ./Pods/UniverseDesignPopover
#  - ./Pods/UniverseDesignStyle
#  - ./Pods/UniverseDesignBadge
#  - ./Pods/UniverseDesignButton
#  - ./Pods/UniverseDesignIcon
#  - ./Pods/UniverseDesignTag
#  - ./Pods/UniverseDesignDatePicker
#  - ./Pods/UniverseDesignDrawer
#  - ./Pods/UniverseDesignToast
#  - ./Pods/UniverseDesignEmpty
#  - ./Pods/UniverseDesignNotice
#  - ./Pods/UniverseDesignDialog
#  - ./Pods/UniverseDesignMenu
#  - ./Pods/UniverseDesignBreadcrumb
#  - ./Pods/UniverseDesignCheckBox
#  - ./Pods/UniverseDesignLoading
#  - ./Pods/UniverseDesignProgressView
#  - ./Pods/UniverseDesignSwitch
#  - ./Pods/UniverseDesignInput
#  - ./Pods/UniverseDesignAvatar
# #VC
#  - ./Pods/VCInfra
#  - ./Pods/LarkByteView
#  - ./Pods/LarkVoIP
#  - ./Pods/EffectSDK_iOS
#  - ./Pods/bytenn-ios
#  - ./Pods/audiosdk
#  - ./Pods/yaml-cpp
#  - ./Pods/Sodium
#  - ./Pods/GoogleAPIClientForREST
#  - ./Pods/LLBSDMessaging
#  - ./Pods/ByteRtcSDK
#  - ./Pods/ByteView
#  - ./Pods/ByteViewBoardcastExtension
#  - ./Pods/ByteViewDebug
#  - ./Pods/ByteViewInterface
#  - ./Pods/ByteViewLS
#  - ./Pods/LarkMinutes
#  - ./Pods/Minutes
#  - ./Pods/MinutesFoundation
#  - ./Pods/MinutesInterface
#  - ./Pods/YYText
#  - ./Pods/CocoaAsyncSocket
#  - ./Pods/MinutesNavigator
#  - ./Pods/TTVideoLive
#  - ./Pods/ByteViewRTCRenderer
#  - ./Pods/LarkRVC
#  - ./Pods/UltrasonicWave
#  - ./Pods/LarkLive
#  - ./Pods/LarkLiveInterface
#  - ./Pods/ByteViewUDColor
#  - ./Pods/ByteViewDependency
# #mail
#  - ./Pods/LarkMail
#  - ./Pods/ESPullToRefresh
#  - ./Pods/LarkMailInterface
#  - ./Pods/LarkWebviewNativeComponent
#  - ./Pods/MailSDK
# #doc
#  - ./Pods/LarkEditorJS
#  - ./Pods/LarkSpaceKit
#  - ./Pods/HandyJSON
#  - ./Pods/libpng
#  - ./Pods/FBReactNativeSpec
#  - ./Pods/React-RCTNetwork
#  - ./Pods/DoubleConversion
#  - ./Pods/ReSwift
#  - ./Pods/BitableBridge
#  - ./Pods/boost-for-react-native
#  - ./Pods/RCTRequired
#  - ./Pods/RCTTypeSafety
#  - ./Pods/React-Core
#  - ./Pods/React-jsiexecutor
#  - ./Pods/SKCommon
#  - ./Pods/SKFoundation
#  - ./Pods/SKResource
#  - ./Pods/SKUIKit
#  - ./Pods/SpaceInterface
#  - ./Pods/SpaceKit
#  - ./Pods/UIImageViewAlignedSwift
#  - ./Pods/SKBitable
#  - ./Pods/SKMindnote
#  - ./Pods/SKSheet
#  - ./Pods/SKSlide
#  - ./Pods/SKWiki
#  - ./Pods/SKBrowser
#  - ./Pods/SKDoc
#  - ./Pods/SKWikiV2
#  - ./Pods/SKDrive
#  - ./Pods/SKSpace
# #common
#  - ./Pods/LarkAppConfig
#  - ./Pods/LarkAppResources
#  - ./Pods/LarkAvatar
#  - ./Pods/LarkBadge
#  - ./Pods/LarkNotificationServiceExtensionLib
#  - ./Pods/LKMetric
#  - ./Pods/LKTracing
#  - ./Pods/LarkExtensions
#  - ./Pods/LarkFeatureGating
#  - ./Pods/LarkFeatureSwitch
#  - ./Pods/LarkLocalizations
#  - ./Pods/LarkNavigation
#  - ./Pods/LarkNavigator
#  - ./Pods/LarkTracker
#  - ./Pods/LarkUIExtension
#  - ./Pods/LarkUIKit
#  - ./Pods/RunloopTools
#  - ./Pods/ThreadSafeDataStructure
#  - ./Pods/LarkColor
#  - ./Pods/LarkTag
#  - ./Pods/BootManager
#  - ./Pods/AsyncComponent
#  - ./Pods/EEAtomic
#  - ./Pods/EEFlexiable
#  - ./Pods/EEImageMagick
#  - ./Pods/EEKeyValue
#  - ./Pods/EENavigator
#  - ./Pods/EEPodInfoDebugger
#  - ./Pods/EETroubleKiller
#  - ./Pods/LKCommonsLogging
#  - ./Pods/LKCommonsTracker
#  - ./Pods/LarkFoundation
#  - ./Pods/LarkResource
#  - ./Pods/Logger
#  - ./Pods/PushKitService
#  - ./Pods/SuiteCodable
#  - ./Pods/TTPlayerSDK
#  - ./Pods/TTVideoEditor
#  - ./Pods/ByteDanceKit
#  - ./Pods/Heimdallr
#  - ./Pods/mobilecv2
#  - ./Pods/espresso
#  - ./Pods/TTVideoEngine
#  - ./Pods/RangersAppLog
#  - ./Pods/smash
#  - ./Pods/BDWebImage
#  - ./Pods/TTNetworkManager
#  - ./Pods/BDWebCore
#  - ./Pods/TTRoute
#  - ./Pods/TTReachability
#  - ./Pods/BDAssert
#  - ./Pods/BDAlogProtocol
#  - ./Pods/BDMonitorProtocol
#  - ./Pods/SwiftProtobuf
#  - ./Pods/RxSwift
#  - ./Pods/boringssl
#  - ./Pods/RxCocoa
#  - ./Pods/Kingfisher
#  - ./Pods/Alamofire
#  - ./Pods/libwebp
#  - ./Pods/CryptoSwift
#  - ./Pods/JSONModel
#  - ./Pods/BDDataDecorator
#  - ./Pods/RxDataSources
#  - ./Pods/YYCache
#  - ./Pods/BDALog
#  - ./Pods/SSZipArchive
#  - ./Pods/Swinject
#  - ./Pods/KingfisherWebP
#  - ./Pods/Gaia
#  - ./Pods/AppReciableSDK
#  - ./Pods/AudioSessionScenario
#  - ./Pods/BDABTestSDK
#  - ./Pods/DateToolsSwift
#  - ./Pods/Homeric
#  - ./Pods/LarkDebug
#  - ./Pods/LarkDebugExtensionPoint
#  - ./Pods/LarkFileKit
#  - ./Pods/LarkOpenTrace
#  - ./Pods/SkeletonView
#  - ./Pods/LarkKAFeatureSwitch
#  - ./Pods/LarkEnv
#  - ./Pods/LarkOpenCombine
#  - ./Pods/LarkOpenCombineDispatch
#  - ./Pods/LarkOpenCombineFoundation
#  - ./Pods/AGFX_pub
#  - ./Pods/arkcrypto-minigame-iOS
#  - ./Pods/EffectPlatformSDK
#  - ./Pods/FileMD5Hash
#  - ./Pods/gaia_lib_publish
#  - ./Pods/Mantle
#  - ./Pods/protobuf_lite
#  - ./Pods/BDFishhook
#  - ./Pods/OneKit
#  - ./Pods/LarkSetting
#  - ./Pods/LarkDeepLink
#  - ./Pods/BDUGDeepLink
#  - ./Pods/BDUGSecure
#  - ./Pods/BDNetworkTag
# #SDK
#  - ./Pods/LarkSQLCipher
#  - ./Pods/RustPB
#  - ./Pods/ServerPB
# #secret
#  - ./Pods/SecSDK
#  - ./Pods/TSPrivacyKit
#  - ./Pods/RSSwizzle
# #AI&Search
#  - ./Pods/LarkSearch
#  - ./Pods/LarkSearchFilter
#  - ./Pods/LarkAI
#  - ./Pods/LarkSearchCore
#  - ./Pods/LarkWidgetService
#  - ./Pods/LarkWidget
# #Calendar
#  - ./Pods/Calendar
#  - ./Pods/CalendarFoundation
#  - ./Pods/CalendarRichTextEditor
#  - ./Pods/JTAppleCalendar
#  - ./Pods/LarkTimeFormatUtils
# #视频
#  - ./Pods/MDLMediaDataLoader
# #广告
#  - ./Pods/MMKV
#  - ./Pods/MMKVCore
#  - ./Pods/TTAdSplashSDK
# # Todo
#  - ./Pods/CTFoundation
#  - ./Pods/Todo
#  - ./Pods/TodoInterface

# paths to ignore during detecting. Takes precedence over `included`.
# excluded:
#   - Pods

# names of group to detect, if not set will detect all the group.
# included_group_name:
#   - Carthage

# names of group to ignore during detecting.
# excluded_group_name:
#   - Pods

# symbols to ignore during detecting, contains class, struct, enum, etc.
blacklist_symbols:
  - AppDelegate
  - viewDidLoad

# allow giving a regax to specify symbol, this example is to ignore symbol contains "Gender".
symbol_regex: "^((?!.*(Gender)).)*$" 

# all the class inherit from class specified in the list will ignore
blacklist_superclass:
  - UITableViewCell

# If output_file is not specified, the defaults to be pecker.result.json in your project
output_file: pecker.result.json

