// DO NOT EDIT.
//
// Generated by the Swift generator for OPMonitorCode.
// Source: https://bytedance.feishu.cn/sheets/shtcnCCboz4CUWBUtZkdmZV0PLb?sheet=hW9qFp&table=tbl5emX07KpwAipE&view=vew6lPBCVe
// Date:   2021/03/12 11:35
//
// For information on using the generated types, please see the documentation:
//  https://bytedance.feishu.cn/sheets/shtcnCCboz4CUWBUtZkdmZV0PLb

import Foundation
import LarkOPInterface

@objcMembers
public final class OPSDKMonitorCode: OPMonitorCode {

    /// 成功
    public static let success = OPSDKMonitorCode(code: 10000, level: OPMonitorLevelNormal, message: "success")

    /// 失败
    public static let unknown_error = OPSDKMonitorCode(code: 10001, level: OPMonitorLevelError, message: "unknown_error")

    /// 取消
    public static let cancel = OPSDKMonitorCode(code: 10002, level: OPMonitorLevelWarn, message: "cancel")

    /// 超时
    public static let timeout = OPSDKMonitorCode(code: 10003, level: OPMonitorLevelError, message: "timeout")

    /// 不合法的参数
    public static let invalid_params = OPSDKMonitorCode(code: 10004, level: OPMonitorLevelError, message: "invalid_params")

    /// can not init data from str
    public static let can_not_init_data_from_str = OPSDKMonitorCode(code: 10005, level: OPMonitorLevelError, message: "can_not_init_data_from_str")

    /// jsonObject type invalid
    public static let json_object_type_invalid = OPSDKMonitorCode(code: 10006, level: OPMonitorLevelError, message: "json_object_type_invalid")

    /// dictionary is not a valid jsonObject
    public static let dictionary_is_not_a_valid_json_object = OPSDKMonitorCode(code: 10007, level: OPMonitorLevelError, message: "dictionary_is_not_a_valid_json_object")

    /// can not init str form data
    public static let can_not_init_str_form_data = OPSDKMonitorCode(code: 10008, level: OPMonitorLevelError, message: "can_not_init_str_form_data")

    /// JSON解码失败
    public static let json_decode_failed = OPSDKMonitorCode(code: 10009, level: OPMonitorLevelError, message: "json_decode_failed")

    /// JSON编码失败
    public static let json_encode_failed = OPSDKMonitorCode(code: 10010, level: OPMonitorLevelError, message: "json_encode_failed")

    /// has no module manager
    public static let has_no_module_manager = OPSDKMonitorCode(code: 10011, level: OPMonitorLevelError, message: "has_no_module_manager")

    /// data_init_error
    public static let data_init_error = OPSDKMonitorCode(code: 10012, level: OPMonitorLevelError, message: "data_init_error")

    /// 可被正常回收的资源现在不存在（已被回收）
    public static let acceptable_resource_not_exists = OPSDKMonitorCode(code: 10013, level: OPMonitorLevelWarn, message: "acceptable_resource_not_exists")

    /// 应当存在的资源现在不存在
    public static let retained_resource_not_exists = OPSDKMonitorCode(code: 10014, level: OPMonitorLevelError, message: "retained_resource_not_exists")

    /// 服务解析失败
    public static let resolve_service_failed = OPSDKMonitorCode(code: 10015, level: OPMonitorLevelError, message: "resolve_service_failed")

    /// 请求业务错误
    public static let request_biz_error = OPSDKMonitorCode(code: 10017, level: OPMonitorLevelError, message: "request_biz_error")

    private init(code: Int, level: OPMonitorLevel, message: String) {
        super.init(domain: OPSDKMonitorCode.domain, code: code, level: level, message: message)
    }

    public static let domain = "client.open_platform.sdk"
}

@objcMembers
public final class OPSDKMonitorCodeLoader: OPMonitorCode {

    /// 应用资源加载超时
    public static let app_resource_load_timeout = OPSDKMonitorCodeLoader(code: 10000, level: OPMonitorLevelError, message: "app_resource_load_timeout")

    /// 文件读取失败
    public static let file_read_failed = OPSDKMonitorCodeLoader(code: 10001, level: OPMonitorLevelError, message: "file_read_failed")

    /// can not get data from response
    public static let get_data_from_response_failed = OPSDKMonitorCodeLoader(code: 10002, level: OPMonitorLevelError, message: "get_data_from_response_failed")

    /// can not get metaInfo from data
    public static let get_meta_info_from_data_failed = OPSDKMonitorCodeLoader(code: 10003, level: OPMonitorLevelError, message: "get_meta_info_from_data_failed")

    /// can not get extensionMeta from data
    public static let get_extension_meta_from_data_failed = OPSDKMonitorCodeLoader(code: 10004, level: OPMonitorLevelError, message: "get_extension_meta_from_data_failed")

    ///
    public static let meta_deserialize_response_failed = OPSDKMonitorCodeLoader(code: 10005, level: OPMonitorLevelError, message: "meta_deserialize_response_failed")

    /// can not get metaURL
    public static let get_meta_url_failed = OPSDKMonitorCodeLoader(code: 10006, level: OPMonitorLevelError, message: "get_meta_url_failed")

    /// meta返回业务错误代码
    public static let get_meta_biz_error = OPSDKMonitorCodeLoader(code: 10007, level: OPMonitorLevelError, message: "get_meta_biz_error")


    private init(code: Int, level: OPMonitorLevel, message: String) {
        super.init(domain: OPSDKMonitorCodeLoader.domain, code: code, level: level, message: message)
    }

    public static let domain = "client.open_platform.sdk.loader"
}

