//
//  OpenAPITabbarErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 27345
//

/// 界面-tabbarErrno
public enum OpenAPITabbarErrno: Int, OpenAPIErrnoProtocol {
    // 非小程序应用
    case notGadgetApp = 301
    // appConfig未配置Tabbar
    case noTabbarConfig = 302
    // 添加的tabbar已经存在
    case tabAlreadyExist = 303
    // 颜色值为非16进制
    case requireHexValue = 304
    // 删除的路径不存在
    case canNotFoundPath = 305
    // 索引参数越界
    case indexOutOfBounds = 1
    // 不支持在非tabbar小程序调用
    case notTabbar = 2
    // 最少需要保留2个tab
    case least2Tab = 3
    // 最多只能存在5个tab
    case upTo5Tab = 4
    // 不能删除正在展示的tab
    case deleteCurrentTab = 5

    public var bizDomain: Int { 11 }
    public var funcDomain: Int { 1 }
    
    public var errString: String {
        switch self {
        case .notGadgetApp:
            return "The app is not a gadget"
        case .noTabbarConfig:
            return "Tabbar not configured in appConfig"
        case .tabAlreadyExist:
            return "The tabbar added already exists"
        case .requireHexValue:
            return "Require hex value"
        case .canNotFoundPath:
            return "Corresponding tabbar path cannot be found"
        case .indexOutOfBounds:
            return "Index out of range"
        case .notTabbar:
            return "Unable to call API, as Tabbar feature has not been enabled"
        case .least2Tab:
            return "At least 2 tabs need to be configured"
        case .upTo5Tab:
            return "Up to 5 tabs can be configured"
        case .deleteCurrentTab:
            return "Unable to delete a tab that is being displayed"
        }
    }
}
