//
//  OpenAPIAccelerometerErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 24206
//

/// 加速度计Errno
public enum OpenAPIAccelerometerErrno: OpenAPIErrnoProtocol {
    // 加速度计在当前设备不可用
    case notSupport
    // 加速度计已经开启
    case alreadyRunning

    public var bizDomain: Int { 15 }
    public var funcDomain: Int { 11 }

    public var rawValue: Int {
        switch self {
        case .notSupport:
            return 1
        case .alreadyRunning:
            return 2
        }
    }
    
    public var errString: String {
        switch self {
        case .notSupport:
            return "Accelerometer unavailable on the device"
        case .alreadyRunning:
            return "Accelerometer  enabled already"
        }
    }
}
