//
//  OpenAPIBeaconErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 24846
//

/// BeaconErrno
public enum OpenAPIBeaconErrno: OpenAPIErrnoProtocol {
    // 系统或设备不支持
    case nonsupport
    // 已经开始搜索
    case alreadyStart
    // 还未开始搜索
    case notStartBeaconDiscovery
    // 位置服务不可用
    case locationUnavailable
    // 蓝牙服务不可用
    case bluetoothUnavailable

    public var bizDomain: Int { 15 }
    public var funcDomain: Int { 3 }

    public var rawValue: Int {
        switch self {
        case .nonsupport:
            return 1
        case .alreadyStart:
            return 2
        case .notStartBeaconDiscovery:
            return 3
        case .locationUnavailable:
            return 4
        case .bluetoothUnavailable:
            return 5
        }
    }
    
    public var errString: String {
        switch self {
        case .nonsupport:
            return "Not supported by the device/system"
        case .alreadyStart:
            return "Search already started"
        case .notStartBeaconDiscovery:
            return "Search not started yet"
        case .locationUnavailable:
            return "Location service not available"
        case .bluetoothUnavailable:
            return "Bluetooth service not available"
        }
    }
}
