
//
//  OpenAPIUiWindowErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 24942
//  

/// 界面-窗口Errno
public enum OpenAPIUiWindowErrno: OpenAPIErrnoProtocol {
    // 小程序处在后台
    case background
    // 主导航栏小程序不支持该API
    case tabGadgetNotSupport
    // 半屏小程序不支持该API
    case xScreenNotSupport
    // 小程序有其他控件弹出,e.g.弹出弹窗(iOS only)
    case appPresenting

    public var bizDomain: Int { 11 }
    public var funcDomain: Int { 3 }

    public var rawValue: Int {
        switch self {
        case .background:
            return 1
        case .tabGadgetNotSupport:
            return 2
        case .xScreenNotSupport:
            return 3
        case .appPresenting:
            return 4
        }
    }
    
    public var errString: String {
        switch self {
        case .background:
            return "The app is running in the background and cannot call the API"
        case .tabGadgetNotSupport:
            return "App pinned to global navigation not support"
        case .xScreenNotSupport:
            return "Current mode not support"
        case .appPresenting:
            return "App is presenting other widget, can not change page orientation"
        }
    }
}
