//
//  OpenAPIComponentCustomizedInputErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 27827
//

/// 组件-Customized InputErrno
public enum OpenAPIComponentCustomizedInputErrno: OpenAPIErrnoProtocol {
    // show() / update() / hide() 调用时兜底错误码
    case internalError
    // userId 换 openID 请求错误。eventType 表示请求 openID 的场景，取以下值：
    // picSelect：onPicSelect 回调时;
    // modelSelect：onModelSelect 回调时;
    // publish：onPublish 回调时;
    // hide：onHide 回调时
    case requestOpenIdError(eventType: String)

    public var bizDomain: Int { 90 }
    public var funcDomain: Int { 11 }

    public var rawValue: Int {
        switch self {
        case .internalError:
            return 100
        case .requestOpenIdError:
            return 201
        }
    }
    
    public var errString: String {
        switch self {
        case .internalError:
            return "InternalError"
        case .requestOpenIdError(let eventType):
            return "Request at user openID error, eventType: \(eventType)"
        }
    }
}
