//
//  OpenAPIGetVideoInfoErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 27843
//  

/// 媒体-getVideoInfoErrno
public enum OpenAPIGetVideoInfoErrno: Int, OpenAPIErrnoProtocol {
    // 不支持网络路径
    case srcInvalid = 1
    // 网络视频下载失败
    case videoDownloadFailed = 2
    // 获取视频信息失败
    case canNotGetInfo = 3
    // 不支持的文件格式
    case typeNotSupport = 4

    public var bizDomain: Int { 13 }
    public var funcDomain: Int { 6 }
    
    public var errString: String {
        switch self {
        case .srcInvalid:
            return "Path not be supported"
        case .videoDownloadFailed:
            return "Unable to load video"
        case .canNotGetInfo:
            return "Can't get info from video file"
        case .typeNotSupport:
            return "Type not be supported"
        }
    }
}
