//
//  OpenAPIRequestAccessErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 28943
//

/// 增量授权Errno
public enum OpenAPIRequestAccessErrno: OpenAPIErrnoProtocol {
    // 获取session失败
    case emptySession
    // 授权过程失败, code: <#code#>, msg: <#message#>
    //
    case authFailed(code: String, message: String)

    public var bizDomain: Int { 27 }
    public var funcDomain: Int { 0 }

    public var rawValue: Int {
        switch self {
        case .emptySession:
            return 1
        case .authFailed:
            return 2
        }
    }
    
    public var errString: String {
        switch self {
        case .emptySession:
            return "Unable to get session"
        case .authFailed(let code, let message):
            return "Authorization terminated unexpectedly. Error code: \(code); error message: \(message)"
        }
    }
}
