//
//  OpenAPILocationErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 31846
//  

/// 地理位置Errno
public enum OpenAPILocationErrno: Int, OpenAPIErrnoProtocol {
    // 租户管理员关闭gps权限 通用
    case adminDisabledGPS = 1
    // 网络错误
    case network = 2
    // 定位超时
    case timeout = 3
    // 定位失败
    case locationFail = 4
    // google位置服务不可用（Android特有）
    case googleNotAvailable = 5
    // 正在定位中遇到了权限问题，可能是用户关闭了定位权限
    case locatingAuthorization = 6
    // ChooseLocation 用户取消
    case userCancel = 7
    // 获取位置信息失败
    case queryFails = 8
    // 租户管理员在后端关闭了高德SDK，需要联系管理员处理
    case adminDisabledAmapSdk = 9
    // 获取poi信息失败
    case retrievePoiFailed = 10
    // 不支持radius参数
    case paramRadiusNotSupport = 11

    public var bizDomain: Int { 17 }
    public var funcDomain: Int { 0 }
    
    public var errString: String {
        switch self {
        case .adminDisabledGPS:
            return "The admin has disabled access to location"
        case .network:
            return "Network error"
        case .timeout:
            return "Location request timed out"
        case .locationFail:
            return "Unable to access location"
        case .googleNotAvailable:
            return "Google services not available. Please install Google services first"
        case .locatingAuthorization:
            return "Please check the status of location services and access to location"
        case .userCancel:
            return "The user exited the location selection page without sending location"
        case .queryFails:
            return "Reverse geocode request yielded no result"
        case .adminDisabledAmapSdk:
            return "The admin has disabled AMap sdk"
        case .retrievePoiFailed:
            return "Unable to retrieve POI information"
        case .paramRadiusNotSupport:
            return "Parameter radius is not supported"
        }
    }
}
