//
//  OpenAPIDriveCloudErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26286
//

/// Drive 云空间Errno
public enum OpenAPIDriveCloudErrno: OpenAPIErrnoProtocol {
    // Drive SDK 的报错
    case driveSdkError(errorDetail: String)
    // files和fileToken不能同时为空
    case fileTokenAndFilesCanNotBothEmpty
    // files和fileToken不能同时存在
    case fileTokenAndFilesCanNotBothExist
    // 任务已完成
    case taskCompleted

    public var bizDomain: Int { 25 }
    public var funcDomain: Int { 0 }

    public var rawValue: Int {
        switch self {
        case .driveSdkError:
            return 1
        case .fileTokenAndFilesCanNotBothEmpty:
            return 2
        case .fileTokenAndFilesCanNotBothExist:
            return 3
        case .taskCompleted:
            return 4
        }
    }

    public var errString: String {
        switch self {
        case .driveSdkError(let errorDetail):
            return "Error in Drive SDK. \(errorDetail)"
        case .fileTokenAndFilesCanNotBothEmpty:
            return "Files and fileToken cannot be both empty"
        case .fileTokenAndFilesCanNotBothExist:
            return "Files and fileToken cannot both exist"
        case .taskCompleted:
            return "Task completed"
        }
    }
}
