//
//  OpenAPILingoErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26741
//

/// 开放接口-飞书字典Errno
public enum OpenAPILingoErrno: Int, OpenAPIErrnoProtocol {
    // id和query不能都为空
    case idAndQueryBothEmpty = 1

    public var bizDomain: Int { 10 }
    public var funcDomain: Int { 17 }
    
    public var errString: String {
        switch self {
        case .idAndQueryBothEmpty:
            return "ID and query cannot both be empty"
        }
    }
}
