//
//  OpenAPIScanCodeErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 24023
//  

/// 设备-扫码Errno
public enum OpenAPIScanCodeErrno: OpenAPIErrnoProtocol {
    // 正在扫码，请不要重复调用
    case scanning
    // 用户主动取消扫码操作
    case userCanceled

    public var bizDomain: Int { 15 }
    public var funcDomain: Int { 5 }

    public var rawValue: Int {
        switch self {
        case .scanning:
            return 1
        case .userCanceled:
            return 2
        }
    }
    
    public var errString: String {
        switch self {
        case .scanning:
            return "Scanning now. Please do not call the API again"
        case .userCanceled:
            return "User canceled scanning"
        }
    }
}
