//
//  OpenAPIGetUpdateManagerErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 27347
//  

/// 更新-getUpdateManagerErrno
public enum OpenAPIGetUpdateManagerErrno: Int, OpenAPIErrnoProtocol {
    // 无需更新
    case notNeedUpdate = 1
    // 无法获取最新应用信息
    case fetchAppInfoFailed = 2
    // 调用次数已达上限
    case tryTimeLimited = 3

    public var bizDomain: Int { 20 }
    public var funcDomain: Int { 0 }
    
    public var errString: String {
        switch self {
        case .notNeedUpdate:
            return "No need to update"
        case .fetchAppInfoFailed:
            return "Unable to get the latest app information"
        case .tryTimeLimited:
            return "API rate limit exceeded"
        }
    }
}
