//
//  OpenAPIShareErrno.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 31515
//  

/// 开放接口-分享Errno
public enum OpenAPIShareErrno: Int, OpenAPIErrnoProtocol {
    // Unable to share due to your organization's security configuration
    case securityPermissionDenied = 1

    public var bizDomain: Int { 10 }
    public var funcDomain: Int { 6 }
    
    public var errString: String {
        switch self {
        case .securityPermissionDenied:
            return "Unable to share due to your organization's security configuration"
        }
    }
}
