//
//  OpenPluginMsgCardShowConfirmModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 28259
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginMsgCardShowConfirmRequest
final class UniversalCardShowConfirmRequest: OpenAPIBaseParams {
    
    /// description: 弹窗标题
    @OpenAPIOptionalParam(
            jsonKey: "title")
    var title: String?
    
    /// description: 弹窗内容
    @OpenAPIOptionalParam(
            jsonKey: "text")
    var text: String?
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_title, _text]
    }
}
