//
//  OpenPluginMsgCardSendRequestModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 28256
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginMsgCardSendRequestRequest
final class OpenPluginMsgCardSendRequestRequest: OpenAPIBaseParams {
    
    /// description: 组件 ID
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "elementID")
    var elementID: String
    
    /// description: 组件 tag
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "tag")
    var tag: String
    
    /// description: 组件 name（form 内必填）
    @OpenAPIOptionalParam(
            jsonKey: "name")
    var name: String?
    
    /// description: actionID
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "actionID")
    var actionID: String
    
    /// description: 请求参数（要求{string:string}）
    @OpenAPIOptionalParam(
            jsonKey: "params")
    var params: [AnyHashable: Any]?
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_elementID, _tag, _name, _actionID, _params]
    }
}
// MARK: - OpenPluginMsgCardShowSelectMenuResponse
final class MessageCardSendRequestResponse: OpenAPIBaseResult {
    /// description: 当前选中的值对应的文本
    let resultType: String
    init(result: String) {
        self.resultType = result
        super.init()
    }

    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["result"] = resultType
        return result
    }
}
