filegroup(
    name = "ji_ld",
    srcs = [":bitsky_jild/bin/ld"],
    visibility = [
        "//visibility:public"
    ],
)

filegroup(
    name = "kun_ld",
    srcs = [":bitsky_jild/bin/ld-classic"],
    visibility = [
        "//visibility:public"
    ],
)