//
//  BaseAssembly.swift
//  Lark
//
//  Auto generated by lark-project.
//  See more: https://bytedance.feishu.cn/docx/doxcnDjV99CCJ2qcihUE453Qaqg
//

import Foundation
import LarkAssembler
import AppContainer
import LKLoadable

final class BaseAssembly: LarkAssemblyInterface {
    lazy var subAssemblies = lazySubAssemblies()

    func getSubAssemblies() -> [LarkAssemblyInterface]? {
        return subAssemblies
    }

    private func lazySubAssemblies() -> [LarkAssemblyInterface] {
        let assemblies = allAssemblies()
        var set = Set<ObjectIdentifier>()
        for ass in assemblies {
            recordAllSubAssemblies(in: &set, for: ass)
        }
        return assemblies.filter { !set.contains(ObjectIdentifier(type(of: $0))) }
    }

    private func recordAllSubAssemblies(in set: inout Set<ObjectIdentifier>, for ass: LarkAssemblyInterface) {
        let subs = ass.getSubAssemblies() ?? []
        guard !subs.isEmpty else { return }
        subs.lazy.forEach {
            set.insert(ObjectIdentifier(type(of: $0)))
            $0.getSubAssemblies()?.forEach { recordAllSubAssemblies(in: &set, for: $0) }
        }
    }
}

import LarkAccount
import AnimatedTabBar
import LarkAppLinkSDK
import LarkBadgeAssembly
import Blockit
import LarkCacheAssembly
import Calendar
import LarkCloudScheme
import LarkAppConfig
import LarkDebug
import LarkLaunchGuide
import ECOInfra
import LarkEmotion
import LarkAccountAssembly
import CalendarMod
import LarkCoreLocation
import LarkDocsIcon
import LarkDynamicResource
import LarkEMM
import LarkFontAssembly
import LarkGuide
import LarkMagicAssembly
import LarkMonitor
import LarkNavigationAssembly
import LarkSceneManagerAssembly
import LarkShareContainer
import LarkSnsShare
import LarkStorageAssembly
import LarkLeanMode
import LarkMagic
import LarkNavigation
import LarkPrivacyAlert
import LarkQRCode
import LarkRustClientAssembly
import SecSDK
import LarkSecurityAudit
import LarkSecurityComplianceInfra
import LarkSetting
import LarkSettingsBundle
import SuiteAppConfig
import LarkSuspendable
import LarkVideoDirector
import LarkWaterMark
import ZeroTrust
import LarkAI

private func allAssemblies() -> [LarkAssemblyInterface] {
    return [
        AccountAssembly(),
        AnimatedTabBarAssembly(),
        AppLinkAssembly(),
        BadgeAssembly(),
        BlockitAssembly(),
        CacheManagerAssembly(),
        CalendarAssembly(),
        CloudSchemeAssembly(),
        ConfigAssembly(),
        DebugAssembly(),
        DefaultLaunchGuideDependencyAssembly(),
        ECOCookieAssembly(),
        ECONetworkAssembly(),
        EmotionAssembly(),
        LarkAccountAssembly(),
        LarkCalendarAssembly(),
        LarkCoreLocationAssembly(),
        LarkDocsIconAssembly(),
        LarkDynamicResourceAssembly(),
        LarkEMMAssembly(),
        LarkFontAssembly(),
        LarkGuideAssembly(),
        LarkMagicAssembly(),
        LarkMonitorAssembly(),
        LarkNavigationAssembly(),
        LarkSceneManagerAssembly(),
        LarkShareContainerAssembly(),
        LarkSnsShareAssembly(),
        LarkSnsShareBaseAssembly(),
        LarkStorageAssembly(),
        LaunchGuideAssembly(),
        LeanModeAssembly(),
        MagicAssembly(),
        NavigationAssembly(),
        PrivacyAlertAssembly(),
        QRCodeAssembly(),
        RustClientAssembly(),
        SecGuardAssembly(),
        SecurityAuditAssembly(),
        SecurityComplianceInfraAssembly(),
        SettingAssembly(),
        SettingsBundleAssembly(),
        SuiteAppConfigAssembly(),
        SuspendAssembly(),
        VideoDirectorAssembly(),
        AIAssembly(),
        WaterMarkAssembly(),
        ZeroTrustAssembly()
    ]
}
