//
//  OpenPluginShowMsgCardOverflowModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 25434
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginShowMsgCardOverflowRequest
public final class UniversalCardShowOverflowRequest: OpenAPIBaseParams {
    
    /// description: 选项列表
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "options")
    public var options: [OptionsItem]
    
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "elementID")
    public var elementID: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_options, _elementID]
    }

    // MARK: OptionsItem
    public final class OptionsItem: OpenAPIBaseParams {

        /// description: 选项文本
        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "text")
        public var text: String

        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "actions")
        public var actions: [ActionsItem]

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_text, _actions]
        }
    }

    // MARK: ActionsItem
    public final class ActionsItem: OpenAPIBaseParams {

        /// description: action 类型
        /// type = open_url 打开页面
        /// type = action_request 发送请求
        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "type")
        public var type: TypeEnum

        /// description: url 参数
        @OpenAPIOptionalParam(
            jsonKey: "url")
        public var url: String?

        /// description: actionId
        @OpenAPIOptionalParam(
            jsonKey: "actionID")
        public var actionID: String?

        @OpenAPIOptionalParam(
            jsonKey: "value")
        public var value: String?

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_type, _url, _actionID, _value]
        }
    }

    // MARK: TypeEnum
    public enum TypeEnum: String, OpenAPIEnum {

        /// description: 打开页面
        case openUrl = "open_url"

        /// description: 发送请求
        case actionRequest = "action_request"

    }
}

// MARK: - OpenPluginMsgCardShowDatePickerResponse
final class UniversalCardShowOverflowResponse: OpenAPIBaseResult {

    /// description: 当前action值
    public var actions: [UniversalCardShowOverflowRequest.ActionsItem]

    init(actions: [UniversalCardShowOverflowRequest.ActionsItem]) {
        self.actions = actions
        super.init()
    }

    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        let actionsDict = actions.map { action in
            var result = ["type": action.type.rawValue]
            if let url = action.url { result["url"] = url }
            if let actionID = action.actionID { result["actionID"] = actionID }
            if let value = action.value { result["value"] = value }
            return result
        }
        result["actions"] = actionsDict
        return result
    }
}
