// DO NOT EDIT.
//
// Generated by the Swift generator for OPMonitorCode.
// Source: https://bytedance.feishu.cn/sheets/shtcnCCboz4CUWBUtZkdmZV0PLb?sheet=uzkrAe&table=tbl98lEAFODMFOIq&view=vewt6pm4Or
// Date:   2021/03/12 14:14
//
// For information on using the generated types, please see the documentation:
//  https://bytedance.feishu.cn/sheets/shtcnCCboz4CUWBUtZkdmZV0PLb

import Foundation
import LarkOPInterface

@objcMembers
public final class OPBlockitMonitorCodeLaunch: OPMonitorCode {

    /// Block启动未知异常
    public static let unknown_error = OPBlockitMonitorCodeLaunch(code: 10000, level: OPMonitorLevelError, message: "unknown_error")

    /// Block启动成功
    public static let success = OPBlockitMonitorCodeLaunch(code: 10001, level: OPMonitorLevelNormal, message: "success")

    /// Block启动取消
    public static let cancel = OPBlockitMonitorCodeLaunch(code: 10002, level: OPMonitorLevelError, message: "cancel")

    /// Block启动失败 - 设备类型在黑名单内
    public static let device_unavailable = OPBlockitMonitorCodeLaunch(code: 10003, level: OPMonitorLevelError, message: "device_unavailable")

    /// Block启动失败 - 自定义环境判断失败
    public static let environment_invalid = OPBlockitMonitorCodeLaunch(code: 10004, level: OPMonitorLevelError, message: "environment_invalid")

    /// Block启动失败 - 无效的appID
    public static let invalid_appid = OPBlockitMonitorCodeLaunch(code: 10005, level: OPMonitorLevelError, message: "invalid_appid")

    /// Block启动失败 - 无效的host
    public static let invalid_host = OPBlockitMonitorCodeLaunch(code: 10006, level: OPMonitorLevelError, message: "invalid_host")

    /// Block启动失败 - Meta请求失败
    public static let meta_info_fail = OPBlockitMonitorCodeLaunch(code: 10009, level: OPMonitorLevelError, message: "meta_info_fail")

    /// Block启动失败 - 下载失败
    public static let download_fail = OPBlockitMonitorCodeLaunch(code: 10010, level: OPMonitorLevelError, message: "download_fail")

    /// Block启动失败 - 已下架
    public static let offline = OPBlockitMonitorCodeLaunch(code: 10011, level: OPMonitorLevelError, message: "offline")

    /// 小程序启动失败 - JSSDK版本过低
    public static let jssdk_old = OPBlockitMonitorCodeLaunch(code: 10012, level: OPMonitorLevelError, message: "jssdk_old")

    /// Block启动失败 - 当前用户无权限访问小程序
    public static let no_permission = OPBlockitMonitorCodeLaunch(code: 10014, level: OPMonitorLevelError, message: "no_permission")

    /// Block启动失败 - 小程序不支持当前宿主环境
    public static let incompatible = OPBlockitMonitorCodeLaunch(code: 10015, level: OPMonitorLevelError, message: "incompatible")

    /// 小程序启动超时
    public static let timeout = OPBlockitMonitorCodeLaunch(code: 10020, level: OPMonitorLevelError, message: "timeout")

    /// 小程序启动失败 - 解析BlockConfig失败
    public static let parse_block_config_failed = OPBlockitMonitorCodeLaunch(code: 10025, level: OPMonitorLevelError, message: "parse_block_config_failed")

    /// 小程序启动失败 - app-service.js 失败或者page-frame.js失败，导致没有document ready
    public static let on_document_ready_error = OPBlockitMonitorCodeLaunch(code: 10036, level: OPMonitorLevelError, message: "on_document_ready_error")

    /// Block启动失败 - 不合法的启动参数
    public static let invalid_init_params = OPBlockitMonitorCodeLaunch(code: 10039, level: OPMonitorLevelError, message: "invalid_init_params")

    /// Blockit启动失败-不合法的block_type_id
    public static let invalid_block_type_id = OPBlockitMonitorCodeLaunch(code: 10040, level: OPMonitorLevelError, message: "invalid_block_type_id")

    /// 启动失败 - guide info 中 status 无法处理
    public static let guide_info_status_invalid = OPBlockitMonitorCodeLaunch(code: 10041, level: OPMonitorLevelError, message: "guide_info_status_invalid")

    /// 启动失败 - 客户端版本太低需要升级
    public static let client_need_update = OPBlockitMonitorCodeLaunch(code: 10042, level: OPMonitorLevelError, message: "client_need_update")

    /// 启动失败 - guide info status 不允许启动
    public static let guide_info_status_unable = OPBlockitMonitorCodeLaunch(code: 10043, level: OPMonitorLevelError, message: "guide_info_status_unable")

    /// 启动失败 - 请求失败
    public static let guide_info_request_error = OPBlockitMonitorCodeLaunch(code: 10044, level: OPMonitorLevelError, message: "guide_info_request_error")


    private init(code: Int, level: OPMonitorLevel, message: String) {
        super.init(domain: OPBlockitMonitorCodeLaunch.domain, code: code, level: level, message: message)
    }

    public static let domain = "client.open_platform.blockit.launch"
}

@objcMembers
public final class OPBlockitMonitorCodeAppLoad: OPMonitorCode {

    /// 容器创建开始
    public static let app_container_create = OPBlockitMonitorCodeAppLoad(code: 10000, level: OPMonitorLevelNormal, message: "app_container_create")

    /// 容器创建完成
    public static let app_container_loaded = OPBlockitMonitorCodeAppLoad(code: 10001, level: OPMonitorLevelNormal, message: "app_container_loaded")

    /// App 启动开始
    public static let app_launch_start = OPBlockitMonitorCodeAppLoad(code: 10002, level: OPMonitorLevelNormal, message: "app_launch_start")

    /// App 启动结束
    public static let app_launch_end = OPBlockitMonitorCodeAppLoad(code: 10003, level: OPMonitorLevelNormal, message: "app_launch_end")

    /// Meta & Pkg加载启动
    public static let meta_pkg_load_start = OPBlockitMonitorCodeAppLoad(code: 10004, level: OPMonitorLevelNormal, message: "meta_pkg_load_start")

    /// Meta加载结束
    public static let meta_load_end = OPBlockitMonitorCodeAppLoad(code: 10005, level: OPMonitorLevelNormal, message: "meta_load_end")

    /// PKG加载结束
    public static let pkg_load_end = OPBlockitMonitorCodeAppLoad(code: 10006, level: OPMonitorLevelNormal, message: "pkg_load_end")

    /// Component加载开始
    public static let component_load_start = OPBlockitMonitorCodeAppLoad(code: 10007, level: OPMonitorLevelNormal, message: "component_load_start")

    /// Component加载结束
    public static let component_load_end = OPBlockitMonitorCodeAppLoad(code: 10008, level: OPMonitorLevelNormal, message: "component_load_end")

    /// Render加载开始
    public static let render_load_start = OPBlockitMonitorCodeAppLoad(code: 10009, level: OPMonitorLevelNormal, message: "render_load_start")

    /// Render加载结束
    public static let render_load_end = OPBlockitMonitorCodeAppLoad(code: 10010, level: OPMonitorLevelNormal, message: "render_load_end")

    /// 运行时加载结束
    public static let runtime_load_end = OPBlockitMonitorCodeAppLoad(code: 10011, level: OPMonitorLevelNormal, message: "runtime_load_end")

    /// 首帧渲染结束
    public static let first_content_render_finish = OPBlockitMonitorCodeAppLoad(code: 10012, level: OPMonitorLevelNormal, message: "first_content_render_finish")


    private init(code: Int, level: OPMonitorLevel, message: String) {
        super.init(domain: OPBlockitMonitorCodeAppLoad.domain, code: code, level: level, message: message)
    }

    public static let domain = "client.open_platform.blockit.app_load"
}
