//
//  Logger.swift
//  ByteView
//
//  Created by kiri on 2020/8/26.
//  Copyright © 2020 Bytedance.Inc. All rights reserved.
//

import Foundation

// 日志上报量统计 https://bytedance.feishu.cn/docx/doxcnPPDTaFi4UBvrh1jVUJO0Kg
extension Logger {
    static let base = getLogger("Base")
    static let interface = getLogger("Interface")
    static let byteRtc = getLogger("ByteRtc")
    static let byteRtcSDK = getLogger("ByteRtcSDK.Log")
    static let grid = getLogger("Grid")
    static let camera = getLogger("Camera")
    static let callKit = getLogger("Meeting.CallKit")
    static let sketch = getLogger("Sketch")
    static let sketchSDK = getLogger("SketchSDK")
    static let vcFollow = getLogger("VCFollow")
    static let liveSetting = getLogger("LiveSetting")
    static let policy = getLogger("Policy")
    static let audioSession = getLogger("AudioSession")
    static let audio = getLogger("Audio")
    static let window = getLogger("Window")
    static let im = getLogger("IM")
    static let participant = getLogger("Participant")
    static let liveCert = getLogger("LiveCert")
    static let lab = getLogger("VCLab")
    static let effect = getLogger("Effect")
    static let effectBackGround = getLogger("Effect.BackGround")
    static let effectPretend = getLogger("Effect.Pretend")
    static let context = getLogger("Context")
    static let router = getLogger("Router")
    static let cert = getLogger("Cert")
    static let Prompt = getLogger("Prompt")
    static let preview = getLogger("Preview")
    static let callOut = getLogger("CallOut")
    static let clientMutex = getLogger("ClientMutex")
    static let interpretation = getLogger("Interpretation")
    static let subtitle = getLogger("Subtitle")
    static let chatMessage = getLogger("ChatMessage")
    static let tab = getLogger("MeetTab")
    static let meetingList = getLogger("Meeting.List")
    static let meetingDetail = getLogger("Meeting.Detail")
    static let live = getLogger("VCLive")
    static let streamManager = getLogger("StreamManager")
    static let renderView = getLogger("RenderView")
    static let tabBadge = getLogger("TabBadge")
    static let localShare = getLogger("LocalShare")
    static let breakoutRoom = getLogger("BreakoutRoom")
    static let transition = getLogger("Transition")
    static let howling = getLogger("Howling")
    static let countDown = getLogger("CountDown")
    static let selfShareScreen = getLogger("SelfShareScreen")
    static let otherShareScreen = getLogger("OtherShareScreen")
    static let debug = getLogger("Debug")
    static let ring = getLogger("Ring")
    static let ringRefuse = getLogger("RingRefuse")
    static let phoneCallDial = getLogger("PhoneCallDial")
    static let phoneCall = getLogger("PhoneCall")
    static let ultrawave = getLogger("Ultrawave")
    static let feedback = getLogger("Feedback")
    static let whiteboard = getLogger("Whiteboard")
    static let callme = getLogger("Callme")
    static let networkStatus = getLogger("NetworkStatus")
    static let scene = getLogger("Scene")
    static let shareScreenToFollow = getLogger("ShareScreenToFollow")
    static let pip = getLogger("PIP")
    static let imChat = getLogger("IMChat")
    static let webSpace = getLogger("WebSpace")
    static let shareContent = getLogger("ShareContent")
    static let audioMode = getLogger("AudioMode")
    static let notes = getLogger("Notes")
    static let myAI = getLogger("MyAI")
    static let enterpriseCall = getLogger("enterpriseCall")
    static let precheck = getLogger("precheck")
}
