included:
  - Bizs/
excluded:
  - Apps/
  - Pods/
  - Bizs/CTFoundation/src/configurations/BundleI18n.swift
  - Bizs/Calendar/src/configurations/BundleI18n.swift
  - Bizs/CalendarFoundation/src/configurations/BundleI18n.swift
  - Bizs/CalendarRichTextEditor/src/configurations/BundleI18n.swift
  - Libs/LarkTimeFormatUtils/src/configurations/BundleI18n.swift
only_rules:
  - implicitly_unwrapped
implicitly_unwrapped:
  excluded:
    - UIKit
    - CalendarFoundation.Component.viewController
