# coding: utf-8
# @!domain [Pod::Podfile]
# @!parse
#  require 'cocoapods'
`git config core.hooksPath hooks`

require_relative '../../if_pod'
require_relative '../../bin/lib/lark-project/lib/lark/project/podfile_mixin'
require_relative '../../bin/lib/lark-project/lib/lark/project/assembly'

# 不进行 dependency 检查
ENV['CHECK_ARCH_DEPS'] = "false"
# 不需要自动登录
ENV['bytest_autoLogin'] = 'false'

hummer_tags = {}
hummer_tags["COCOAPODS_LINK_POD_CACHE"] = 1 if Lark::Misc.true? ENV['COCOAPODS_LINK_POD_CACHE']
hummer_tags["COCOAPODS_INTEGRATE_SPECIFIC_TARGETS"] = 1 if Lark::Misc.true? ENV['COCOAPODS_INTEGRATE_SPECIFIC_TARGETS']
lark_template_common_setup(hummer_tags: hummer_tags)

strict_lock_mode!

disable_swiftlint! if respond_to?(:disable_swiftlint!)

dev_pods = %w[
  CalendarMod
  CalendarFoundation
  CalendarRichTextEditor
  LarkTimeFormatUtils
  Calendar
  CTFoundation
]

lark_use_common_binary_config(strategy: :all) do
  # additional config
  source_pods = %w[
      RichLabel
      AsyncComponent
  ]
  dev_pods.each { |v| source v } # dev pod 使用源码
  source_pods.each { |v| source v } # dev pod 使用源码
end

target 'CalendarDemo' do
  lark_main_target_if_pods

  # 壳工程额外需要
  pod 'LarkRustClientAssembly'
  pod 'LarkQRCode'
  pod 'SwiftLint', :configurations => ['Debug']
  pod 'FLEX', :configurations => ['Debug']
  pod 'LookinServer', configurations: ['Debug']
  pod 'LarkMonitor'
  pod 'LarkAccount'
  pod 'PassportDebug'
  pod 'EEKeyValue'

  messengerDependency = false
  if messengerDependency
    pod 'MessengerMod'
    pod 'Lynx'
  end

  dev_pods.each { |v| pod v, inhibit_warnings: false }
end

# @param installer [Pod::Installer]
pre_install do |installer|
  lark_template_common_pre_install installer

  # installer.pod_targets.each do |pod_target|
  #   attributes_hash = pod_target.root_spec.attributes_hash
  #   pod_target_xcconfig = (attributes_hash['pod_target_xcconfig'] ||= {})
  #   # additional config
  # end
end

# @param installer [Pod::Installer]
post_install do |installer|
  lark_template_common_post_install installer

  # 自动收集 Assembly，生成/更新 BaseAssembly.swift
  Assembly.rebuild installer
end

# Podfile结束eval前需要执行的一些代码，目前是引用if_pod的集成需要延后生效
flush_defer_actions!
