included:
  - MailSDK/Foundation
  - MailSDK/Mail
  - MailSDK/MailFoundation
  - MailSDK/MailUIKit
excluded:
  - MailSDK/Resources
  - MailSDK/src
  - LarkMailInterface
  - Example
  - Scripts
disabled_rules:
  - force_try # 是否允许try!，存在这种代码。。后续一起确定下
  - force_cast # 是否允许 as! 强转的出现？需要一起确定下
  - explicit_init # 个人使用习惯，init能快速让编译器出现代码补全提示
  - shorthand_operator # 个人使用习惯，代码中有大量的人不使用+=、*=、-=等操作符。所以不做要求
  - number_separator # 长位数数字添加下划线
  - vertical_parameter_alignment
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - type_name
  - identifier_name
  - object_literal
  - private_over_fileprivate
  - multiple_closures_with_trailing_closure
  - empty_count # 倾向使用isEmpty接口替代count>0，swiftlint里面这项规则是属于performance？？ 影响开发效率，去掉
  - redundant_optional_initialization # 初始化nil变量是,不建议赋值nil
  - unused_closure_parameter # 没用到的闭包函数
opt_in_rules:
  - empty_string
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - prohibited_super_call
  - fatal_error_message
  - weak_delegate # 代理应该写成weak类型（弱代理）来避免循环引用
  - file_header # 文件头部内容

# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*?\.swift
#                     \/\/  Lark((UI)?Tests)?
#                     \/\/
#                     \/\/  Created by .*? on \d+\/\d+\/\d+\.
#                     \/\/  Copyright © \d{4}年 Bytedance\.Inc\. All rights reserved\.
#                     \/\/
line_length: 200
# force_cast: warning
empty_string: error
weak_delegate: error
weak_computed_property: error
function_parameter_count: 9
identifier_name:
  min_length: 1
  excluded:
    - i
large_tuple: 3
