//
//  OpenPluginShowMsgCardOverflowModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 25434
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginShowMsgCardOverflowRequest
public final class OpenPluginShowMsgCardOverflowRequest: OpenAPIBaseParams {
    
    /// description: 选项列表
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "options")
    public var options: [OptionsItem]
    
    /// description: 二次确认
    @OpenAPIOptionalParam(
            jsonKey: "confirm")
    public var confirm: ConfirmObject?
    
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "elementID")
    public var elementID: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_options, _confirm, _elementID]
    }

    // MARK: OptionsItem
    public final class OptionsItem: OpenAPIBaseParams {

        /// description: 选项文本
        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "text")
        public var text: String

        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "actions")
        public var actions: [ActionsItem]

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_text, _actions]
        }
    }

    // MARK: ActionsItem
    public final class ActionsItem: OpenAPIBaseParams {

        /// description: action 类型
        /// type = open_url 打开页面
        /// type = action_request 发送请求
        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "type")
        public var type: TypeEnum

        /// description: url 参数
        @OpenAPIOptionalParam(
            jsonKey: "url")
        public var url: String?

        /// description: actionId
        @OpenAPIOptionalParam(
            jsonKey: "actionID")
        public var actionID: String?

        @OpenAPIOptionalParam(
            jsonKey: "value")
        public var value: String?

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_type, _url, _actionID, _value]
        }
    }

    // MARK: TypeEnum
    public enum TypeEnum: String, OpenAPIEnum {

        /// description: 打开页面
        case openUrl = "open_url"

        /// description: 发送请求
        case actionRequest = "action_request"

    }

    // MARK: ConfirmObject
    public final class ConfirmObject: OpenAPIBaseParams {

        /// description: 二次确认弹窗的title
        @OpenAPIOptionalParam(
                jsonKey: "title")
        public var title: String?

        /// description: 二次确认弹窗的text
        @OpenAPIOptionalParam(
                jsonKey: "text")
        public var text: String?

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_title, _text]
        }
    }
}
