included:
  - LarkSecurityCompliance
  - LarkSecurityComplianceInfra
  - LarkSecurityComplianceInterface
  - LarkEMM
  - LarkSecurityAudit
  - LarkPrivacyMonitor
  - LarkSensitivityControl
  - LarkSnCService
  - LarkPolicyEngine
  - LarkWaterMark
  - SecurityComplianceDebug
  - SCDemoImp
excluded:
  - Pods
  - "**/*/*.pb.swift"
  - SecurityComplianceDebug
  - LarkSecurityAudit/src/Core/Generated
disabled_rules:
  - empty_enum_arguments # 这个规则会误报`if !xxx.xxx()`, 先禁止掉
  - vertical_parameter_alignment
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - type_name
  - identifier_name
  - object_literal
  - private_over_fileprivate
  - multiple_closures_with_trailing_closure
  - orphaned_doc_comment
  - todo
  - syntactic_sugar
  - file_header
  - trailing_whitespace
opt_in_rules:
  - expiring_todo
  - explicit_init
  - empty_count
  - empty_string
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - anyobject_protocol
  - required_enum_case
  - force_cast

custom_rules:
  init_color_with_token:
    name: "Color Init"
    regex: "UIColor\\.init*|UIColor\\.(?!clear|ud).*|UIColor\\(.*\\)"
    message: "Please use UniverseDesign Color"
    severity: warning
line_length: 190
force_cast: warning
empty_string: error
warning_threshold: 1
function_parameter_count: 9
identifier_name:
  min_length: 1
  excluded:
    - i
number_separator:
  minimum_length: 5
large_tuple: 3
