//
//  OpenPluginGetPerformanceEntriesSyncModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 28143
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginGetPerformanceEntriesSyncResponse
final class OpenPluginGetPerformanceEntriesSyncResponse: OpenAPIBaseResult {
    
    let entries: [EntriesItem]
    
    init(entries: [EntriesItem]) {
        self.entries = entries
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["entries"] = entries.map({ $0.toJSONDict() })
        return result
    }

    // MARK: EntriesItem
    final class EntriesItem: OpenAPIBaseResult {

        /// description: 该 performance entry 的名字
        let name: String

        /// description: 代表所上报的 performance metric 的 entryType 类型，例如 "launch"、"script"
        let entryType: String

        /// description: 开始时间
        let startTime: Double

        /// description: 时长
        let duration: Double?

        /// description: 文件名
        let fileName: String?

        /// description: 标识是否有包
        let isPreload: Bool?

        /// description: 对应页面实例 Id
        let webviewId: Int?

        init(name: String, entryType: String, startTime: Double, duration: Double?, fileName: String?, isPreload: Bool?, webviewId: Int?) {
            self.name = name
            self.entryType = entryType
            self.startTime = startTime
            self.duration = duration
            self.fileName = fileName
            self.isPreload = isPreload
            self.webviewId = webviewId
            super.init()
        }

        override func toJSONDict() -> [AnyHashable : Any] {
            var result: [AnyHashable : Any] = [:]
            result["name"] = name
            result["entryType"] = entryType
            result["startTime"] = startTime
            result["duration"] = duration
            result["fileName"] = fileName
            result["isPreload"] = isPreload
            result["webviewId"] = webviewId
            return result
        }
    }
}
