//
//  OpenPluginSearchPOIModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 31846
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginSearchPOIRequest
final class OpenPluginSearchPOIRequest: OpenAPIBaseParams {
    
    /// description: 纬度
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "latitude")
    var latitude: Double
    
    /// description: 经度
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "longitude")
    var longitude: Double
    
    /// description: 半径，以米为单位
    @OpenAPIOptionalParam(
            jsonKey: "radius")
    var radius: Int?
    
    /// description: 搜索关键字
    @OpenAPIOptionalParam(
            jsonKey: "keyword")
    var keyword: String?
    
    /// description: 返回位置数量上限
    @OpenAPIRequiredParam(
            userOptionWithJsonKey: "maxCount",
            defaultValue: 24)
    var maxCount: Int
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_latitude, _longitude, _radius, _keyword, _maxCount]
    }
}

// MARK: - OpenPluginSearchPOIResponse
final class OpenPluginSearchPOIResponse: OpenAPIBaseResult {
    
    /// description: poi列表
    let poiList: [PoiListItem]
    
    init(poiList: [PoiListItem]) {
        self.poiList = poiList
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["poiList"] = poiList.map({ $0.toJSONDict() })
        return result
    }

    // MARK: PoiListItem
    final class PoiListItem: OpenAPIBaseResult {

        /// description: 纬度
        let latitude: Double

        /// description: 经度
        let longitude: Double

        /// description: 位置名称
        let locationName: String

        /// description: 位置详细地址
        let locationAddress: String

        init(latitude: Double, longitude: Double, locationName: String, locationAddress: String) {
            self.latitude = latitude
            self.longitude = longitude
            self.locationName = locationName
            self.locationAddress = locationAddress
            super.init()
        }

        override func toJSONDict() -> [AnyHashable : Any] {
            var result: [AnyHashable : Any] = [:]
            result["latitude"] = latitude
            result["longitude"] = longitude
            result["locationName"] = locationName
            result["locationAddress"] = locationAddress
            return result
        }
    }
}
