# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'git@code.byted.org:ee/pods_specs.git'
source 'git@code.byted.org:iOS_Library/lark_source_repo.git'
source 'git@code.byted.org:iOS_Library/publicthird_source_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_source_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_source_repo.git'

def pods
  pod 'UniverseDesignIcon', :path => '../../../../Universe/Components/UniverseDesignIcon'
  pod 'UniverseDesignColor', :path => '../../../../Universe/Components/UniverseDesignColor'
  pod 'FigmaKit', :path => '../../../../Infra/Libs/UI/FigmaKit'
  pod 'UniverseDesignFont', :path => '../../../../Universe/Components/UniverseDesignFont'
  pod 'UniverseDesignTheme', :path => '../../../../Universe/Components/UniverseDesignTheme'
  pod 'LarkLocalizations', :path => '../../../../Infra/Libs/LarkLocalizations'
  pod 'LarkModel', :subspecs => ['Base'], :path => '../../../../Infra/Libs/LarkModel'
  pod 'LarkContactComponent', :subspecs => ['Utils'], :path => '../../../../Infra/Bizs/LarkContactComponent'
  pod 'RustPB', '7.5.0'
end

target 'LarkPickerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LookinServer'
  pod 'LarkSearchCore', :subspecs => ['View'], :path => '../'
  pods
end

target 'UnitTests' do
  use_frameworks!
  pod 'LarkSearchCore', :subspecs => ['Base', 'Utils'], :path => '../'
  pods
end

target 'ViewTests' do
  use_frameworks!
  pod 'iOSSnapshotTestCase', '6.2.0'
  pod 'LarkSearchCore', :subspecs => ['View'], :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
