exclude_path:
  - '**/*Debug/'
  - '**/*[Tt]est/'
  - '**/[Tt]ests/'
  - '**/UnitTests/'
  - '**/Example/'
  - '**/app/{app,test,ViewTests}/'
  - '**/*Demo/'

module_to_pod:
  AMapFoundationKit: AMapFoundation-NO-IDFA
  AMapLocationKit: AMapLocation-NO-IDFA
  AMapSearchKit: AMapSearch-NO-IDFA
  AnyCodable: 'AnyCodable-FlightSchool'
  AppsFlyerLib: 'AppsFlyerFramework'
  Lottie: 'lottie-ios'
  NSObject_Rx: 'NSObject+Rx'
  OCOpusCodec: oc-opus-codec
  OpenCombine: LarkOpenCombine
  OpenCombineDispatch: LarkOpenCombineDispatch
  OpenCombineFoundation: LarkOpenCombineFoundation
  Reachability: 'ReachabilitySwift'
  SQLCipher: LarkSQLCipher
  SQLite: SQLite.swift
  SQLiteMigrationManager: SQLiteMigrationManager.swift
  SocketIO: 'Socket.IO-Client-Swift'
  VolcEngineRTC: ByteRtcSDK
  libPhoneNumber_iOS: 'libPhoneNumber-iOS'
  yoga: Yoga

# system or speical deps ignored for missing or extra check
ignored_deps:
  # special deps
  - CaptchaTokenCrypto # only deps in LarkAccount
  # allowed indirect deps
  - RxRelay
  - LarkLocalizations
  # special deps
  - COpenCombineHelpers
  - Danger
  - PackageDescription

  # additional system
  - iAd
  - AppKit
  - AudioUnit
  - XCTest
  - Glibc
  - FoundationNetworking
  - WatchKit

  # modulemap
  - AppleArchive
  - AppleTextureEncoder
  - AssertMacros
  - Availability
  - C
  - CommonCrypto
  - Compression
  - ConditionalMacros
  - Darwin
  - Dispatch
  - DispatchIntrospection
  - Error
  - Ext
  - HTMLparser
  - HTMLtree
  - ICU
  - MacTypes
  - Mach
  - MachO
  - NSObject
  - OSAtomic
  - OSByteOrder
  - OSCacheControl
  - OSReturn
  - OSTypes
  - ObjectiveC
  - POSIX
  - Random
  - SAX
  - SAX2
  - SQLite3
  - Spatial
  - SwiftOverlayShims
  - SwiftShims
  - TargetConditionals
  - access
  - accumulate
  - acl
  - activity
  - add_const
  - add_cv
  - add_lvalue_reference
  - add_pointer
  - add_rvalue_reference
  - add_volatile
  - addressof
  - adjacent_difference
  - adjacent_find
  - advance
  - aio
  - algorithm
  - aligned_storage
  - aligned_union
  - alignment_of
  - all
  - all_of
  - alloca
  - allocate_at_least
  - allocation_guard
  - allocator
  - allocator_arg_t
  - allocator_traits
  - any
  - any_of
  - appleapiopts
  - apply_cv
  - arch
  - architecture
  - arithmetic
  - arpa
  - array
  - as_const
  - asl
  - asm
  - assignable
  - assume_aligned
  - atomic
  - attr
  - audit
  - audit_triggers_types
  - auto_cast
  - auto_ptr
  - back_insert_iterator
  - bank
  - bank_types
  - barrier
  - base
  - basic
  - bernoulli_distribution
  - binary_function
  - binary_negate
  - binary_search
  - bind
  - bind_back
  - bind_front
  - binder1st
  - binder2nd
  - binomial_distribution
  - bit
  - bit_cast
  - bitset
  - block
  - boolean
  - boolean_testable
  - bootstrap
  - bounded_iter
  - boyer_moore_searcher
  - bsm
  - buffer
  - byteswap
  - c14n
  - calendar
  - cassert
  - catalog
  - cauchy_distribution
  - ccomplex
  - cctype
  - cdefs
  - cerrno
  - cfenv
  - cfloat
  - char_traits
  - charconv
  - chars_format
  - chi_squared_distribution
  - chrono
  - chvalid
  - cinttypes
  - ciso646
  - clamp
  - clamp_to_integral
  - class_or_enum
  - climits
  - clocale
  - clock
  - clock_priv
  - clock_reply
  - clock_types
  - clonefile
  - cmath
  - cmp
  - codecvt
  - common_comparison_category
  - common_iterator
  - common_reference
  - common_reference_with
  - common_type
  - common_view
  - common_with
  - commpage
  - comp
  - comp_ref_type
  - compact_unwind_encoding
  - compare
  - compare_partial_order_fallback
  - compare_strong_order_fallback
  - compare_three_way
  - compare_three_way_result
  - compare_weak_order_fallback
  - compat
  - complex
  - complex_h
  - compose
  - compressed_pair
  - concepts
  - condition_variable
  - conditional
  - conjunction
  - construct_at
  - constructible
  - convert_to_timespec
  - convertible_to
  - copy
  - copy_backward
  - copy_cv
  - copy_cvref
  - copy_if
  - copy_n
  - copy_options
  - copyable
  - copyable_box
  - copyfile
  - coroutine
  - coroutine_handle
  - coroutine_traits
  - count
  - count_if
  - counted
  - counted_iterator
  - cpio
  - crt_externs
  - csetjmp
  - csignal
  - cstdarg
  - cstdbool
  - cstddef
  - cstdint
  - cstdio
  - cstdlib
  - cstring
  - ctermid
  - ctgmath
  - ctime
  - ctype
  - ctype_h
  - cuchar
  - cwchar
  - cwctype
  - dangling
  - data
  - day
  - debug
  - debugXML
  - decay
  - declval
  - default_random_engine
  - default_searcher
  - default_sentinel
  - depr
  - deque
  - derived_from
  - destructible
  - device
  - dict
  - different_from
  - directory_entry
  - directory_iterator
  - directory_options
  - dirent
  - discard_block_engine
  - discrete_distribution
  - disjunction
  - distance
  - dl
  - dlfcn
  - dnssd
  - drop_view
  - duration
  - dyld
  - dyld_kernel
  - empty
  - empty_view
  - enable_borrowed_range
  - enable_if
  - enable_insertable
  - enable_view
  - encoding
  - endian
  - entities
  - equal
  - equal_range
  - equality_comparable
  - erase_if_container
  - err
  - errno
  - errno_h
  - error
  - ethernet
  - event
  - exc
  - exception
  - exception_types
  - exchange
  - exclusive_scan
  - execution
  - experimental
  - exponential_distribution
  - extended_grapheme_cluster_table
  - extent
  - extern_template_lists
  - extreme_value_distribution
  - fat
  - fcntl
  - fenv
  - fenv_h
  - file
  - file_clock
  - file_status
  - file_time_type
  - file_type
  - filesystem
  - filesystem_error
  - filio
  - fill
  - fill_n
  - filter_view
  - find
  - find_end
  - find_first_of
  - find_if
  - find_if_not
  - fisher_f_distribution
  - float
  - fmtmsg
  - fnmatch
  - for
  - for_each
  - for_each_n
  - format
  - format_arg
  - format_arg_store
  - format_args
  - format_context
  - format_error
  - format_fwd
  - format_parse_context
  - format_string
  - format_to_n_result
  - formatter
  - formatter_bool
  - formatter_char
  - formatter_floating_point
  - formatter_integer
  - formatter_integral
  - formatter_output
  - formatter_pointer
  - formatter_string
  - forward
  - forward_list
  - fpos
  - from_chars_result
  - front_insert_iterator
  - fstream
  - ftw
  - function
  - functional
  - future
  - gamma_distribution
  - gcd_lcm
  - generate
  - generate_canonical
  - generate_n
  - geometric_distribution
  - gethostuuid
  - getopt
  - getsect
  - glob
  - globals
  - grp
  - half_positive
  - has_unique_object_representation
  - has_virtual_destructor
  - hash
  - hh_mm_ss
  - high_resolution_clock
  - host_info
  - host_notify
  - host_priv
  - host_reboot
  - host_security
  - host_special_ports
  - hv
  - icmp6
  - iconv
  - identity
  - if
  - if_var
  - if_var_status
  - ifaddrs
  - impl
  - in
  - in_found_result
  - in_fun_result
  - in_in_out_result
  - in_in_result
  - in_out_out_result
  - in_out_result
  - in_pcb
  - in_place
  - in_systm
  - includes
  - inclusive_scan
  - incrementable_traits
  - independent_bits_engine
  - indirectly_comparable
  - inet
  - initializer_list
  - inner_product
  - inplace_merge
  - insert_iterator
  - integer_sequence
  - integral_constant
  - inttypes
  - inttypes_h
  - invocable
  - invoke
  - ioccom
  - ioctl
  - iomanip
  - ios
  - iosfwd
  - iostream
  - iota
  - iota_view
  - ip
  - ip6
  - ip_icmp
  - ipc
  - ipsec
  - is
  - is_abstract
  - is_aggregate
  - is_arithmetic
  - is_array
  - is_assignable
  - is_base_of
  - is_bounded_array
  - is_callable
  - is_class
  - is_compound
  - is_const
  - is_constant_evaluated
  - is_constructible
  - is_convertible
  - is_copy_assignable
  - is_copy_constructible
  - is_core_convertible
  - is_default_constructible
  - is_destructible
  - is_empty
  - is_enum
  - is_eq
  - is_final
  - is_floating_point
  - is_function
  - is_fundamental
  - is_heap
  - is_heap_until
  - is_integral
  - is_literal_type
  - is_member_function_pointer
  - is_member_object_pointer
  - is_member_pointer
  - is_move_assignable
  - is_move_constructible
  - is_nothrow_assignable
  - is_nothrow_constructible
  - is_nothrow_convertible
  - is_nothrow_copy_assignable
  - is_nothrow_copy_constructible
  - is_nothrow_default_constructible
  - is_nothrow_destructible
  - is_nothrow_move_assignable
  - is_nothrow_move_constructible
  - is_null_pointer
  - is_object
  - is_partitioned
  - is_permutation
  - is_pod
  - is_pointer
  - is_polymorphic
  - is_primary_template
  - is_reference
  - is_reference_wrapper
  - is_referenceable
  - is_same
  - is_scalar
  - is_scoped_enum
  - is_seed_sequence
  - is_signed
  - is_signed_integer
  - is_sorted
  - is_sorted_until
  - is_standard_layout
  - is_transparent
  - is_trivial
  - is_trivially_assignable
  - is_trivially_constructible
  - is_trivially_copy_assignable
  - is_trivially_copy_constructible
  - is_trivially_copyable
  - is_trivially_default_constructible
  - is_trivially_destructible
  - is_trivially_move_assignable
  - is_trivially_move_constructible
  - is_unbounded_array
  - is_union
  - is_unsigned
  - is_unsigned_integer
  - is_valid
  - is_valid_expansion
  - is_void
  - is_volatile
  - iso646
  - istream
  - istream_iterator
  - istreambuf_iterator
  - iter_move
  - iter_swap
  - iterator
  - iterator_operations
  - iterator_traits
  - join_view
  - kauth
  - kcdata
  - kdebug
  - kern_return
  - kmod
  - knuth_b
  - langinfo
  - latch
  - lazy
  - lazy_split_view
  - lctx
  - ldsyms
  - lexicographical_compare
  - libgen
  - libkern
  - libunwind
  - libxml2
  - limits
  - linear_congruential_engine
  - list
  - literals
  - loader
  - locale
  - locale_h
  - lock
  - log
  - log2
  - lognormal_distribution
  - lower_bound
  - mach_error
  - mach_host
  - mach_init
  - mach_interface
  - mach_param
  - mach_port
  - mach_right
  - mach_syscalls
  - mach_time
  - mach_traps
  - mach_types
  - mach_voucher
  - mach_voucher_types
  - machine
  - make_32_64_or_128_bit
  - make_heap
  - make_projected
  - make_signed
  - make_unsigned
  - malloc
  - map
  - math
  - math_h
  - max
  - max_element
  - mem_fn
  - mem_fun_ref
  - memory
  - memory_entry
  - memory_object_types
  - memory_resource
  - merge
  - mergeable
  - mersenne_twister_engine
  - message
  - midpoint
  - mig
  - mig_errors
  - mig_strncpy_zerofill_support
  - mig_voucher_support
  - min
  - min_element
  - min_max_result
  - minmax
  - minmax_element
  - mismatch
  - mman
  - monetary
  - monostate
  - month
  - month_weekday
  - monthday
  - mount
  - movable
  - move
  - move_backward
  - move_iterator
  - move_sentinel
  - msg
  - mutex
  - nanoftp
  - nanohttp
  - nat
  - ndbm
  - ndr
  - ndr_def
  - negation
  - negative_binomial_distribution
  - net
  - net_kev
  - netdb
  - netinet
  - netinet6
  - networkext
  - new
  - next
  - next_permutation
  - nl_types
  - nlist
  - non_propagating_cache
  - none_of
  - noop_coroutine_handle
  - normal_distribution
  - not_fn
  - notify
  - nth_element
  - numbers
  - numeric
  - object
  - only
  - operations
  - optional
  - ordering
  - os
  - os_object
  - os_workgroup
  - ostream
  - ostream_iterator
  - ostreambuf_iterator
  - overflow
  - owning_view
  - pair
  - param
  - parser
  - parserInternals
  - parser_std_format_spec
  - partial_order
  - partial_sort
  - partial_sort_copy
  - partial_sum
  - partition
  - partition_copy
  - partition_point
  - path
  - path_iterator
  - paths
  - pattern
  - perfect_forward
  - perm_options
  - perms
  - permutable
  - pfkeyv2
  - piecewise_constant_distribution
  - piecewise_construct
  - piecewise_linear_distribution
  - pointer_to_binary_function
  - pointer_to_unary_function
  - pointer_traits
  - poisson_distribution
  - policy
  - poll
  - poll_with_backoff
  - pop_heap
  - port
  - port_obj
  - predicate
  - prev
  - prev_permutation
  - priority_tag
  - proc
  - processor
  - processor_info
  - processor_set
  - projected
  - promote
  - propagate_const
  - pthread
  - push_heap
  - pwd
  - qos
  - queue
  - quota
  - random
  - random_device
  - randomize_range
  - range_adaptor
  - ranges
  - ranges_adjacent_find
  - ranges_all_of
  - ranges_any_of
  - ranges_binary_search
  - ranges_clamp
  - ranges_construct_at
  - ranges_copy
  - ranges_copy_backward
  - ranges_copy_if
  - ranges_copy_n
  - ranges_count
  - ranges_count_if
  - ranges_equal
  - ranges_equal_range
  - ranges_fill
  - ranges_fill_n
  - ranges_find
  - ranges_find_end
  - ranges_find_first_of
  - ranges_find_if
  - ranges_find_if_not
  - ranges_for_each
  - ranges_for_each_n
  - ranges_generate
  - ranges_generate_n
  - ranges_includes
  - ranges_inplace_merge
  - ranges_is_heap
  - ranges_is_heap_until
  - ranges_is_partitioned
  - ranges_is_permutation
  - ranges_is_sorted
  - ranges_is_sorted_until
  - ranges_iterator_concept
  - ranges_lexicographical_compare
  - ranges_lower_bound
  - ranges_make_heap
  - ranges_max
  - ranges_max_element
  - ranges_merge
  - ranges_min
  - ranges_min_element
  - ranges_minmax
  - ranges_minmax_element
  - ranges_mismatch
  - ranges_move
  - ranges_move_backward
  - ranges_next_permutation
  - ranges_none_of
  - ranges_nth_element
  - ranges_operations
  - ranges_partial_sort
  - ranges_partial_sort_copy
  - ranges_partition
  - ranges_partition_copy
  - ranges_partition_point
  - ranges_pop_heap
  - ranges_prev_permutation
  - ranges_push_heap
  - ranges_remove
  - ranges_remove_copy
  - ranges_remove_copy_if
  - ranges_remove_if
  - ranges_replace
  - ranges_replace_copy
  - ranges_replace_copy_if
  - ranges_replace_if
  - ranges_reverse
  - ranges_reverse_copy
  - ranges_rotate
  - ranges_rotate_copy
  - ranges_sample
  - ranges_search
  - ranges_search_n
  - ranges_set_difference
  - ranges_set_intersection
  - ranges_set_symmetric_difference
  - ranges_set_union
  - ranges_shuffle
  - ranges_sort
  - ranges_sort_heap
  - ranges_stable_partition
  - ranges_stable_sort
  - ranges_swap_ranges
  - ranges_transform
  - ranges_uninitialized_algorithms
  - ranges_unique
  - ranges_unique_copy
  - ranges_upper_bound
  - rank
  - ranlib
  - ranlux
  - ratio
  - raw_storage_iterator
  - rbegin
  - rbtree
  - readable_traits
  - readpassphrase
  - recursive_directory_iterator
  - reduce
  - ref_view
  - reference_wrapper
  - regex
  - regular
  - rel_ops
  - relation
  - relaxng
  - reloc
  - remove
  - remove_all_extents
  - remove_const
  - remove_copy
  - remove_copy_if
  - remove_cv
  - remove_cvref
  - remove_extent
  - remove_if
  - remove_pointer
  - remove_reference
  - remove_volatile
  - rend
  - replace
  - replace_copy
  - replace_copy_if
  - replace_if
  - resource
  - reverse
  - reverse_access
  - reverse_copy
  - reverse_iterator
  - reverse_view
  - rotate
  - rotate_copy
  - rpc
  - runetype
  - same_as
  - sample
  - sched
  - schemasInternals
  - schematron
  - scope6_var
  - scoped_allocator
  - search
  - search_n
  - secure
  - seed_seq
  - select
  - select_proto
  - sem
  - semaphore
  - semiregular
  - set
  - set_difference
  - set_intersection
  - set_symmetric_difference
  - set_union
  - setjmp
  - setjmp_h
  - shared_mutex
  - shared_ptr
  - shift_left
  - shift_right
  - shm
  - shuffle
  - shuffle_order_engine
  - sift_down
  - signal
  - signpost
  - simd
  - single_view
  - size
  - socket
  - socketvar
  - sockio
  - sort
  - sort_heap
  - sortable
  - space_info
  - span
  - span_fwd
  - spawn
  - spis
  - sstream
  - stab
  - stable_partition
  - stable_sort
  - stack
  - stat
  - statvfs
  - std
  - std_config
  - std_types
  - stdarg
  - stdatomic
  - stdatomic_h
  - stdbool
  - stdbool_h
  - stddef
  - stddef_h
  - stdexcept
  - stdint
  - stdint_h
  - stdio
  - stdio_h
  - stdlib
  - stdlib_h
  - steady_clock
  - streambuf
  - string
  - string_h
  - string_view
  - string_view_fwd
  - strings
  - strong_order
  - strstream
  - student_t_distribution
  - subrange
  - subtract_with_carry_engine
  - swap
  - swap_allocator
  - swap_ranges
  - swappable
  - sync
  - sync_policy
  - synth_three_way
  - sys
  - syscall
  - sysctl
  - sysexits
  - syslimits
  - syslog
  - system_clock
  - system_error
  - tables
  - take_view
  - tar
  - task
  - task_info
  - task_inspect
  - task_policy
  - task_special_ports
  - tcp
  - tcp_timer
  - tcp_var
  - temporary_buffer
  - termios
  - tgmath
  - tgmath_h
  - thread
  - thread_act
  - thread_info
  - thread_policy
  - thread_special_ports
  - thread_state
  - thread_status
  - thread_switch
  - threads
  - three_way_comparable
  - time
  - time_point
  - time_value
  - timeb
  - timed_backoff_policy
  - times
  - to_chars_base_10
  - to_chars_result
  - to_underlying
  - totally_ordered
  - trace
  - trace_base
  - transaction
  - transform
  - transform_exclusive_scan
  - transform_inclusive_scan
  - transform_reduce
  - transform_view
  - traps
  - tree
  - trivial_awaitables
  - ttycom
  - ttydefaults
  - tuple
  - type_identity
  - type_list
  - type_traits
  - typeindex
  - typeinfo
  - types
  - u8path
  - uchar_h
  - ucontext
  - ucred
  - udp
  - uio
  - ulimit
  - un
  - unary_function
  - unary_negate
  - underlying_type
  - unicode
  - uniform_int_distribution
  - uniform_random_bit_generator
  - uniform_random_bit_generator_adaptor
  - uniform_real_distribution
  - uninitialized_algorithms
  - unique
  - unique_copy
  - unique_ptr
  - unistd
  - unordered_map
  - unordered_set
  - unreachable
  - unreachable_sentinel
  - unwind
  - unwrap_iter
  - unwrap_range
  - unwrap_ref
  - upper_bound
  - uri
  - uses_allocator
  - util
  - utility
  - utime
  - utmpx
  - utsname
  - uuid
  - valarray
  - valid
  - variant
  - vector
  - version
  - view_interface
  - views
  - vm
  - vm_attributes
  - vm_behavior
  - vm_inherit
  - vm_map
  - vm_page_size
  - vm_param
  - vm_prot
  - vm_purgable
  - vm_region
  - vm_statistics
  - vm_sync
  - vm_task
  - vm_types
  - void_t
  - voidify
  - wait
  - wchar
  - wchar_h
  - wctype
  - wctype_h
  - weak_order
  - weak_result_type
  - weekday
  - weibull_distribution
  - wordexp
  - workgroup
  - wrap_iter
  - xattr
  - xattr_flags
  - xinclude
  - xlink
  - xlocale
  - xmlIO
  - xmlautomata
  - xmlerror
  - xmlexports
  - xmlmemory
  - xmlmodule
  - xmlreader
  - xmlregexp
  - xmlsave
  - xmlschemas
  - xmlschemastypes
  - xmlstring
  - xmlunicode
  - xmlversion
  - xmlwriter
  - xpath
  - xpathInternals
  - xpointer
  - year
  - year_month
  - year_month_day
  - year_month_weekday
  - zip_view
  - zlib
