# slather config file

coverage_service: cobertura_xml
xcodeproj: 'Example/ByteView.xcodeproj'
scheme: 'ByteView-Example'
build_directory: './DerivedData'
source_directory: './ByteView/'
output_directory: './reports'
ignore:
    - 'Example/**/*'
    - './ByteView/Classes/Debug/*'
    - '**/*ViewController*.swift'
    - '**/*ContainerController.swift'
    - '**/NavigationController.swift'
    - '**/ActionSheetController.swift'
    - '**/*View.swift'
    - '**/*Cell*.swift'
    - '**/FeedbackBar.swift'
    - '**/FeedBackSegment.swift'
    - './ByteView/Classes/Classes/Utility/**/*'
    - '**/*Keyboard*.swift'
    - '**/BundleI18n.swift'
    - '**/BundleConfig.swift'
    - '**/SceneManipulator*.swift'
    - '**/*i18n*'
    - '**/auto_resources/**/*'
