# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'git@code.byted.org:ee/pods_specs.git'
source 'git@code.byted.org:iOS_Library/lark_source_repo.git'
source 'git@code.byted.org:iOS_Library/publicthird_source_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_source_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_source_repo.git'

def pods
  #pod 'LarkLocalizations', :path => '../../../../Infra/Libs/LarkLocalizations'
  pod 'RustPB', '7.3.0-g6d04a0331009-1694169776.199187375-alpha'
end

target 'LarkModelDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LookinServer'
  #pod 'LarkModel', :subspecs => ['Base'], :path => '../'
  pods
end

target 'UnitTests' do
  use_frameworks!
  pod 'LarkModel', :subspecs => ['Base'], :path => '../'
  pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
