//
//  OpenPluginStartDeviceCredentialModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26127
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginStartDeviceCredentialRequest
final class OpenPluginStartDeviceCredentialRequest: OpenAPIBaseParams {
    
    /// description: 验证描述，即识别过程中显示在界面上的对话框提示内容
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "authContent")
    public var authContent: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_authContent]
    }
}
