# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

 lane :build_verify do |options|
    merge_policy = lambda do |key, o, n|
      if o.is_a? Hash and n.is_a? Hash
        o.merge!(n, &merge_policy)
      elsif Fastlane::Actions::XcodebuildAction::ARGS_MAP.include? key and n == 'false'
        nil # remove action
      else
        n
      end
    end

    options = {
      workspace: 'Passport.xcworkspace',
      scheme: 'Passport',
      configuration: 'Debug',
      clean: true,
      build: true,
      raw_buildlog: false, # show output from script like swiftlint
      destination: 'generic/platform=iOS Simulator',
      build_settings: {
        'CODE_SIGNING_REQUIRED' => 'NO',
        'VALID_ARCHS' => 'x86_64'
      },
      derivedDataPath: ENV['DERIVED_DATA_PATH'],
      result_bundle_path: ENV['RESULT_DATA_PATH']
    }.merge!(options, &merge_policy)

    if log_path = ENV["GYM_BUILDLOG_PATH"]
      ENV["XCODE_BUILDLOG_PATH"] = log_path
    end

    xcodebuild options
  end

end
