//
//  OpenPluginFileSystemManagerAppendFileModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 22636
//  

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginFileSystemManagerAppendFileRequest
final class OpenPluginFileSystemManagerAppendFileRequest: OpenAPIBaseParams {
    
    /// description: 要追加内容的文件路径 (本地路径)
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "filePath")
    public var filePath: String
    
    /// description: 要追加的文本
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "data")
    public var data: Any
    
    /// description: 指定写入文件的字符编码，默认值为utf8（默认值仅在data为string类型时生效）
    @OpenAPIRequiredParam(
            userOptionWithJsonKey: "encoding",
            defaultValue: "utf8")
    public var encoding: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_filePath, _data, _encoding, ];
    }
}

// MARK: - OpenPluginFileSystemManagerAppendFileResponse
final class OpenPluginFileSystemManagerAppendFileResponse: OpenAPIBaseResult {
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        let result: [AnyHashable : Any] = [:]
        return result
    }
}
