//
//  OpenPluginAddAppToTabModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 29043
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginAddAppToTabRequest
final class OpenPluginAddAppToTabRequest: OpenAPIBaseParams {
    
    /// description: 应用id，唯一
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "appID")
    var appID: String
    
    /// description: 多语言，应用名称，结构:{'zh-cn': 'xxx'}
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "title")
    var title: [AnyHashable: Any]
    
    /// description: 应用类型，miniprogram/web-app
    /// appType = 2 开放平台：小程序
    /// appType = 3 开放平台：网页应用
    @OpenAPIOptionalParam(
            jsonKey: "appType")
    var appType: AppTypeEnum?
    
    /// description: 应用logo url地址
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "logoUrl")
    var logoUrl: String
    
    /// description: 应用applink，根据applink规则拼接
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "url")
    var url: String
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_appID, _title, _appType, _logoUrl, _url]
    }

    // MARK: AppTypeEnum
    enum AppTypeEnum: Int, OpenAPIEnum {

        /// description: 开放平台：小程序
        case mINI_APP = 2

        /// description: 开放平台：网页应用
        case wEB_APP = 3

    }
}
