//
//  OpenPluginRemoveAppFromTabModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 29045
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginRemoveAppFromTabRequest
final class OpenPluginRemoveAppFromTabRequest: OpenAPIBaseParams {
    
    /// description: 应用id，唯一
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "appID")
    var appID: String
    
    /// description: 应用类型，miniprogram/web-app
    /// appType = 2 开放平台：小程序
    /// appType = 3 开放平台：网页应用
    @OpenAPIOptionalParam(
            jsonKey: "appType")
    var appType: AppTypeEnum?
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_appID, _appType]
    }

    // MARK: AppTypeEnum
    enum AppTypeEnum: Int, OpenAPIEnum {

        /// description: 开放平台：小程序
        case mINI_APP = 2

        /// description: 开放平台：网页应用
        case wEB_APP = 3

    }
}
