//
//  OpenPluginCheckAppExistInTabModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 29047
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginCheckAppExistInTabRequest
final class OpenPluginCheckAppExistInTabRequest: OpenAPIBaseParams {
    
    /// description: 应用id，唯一
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "appID")
    var appID: String
    
    /// description: 应用类型(移动端必填，PC端可选)
    /// appType = 2 小程序
    /// appType = 3 网页应用
    @OpenAPIOptionalParam(
            jsonKey: "appType")
    var appType: AppTypeEnum?
    
    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_appID, _appType]
    }

    // MARK: AppTypeEnum
    enum AppTypeEnum: Int, OpenAPIEnum {

        /// description: 小程序
        case mINI_APP = 2

        /// description: 网页应用
        case wEB_APP = 3

    }
}

// MARK: - OpenPluginCheckAppExistInTabResponse
final class OpenPluginCheckAppExistInTabResponse: OpenAPIBaseResult {
    
    /// description: true表示该应用在主导航中
    let isAppInTab: Bool
    
    init(isAppInTab: Bool) {
        self.isAppInTab = isAppInTab
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["isAppInTab"] = isAppInTab
        return result
    }
}
