//
//  OpenPluginCheckAppExistInTabAPI.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE on 2023/6/30 06:59:15
//

import Foundation
import LarkOpenAPIModel
import TTMicroApp
import LarkOpenPluginManager
import LarkQuickLaunchInterface
import LarkContainer
import RxSwift
import LarkTab

// MARK: - OpenPluginCheckAppExistInTabAPI
final class OpenPluginCheckAppExistInTabAPI: OpenBasePlugin {
    
    @InjectedUnsafeLazy var quickLaunchService: QuickLaunchService
    
    private let disposeBag = DisposeBag()
    
    func checkAppExistInTab(
        params: OpenPluginCheckAppExistInTabRequest,
        context: OpenAPIContext,
        gadgetContext: GadgetAPIContext,
        callback: @escaping (OpenAPIBaseResponse<OpenPluginCheckAppExistInTabResponse>) -> Void) {
            guard OpenPluginAppTabUtil.checkAppTabAPI(apiName: "checkAppExistInTab", uniqueID:gadgetContext.uniqueID) else {
                let error = OpenAPIError(errno: OpenAPICommonErrno.unable)
                callback(.failure(error: error))
                return
            }
            guard let appTypeNum = params.appType?.rawValue, let appType = CustomBizType(rawValue: appTypeNum) else {
                let error = OpenAPIError(errno: OpenAPICommonErrno.invalidParam(.invalidParam(param: "appType")))
                callback(.failure(error: error))
                return
            }
            quickLaunchService.findInQuickLaunchWindow(appId: params.appID, tabBizType: appType).subscribe(onNext: { response in
                callback(.success(data: OpenPluginCheckAppExistInTabResponse(isAppInTab: response)))
            }, onError: { error in
                context.apiTrace.error("appToTab check failed: \(error)")
                let callbackError = OpenPluginAppTabUtil.processError(error: error)
                callback(.failure(error: callbackError))
            }).disposed(by: self.disposeBag)
    }
    
    required init(resolver: UserResolver) {
        super.init(resolver: resolver)
        registerInstanceAsyncHandlerGadget(for: "checkAppExistInTab", pluginType: Self.self, paramsType: OpenPluginCheckAppExistInTabRequest.self, resultType: OpenPluginCheckAppExistInTabResponse.self) { (this, params, context, gadgetContext, callback) in
            context.apiTrace.info("checkAppExistInTab API call start")
            this.checkAppExistInTab(params: params, context: context, gadgetContext: gadgetContext, callback: callback)
            context.apiTrace.info("checkAppExistInTab API call end")
        }
    }
}
