//
//  OpenPluginMsgCardOpenUrlModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 30653
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginMsgCardOpenUrlRequest
final class OpenPluginMsgCardOpenUrlRequest: OpenAPIBaseParams {

    /// description: elementID
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "elementID")
    var elementID: String

    /// description:
    @OpenAPIOptionalParam(
            jsonKey: "url")
    var url: String?

    /// description: 组件 tag
    @OpenAPIOptionalParam(
            jsonKey: "tag")
    var tag: String?

    override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_elementID, _url, _tag]
    }
}
