//
//  BaseAssembly.swift
//  Lark
//
//  Auto generated by lark-project.
//  See more: https://bytedance.feishu.cn/docx/doxcnDjV99CCJ2qcihUE453Qaqg
//

import Foundation
import LarkAssembler
import AppContainer
import LKLoadable

final class BaseAssembly: LarkAssemblyInterface {
    lazy var subAssemblies = lazySubAssemblies()

    func getSubAssemblies() -> [LarkAssemblyInterface]? {
        return subAssemblies
    }

    private func lazySubAssemblies() -> [LarkAssemblyInterface] {
        var assemblies = allAssemblies()

        if OPUnitTestHelper.isUnitTest() {
            assemblies.removeAll { $0 is PrivacyAlertAssembly }
        }
        var set = Set<ObjectIdentifier>()
        for ass in assemblies {
            recordAllSubAssemblies(in: &set, for: ass)
        }
        return assemblies.filter { !set.contains(ObjectIdentifier(type(of: $0))) }
    }

    private func recordAllSubAssemblies(in set: inout Set<ObjectIdentifier>, for ass: LarkAssemblyInterface) {
        let subs = ass.getSubAssemblies() ?? []
        guard !subs.isEmpty else { return }
        subs.lazy.forEach {
            set.insert(ObjectIdentifier(type(of: $0)))
            $0.getSubAssemblies()?.forEach { recordAllSubAssemblies(in: &set, for: $0) }
        }
    }
}

import LarkAccount
import AnimatedTabBar
import LarkAppLinkSDK
import LarkBGTaskScheduler
import LarkBadgeAssembly
import Blockit
import LarkCacheAssembly
import LarkCloudScheme
import LarkAppConfig
import LarkDebug
import LarkLaunchGuide
import ECOInfra
import EcosystemWeb
import LarkEmotion
import LarkSecurityCompliance
import LarkAccountAssembly
import LarkBaseService
import LarkCleanAssembly
import LarkCoreLocation
import LarkDocsIcon
import LarkDynamicResource
import LarkEMM
import LarkFontAssembly
import LarkGuide
import LarkAIInfra
import LarkMonitor
import LarkNavigationAssembly
import LarkPushTokenUploader
import LarkSceneManagerAssembly
import LarkShareContainer
import LarkSnsShare
import LarkStorageAssembly
import LarkWorkplace
import LarkLeanMode
import LarkMicroApp
import LarkNavigation
import OPBlock
import LarkPrivacyAlert
import LarkRustClientAssembly
import SecSDK
import LarkSecurityAudit
import LarkSecurityComplianceInfra
import LarkSetting
import LarkSettingsBundle
import SuiteAppConfig
import LarkSuspendable
import LarkTabMicroApp
import TangramService
import LarkVideoDirector
import LarkWaterMark
import WorkplaceMod
import ZeroTrust

private func allAssemblies() -> [LarkAssemblyInterface] {
    return [
        AccountAssembly(),
        AnimatedTabBarAssembly(),
        AppLinkAssembly(),
        BGTaskSchedulerAssembly(),
        BadgeAssembly(),
        BlockitAssembly(),
        CacheManagerAssembly(),
        CloudSchemeAssembly(),
        ConfigAssembly(),
        DebugAssembly(),
        DefaultLaunchGuideDependencyAssembly(),
        ECOCookieAssembly(),
        ECONetworkAssembly(),
        EcosystemWebAssemblyV2(),
        EmotionAssembly(),
        FileCryptoAssembly(),
        LarkAccountAssembly(),
        LarkBaseServiceAssembly(),
        LarkCleanAssembly(),
        LarkCoreLocationAssembly(),
        LarkDocsIconAssembly(),
        LarkDynamicResourceAssembly(),
        LarkEMMAssembly(),
        LarkFontAssembly(),
        LarkGuideAssembly(),
        LarkInlineAIAssemble(),
        LarkMonitorAssembly(),
        LarkNavigationAssembly(),
        LarkPushTokenUploaderAssembly(),
        LarkSceneManagerAssembly(),
        LarkSecurityComplianceAssembly(),
        LarkShareContainerAssembly(),
        LarkSnsShareAssembly(),
        LarkSnsShareBaseAssembly(),
        LarkStorageAssembly(),
        LarkWorkplaceAssembly(),
        LaunchGuideAssembly(),
        LeanModeAssembly(),
        MicroAppAssembly(),
        NavigationAssembly(),
        OPBlockAssembly(),
        PrivacyAlertAssembly(),
        RustClientAssembly(),
        SecGuardAssembly(),
        SecurityAuditAssembly(),
        SecurityComplianceInfraAssembly(),
        SecurityPolicyAssembly(),
        SettingAssembly(),
        SettingsBundleAssembly(),
        SuiteAppConfigAssembly(),
        SuspendAssembly(),
        TabMicroAppAssembly(),
        TangramAssembly(),
        VideoDirectorAssembly(),
        WaterMarkAssembly(),
        WorkplaceAssembly(),
        ZeroTrustAssembly()
    ]
}
