# relative to ios-client repo root
# 目录需要以/结尾
excludePath:
- '**/*Debug/'
- '**/*[Tt]est/'
- '**/[Tt]ests/'
- '**/Example/'
- '**/app/{app,test}/src/'
- '**/*{Demo,Demos}/'
- bin/
- Lark-cal/
- Modules/Security/SCDemoImp/
- Modules/Foundation/Libs/EENavigator/
- Modules/Infra/Libs/Swinject/
- Modules/Infra/Libs/LarkContainer/
- Modules/Infra/Bizs/BootManager/

globalType:
- GlobalRustService
- AppConfiguration

# Passport @jinjian.au
# https://bytedance.feishu.cn/wiki/YKf1wpH2Uipr1tk2DAdcFzHzniz?table=tbl8W3xvsayO1N0m&view=vewycUWXph
- V3APIHelper
- DeviceService
- InternalDeviceServiceProtocol
- PassportStore
- PassportTokenManager
- HTTPClient
- DynamicDomainService
- Launcher
- AccountService
- V3LoginService
- NewSwitchUserService
- SwitchUserExchangeSessionAPI
- UserManager
- EnvironmentInterface
- KaLoginManager
- KaLoginService
- LogoutService
- AccountServiceUG
- BioAuthService
- LoginAPI
- PassportService
- PassportStateService
- UserSessionService

# OpenPlatform
- ECONetworkDependency
- ECOFoundationDependency
- WebAppMonitorProtocol
- OpenAPIWebSessionUpdate
- OPNetStatusHelper
- LocationAuthorization
