//
//  OpenPluginGetContainerContextModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 27773
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginGetContainerContextResponse
final class OpenPluginGetContainerContextResponse: OpenAPIBaseResult {
    
    /// description: 容器运行业务场景，比如主导航，工作台，独立窗口等
    let mode: String
    
    /// description: 页面跳转来源，比如从IM打开，或者工作台打开
    let fromScene: String
    
    init(mode: String, fromScene: String) {
        self.mode = mode
        self.fromScene = fromScene
        super.init()
    }
    
    override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["mode"] = mode
        result["fromScene"] = fromScene
        return result
    }
}
