//
//  OpenPluginGetLegacyDeviceIDModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 27217
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginGetLegacyDeviceIDResponse
final class OpenPluginGetLegacyDeviceIDResponse: OpenAPIBaseResult {
    
    /// description: 旧设备ID
    public let legacyDeviceID: String?
    
    public init(legacyDeviceID: String?) {
        self.legacyDeviceID = legacyDeviceID
        super.init()
    }
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["legacyDeviceID"] = legacyDeviceID
        return result
    }
}
