//
//  OpenPluginGetInternalFeatureGatingModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 25980
//  

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginGetInternalFeatureGatingRequest
final class OpenPluginGetInternalFeatureGatingRequest: OpenAPIBaseParams {
    
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "fg_name")
    public var fg_name: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_fg_name]
    }
}

// MARK: - OpenPluginGetInternalFeatureGatingResponse
final class OpenPluginGetInternalFeatureGatingResponse: OpenAPIBaseResult {
    
    public let fg_value: Bool
    
    public init(fg_value: Bool) {
        self.fg_value = fg_value
        super.init()
    }
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["fg_value"] = fg_value
        return result
    }
}
