//
//  OpenPluginCompressImageModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 23936
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginCompressImageRequest
final class OpenPluginCompressImageRequest: OpenAPIBaseParams {
    
    /// description: 压缩质量，范围 0～100，数值越小，质量越低，压缩率越高（仅对 jpg 有效）
    /// 注意事项：非 jpg 格式，会输出原文件
    @OpenAPIRequiredParam(
            userOptionWithJsonKey: "quality",
            defaultValue: 80)
    public var quality: Int
    
    /// description: 图片路径，可以是相对路径、临时文件路径、存储文件路径
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "src")
    public var src: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_quality, _src, ];
    }
}

// MARK: - OpenPluginCompressImageResponse
final class OpenPluginCompressImageResponse: OpenAPIBaseResult {
    
    /// description: 压缩后的图片路径
    public let tempFilePath: String
    
    public init(tempFilePath: String) {
        self.tempFilePath = tempFilePath
        super.init()
    }
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["tempFilePath"] = tempFilePath
        return result
    }
}
