//
//  OpenPluginOnOpenFileFromCloudDownloadCompleteModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26692
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginOnOpenFileFromCloudDownloadCompleteResponse
final class OpenPluginOnOpenFileFromCloudDownloadCompleteResponse: OpenAPIBaseResult {

    /// description: 预览的文件名
    public let fileName: String

    /// description: 预览的文件 Token
    public let fileToken: String

    /// description: 预览的文件后缀名
    public let fileType: String

    /// description: 预览的文件大小
    public let size: Int

    public let taskID: String

    public init(fileName: String, fileToken: String, fileType: String, size: Int, taskID: String) {
        self.fileName = fileName
        self.fileToken = fileToken
        self.fileType = fileType
        self.size = size
        self.taskID = taskID
        super.init()
    }

    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["fileName"] = fileName
        result["fileToken"] = fileToken
        result["fileType"] = fileType
        result["size"] = size
        result["taskID"] = taskID
        return result
    }
}
