//
//  OpenPluginDownloadFileFromCloudAbortModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26289
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginDownloadFileFromCloudAbortRequest
final class OpenPluginDownloadFileFromCloudAbortRequest: OpenAPIBaseParams {

    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "taskID")
    public var taskID: String

    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_taskID]
    }
}
