//
//  OpenPluginOpenLingoProfileModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26741
//
//  类型声明默认为internal, 如需被外部Module引用, 请在上行添加
//  /** anycode-lint-ignore */
//  public
//  /** anycode-lint-ignore */

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginOpenLingoProfileRequest
final class OpenPluginOpenLingoProfileRequest: OpenAPIBaseParams {
    
    /// description: 词条ID
    @OpenAPIOptionalParam(
            jsonKey: "id")
    public var id: String?
    
    /// description: 词条查询关键词
    @OpenAPIOptionalParam(
            jsonKey: "query")
    public var query: String?
    
    /// description: 业务自定义数据分析数据
    /// 注意事项：至少包含标记来源的card_source字段 ( 如 { "card_source": "test" } )，才能触发数据统计
    @OpenAPIOptionalParam(
            jsonKey: "analysisParams")
    public var analysisParams: [AnyHashable: Any]?
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_id, _query, _analysisParams]
    }
}
