//
//  OpenPluginOnUploadFileToCloudUpdateModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26291
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginOnUploadFileToCloudUpdateResponse
final class OpenPluginOnUploadFileToCloudUpdateResponse: OpenAPIBaseResult {

    public let taskID: String

    public let progress: Int

    public init(taskID: String, progress: Int) {
        self.taskID = taskID
        self.progress = progress
        super.init()
    }

    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["taskID"] = taskID
        result["progress"] = progress
        return result
    }
}
