//
//  OpenPluginUploadFileToCloudAbortModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26288
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginUploadFileToCloudAbortRequest
final class OpenPluginUploadFileToCloudAbortRequest: OpenAPIBaseParams {

    /// description:
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "taskID")
    public var taskID: String

    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_taskID]
    }
}
