#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

ROOTDIR=$(pwd)


# echo "II. Check Messenger Pod versoin"
# ruby ./hooks/checkMessengerVersion.rb
# if [ $? -eq 1 ]; then
#     exit 1
# fi

echo "2. generate config"
ruby ./scripts/bits_component_config_generator.rb
python3 ./scripts/mbox_config_generator.py
python3 ./scripts/recommend_components_generator.py
