// DO NOT EDIT.
//
// Generated by the Swift generator for OPMonitorCode.
// Source: https://bytedance.feishu.cn/sheets/shtcnCCboz4CUWBUtZkdmZV0PLb?sheet=ve29xQ&table=tblhdeAY8y&view=vewDYgteNU
// Date:   2021/01/07 16:26
//
// For information on using the generated types, please see the documentation:
//  https://bytedance.feishu.cn/sheets/shtcnCCboz4CUWBUtZkdmZV0PLb

import Foundation

// Copy from GDMonitorCode
public final class GDAPIMonitorCode: OPMonitorCode {

    /// 图片url不合法
    public static let illegal_image_url = GDAPIMonitorCode(code: 10016, level: OPMonitorLevelError, message: "illegal_image_url")

    /// 图片加载失败
    public static let image_load_failed = GDAPIMonitorCode(code: 10044, level: OPMonitorLevelWarn, message: "image_load_failed")

    private init(code: Int, level: OPMonitorLevel, message: String) {
        super.init(domain: GDAPIMonitorCode.domain, code: code, level: level, message: message)
    }

    public static let domain = "client.open_platform.gadget"
}
