// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientPassportMonitorSwitchUserCode: OPMonitorCodeBase {

    /** 进入切换租户流程，switch_reason */
    public static let switch_user_start = EPMClientPassportMonitorSwitchUserCode(code: 10001, level: OPMonitorLevelNormal, message: "switch_user_start")

    /** 切换租户流程完成，返回成功 */
    public static let switch_user_end_succ = EPMClientPassportMonitorSwitchUserCode(code: 10002, level: OPMonitorLevelNormal, message: "switch_user_end_succ")

    /** 切换租户流程完成，返回失败，fail_reason */
    public static let switch_user_end_fail = EPMClientPassportMonitorSwitchUserCode(code: 10003, level: OPMonitorLevelError, message: "switch_user_end_fail")

    /** 切换租户请求开始，request_type */
    public static let switch_identity_request_start = EPMClientPassportMonitorSwitchUserCode(code: 10004, level: OPMonitorLevelNormal, message: "switch_identity_request_start")

    /** 切换租户请求成功，next_step，request_type */
    public static let switch_identity_request_succ = EPMClientPassportMonitorSwitchUserCode(code: 10005, level: OPMonitorLevelNormal, message: "switch_identity_request_succ")

    /** 切换enter_app流程对端用户入口 */
    public static let enter_app_cross_user_entry = EPMClientPassportMonitorSwitchUserCode(code: 10006, level: OPMonitorLevelNormal, message: "enter_app_cross_user_entry")

    /** 切换enter_app流程对端用户环境准备成功 */
    public static let cross_env_and_device_id_succ = EPMClientPassportMonitorSwitchUserCode(code: 10007, level: OPMonitorLevelNormal, message: "cross_env_and_device_id_succ")

    /** 切换租户处理用户下线开始 */
    public static let make_offline_process_start = EPMClientPassportMonitorSwitchUserCode(code: 10008, level: OPMonitorLevelNormal, message: "make_offline_process_start")

    /** 切换租户处理用户下线成功 */
    public static let make_offline_process_end = EPMClientPassportMonitorSwitchUserCode(code: 10009, level: OPMonitorLevelNormal, message: "make_offline_process_end")

    /** 切换租户处理用户上线开始 */
    public static let make_online_process_start = EPMClientPassportMonitorSwitchUserCode(code: 10010, level: OPMonitorLevelNormal, message: "make_online_process_start")

    /** 切换租户处理用户上线成功 */
    public static let make_online_process_end = EPMClientPassportMonitorSwitchUserCode(code: 10011, level: OPMonitorLevelNormal, message: "make_online_process_end")

    /** 切换到下一个有效session的租户，入口 */
    public static let switch_to_invalid_session_user_start = EPMClientPassportMonitorSwitchUserCode(code: 10012, level: OPMonitorLevelNormal, message: "switch_to_invalid_session_user_start")

    /** 检查用户session状态接口开始请求 */
    public static let check_status_request_start = EPMClientPassportMonitorSwitchUserCode(code: 10013, level: OPMonitorLevelNormal, message: "check_status_request_start")

    /** 检查用户session状态接口返回成功 */
    public static let check_status_request_succ = EPMClientPassportMonitorSwitchUserCode(code: 10014, level: OPMonitorLevelNormal, message: "check_status_request_succ")

    /** 切换到下一个有效session的租户流程调用主动切换 */
    public static let switch_to_invalid_session_user_goto_switch_user = EPMClientPassportMonitorSwitchUserCode(code: 10015, level: OPMonitorLevelNormal, message: "switch_to_invalid_session_user_goto_switch_user")

    /** 切换租户时目标租户为空，租户userId的userId为空，switch_reason */
    public static let switch_target_null_and_user_id_empty = EPMClientPassportMonitorSwitchUserCode(code: 10016, level: OPMonitorLevelNormal, message: "switch_target_null_and_user_id_empty")

    /** 切换租户时目标租户为空，利用targetUserId请求user_list获取租户信息，switch_reason */
    public static let switch_target_null_and_request_tenant_beg = EPMClientPassportMonitorSwitchUserCode(code: 10017, level: OPMonitorLevelNormal, message: "switch_target_null_and_request_tenant_beg")

    /** 切换租户时目标租户为空，重新获取租户信息成功，继续切换 */
    public static let switch_target_null_and_request_tenant_succ_next = EPMClientPassportMonitorSwitchUserCode(code: 10018, level: OPMonitorLevelNormal, message: "switch_target_null_and_request_tenant_succ_next")

    /** 切换租户时目标租户为空，重新获取租户信息失败，切换失败 */
    public static let switch_target_null_and_request_tenant_fail_end = EPMClientPassportMonitorSwitchUserCode(code: 10019, level: OPMonitorLevelError, message: "switch_target_null_and_request_tenant_fail_end")

    /** 切换租户处理用户下线失败 */
    public static let make_offline_process_end_fail = EPMClientPassportMonitorSwitchUserCode(code: 10020, level: OPMonitorLevelError, message: "make_offline_process_end_fail")

    /** 切换租户处理用户上线失败 */
    public static let make_online_process_end_fail = EPMClientPassportMonitorSwitchUserCode(code: 10021, level: OPMonitorLevelError, message: "make_online_process_end_fail")

    /** 切换enter_app流程对端用户环境准备失败 */
    public static let cross_env_and_device_id_fail = EPMClientPassportMonitorSwitchUserCode(code: 10022, level: OPMonitorLevelError, message: "cross_env_and_device_id_fail")

    /** 调用rust获取指定env接口失败 */
    public static let rust_fetch_applog_domain_fail = EPMClientPassportMonitorSwitchUserCode(code: 10023, level: OPMonitorLevelError, message: "rust_fetch_applog_domain_fail")

    /** 获取指定unit的did失败 */
    public static let fetch_did_by_unit_fail = EPMClientPassportMonitorSwitchUserCode(code: 10024, level: OPMonitorLevelError, message: "fetch_did_by_unit_fail")

    /** 调用rust set_env失败 */
    public static let rust_set_env_fail = EPMClientPassportMonitorSwitchUserCode(code: 10025, level: OPMonitorLevelError, message: "rust_set_env_fail")

    /** 调用rust 更新设备deviceId失败 */
    public static let rust_set_deviceinfo_fail = EPMClientPassportMonitorSwitchUserCode(code: 10026, level: OPMonitorLevelError, message: "rust_set_deviceinfo_fail")

    /** 切换租户流程开始回滚操作 */
    public static let switch_user_rollback_start = EPMClientPassportMonitorSwitchUserCode(code: 10027, level: OPMonitorLevelNormal, message: "switch_user_rollback_start")

    /** 切换租户流程开始回滚操作失败 */
    public static let switch_user_rollback_fail = EPMClientPassportMonitorSwitchUserCode(code: 10028, level: OPMonitorLevelError, message: "switch_user_rollback_fail")

    /** 切换租户流程开始回滚操作成功 */
    public static let switch_user_rollback_succ = EPMClientPassportMonitorSwitchUserCode(code: 10029, level: OPMonitorLevelNormal, message: "switch_user_rollback_succ")

    /** 切换租户回滚失败后重试切换 */
    public static let switch_user_rollback_fail_retry_switch = EPMClientPassportMonitorSwitchUserCode(code: 10030, level: OPMonitorLevelNormal, message: "switch_user_rollback_fail_retry_switch")

    /** 切换租户回滚失败后重试失败登出全部用户 */
    public static let switch_user_rollback_error_logout_all = EPMClientPassportMonitorSwitchUserCode(code: 10031, level: OPMonitorLevelError, message: "switch_user_rollback_error_logout_all")

    /** 切换租户请求失败 */
    public static let switch_identity_request_fail = EPMClientPassportMonitorSwitchUserCode(code: 10032, level: OPMonitorLevelError, message: "switch_identity_request_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientPassportMonitorSwitchUserCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.passport.monitor.switch_user"
}