// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformInAppNotificationCode: OPMonitorCodeBase {

    /** 应用内的「管理员通知消息」页面的展示 */
    public static let openplatform_in_app_notification_view = EPMClientOpenPlatformInAppNotificationCode(code: 10000, level: OPMonitorLevelNormal, message: "openplatform_in_app_notification_view")

    /** 应用内的「管理员通知消息」页面的点击行为 */
    public static let openplatform_in_app_notification_click = EPMClientOpenPlatformInAppNotificationCode(code: 10001, level: OPMonitorLevelNormal, message: "openplatform_in_app_notification_click")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformInAppNotificationCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.in_app_notification"
}