// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformCommonPackageCode: OPMonitorCodeBase {

    /** pkg下载不合法的参数 */
    public static let pkg_download_invalid_params = EPMClientOpenPlatformCommonPackageCode(code: 10000, level: OPMonitorLevelError, message: "pkg_download_invalid_params")

    /** pkg下载成功 */
    public static let pkg_download_success = EPMClientOpenPlatformCommonPackageCode(code: 10001, level: OPMonitorLevelNormal, message: "pkg_download_success")

    /** pkg下载失败 */
    public static let pkg_download_failed = EPMClientOpenPlatformCommonPackageCode(code: 10002, level: OPMonitorLevelError, message: "pkg_download_failed")

    /** pkg下载取消 */
    public static let pkg_download_canceled = EPMClientOpenPlatformCommonPackageCode(code: 10003, level: OPMonitorLevelWarn, message: "pkg_download_canceled")

    /** 无pkg下载URL */
    public static let pkg_download_no_url = EPMClientOpenPlatformCommonPackageCode(code: 10004, level: OPMonitorLevelError, message: "pkg_download_no_url")

    /** pkgmd5检验失败 */
    public static let pkg_download_md5_verified_failed = EPMClientOpenPlatformCommonPackageCode(code: 10005, level: OPMonitorLevelError, message: "pkg_download_md5_verified_failed")

    /** 删除下载文件失败(包括下载完成文件和下载中的文件) */
    public static let pkg_delete_file_failed = EPMClientOpenPlatformCommonPackageCode(code: 10006, level: OPMonitorLevelError, message: "pkg_delete_file_failed")

    /** 下载过程中发生写入数据异常 */
    public static let pkg_write_file_failed = EPMClientOpenPlatformCommonPackageCode(code: 10007, level: OPMonitorLevelError, message: "pkg_write_file_failed")

    /** pkg安装不合法的参数 */
    public static let pkg_install_invalid_params = EPMClientOpenPlatformCommonPackageCode(code: 10010, level: OPMonitorLevelError, message: "pkg_install_invalid_params")

    /** pkg描述标记校验失败 */
    public static let pkg_mask_verified_failed = EPMClientOpenPlatformCommonPackageCode(code: 10011, level: OPMonitorLevelError, message: "pkg_mask_verified_failed")

    /** pkg安装成功 */
    public static let pkg_install_success = EPMClientOpenPlatformCommonPackageCode(code: 10012, level: OPMonitorLevelNormal, message: "pkg_install_success")

    /** 暂无注释... */
    public static let pkg_install_failed = EPMClientOpenPlatformCommonPackageCode(code: 10013, level: OPMonitorLevelError, message: "pkg_install_failed")

    /** 找不到Pkg内的指定文件(默认事件) */
    public static let pkg_file_not_found = EPMClientOpenPlatformCommonPackageCode(code: 10014, level: OPMonitorLevelError, message: "pkg_file_not_found")

    /** 加载Pkg数据出错（默认事件） */
    public static let pkg_read_data_failed = EPMClientOpenPlatformCommonPackageCode(code: 10015, level: OPMonitorLevelError, message: "pkg_read_data_failed")

    /** 加载Pkg数据超时(非请求超时, 而是api调用耗时过长)（默认事件） */
    public static let pkg_read_timeout = EPMClientOpenPlatformCommonPackageCode(code: 10016, level: OPMonitorLevelError, message: "pkg_read_timeout")

    /** 创建pkg相关目录或文件失败 */
    public static let pkg_create_file_failed = EPMClientOpenPlatformCommonPackageCode(code: 10017, level: OPMonitorLevelError, message: "pkg_create_file_failed")

    /** pkg版本太低 */
    public static let pkg_version_too_old = EPMClientOpenPlatformCommonPackageCode(code: 10018, level: OPMonitorLevelError, message: "pkg_version_too_old")

    /** 安装包不存在（包括下载包和安装包） */
    public static let pkg_not_found = EPMClientOpenPlatformCommonPackageCode(code: 10019, level: OPMonitorLevelError, message: "pkg_not_found")

    /** 分包预加载开始 */
    public static let mp_preload_sub_package_start = EPMClientOpenPlatformCommonPackageCode(code: 10025, level: OPMonitorLevelNormal, message: "mp_preload_sub_package_start")

    /** 分包预加载结束 */
    public static let mp_preload_sub_package_result = EPMClientOpenPlatformCommonPackageCode(code: 10026, level: OPMonitorLevelNormal, message: "mp_preload_sub_package_result")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformCommonPackageCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.common.package"
}