// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformCommonPerformanceCode: OPMonitorCodeBase {

    /** 检测到有对象内存泄漏发生 */
    public static let op_object_leaked = EPMClientOpenPlatformCommonPerformanceCode(code: 10001, level: OPMonitorLevelWarn, message: "op_object_leaked")

    /** 检测到对象实例数量超出限制 */
    public static let op_object_overcount = EPMClientOpenPlatformCommonPerformanceCode(code: 10002, level: OPMonitorLevelWarn, message: "op_object_overcount")

    /** 检测到指定时期内内存波动过大 */
    public static let op_memory_wave = EPMClientOpenPlatformCommonPerformanceCode(code: 10003, level: OPMonitorLevelWarn, message: "op_memory_wave")

    /** 当前内存占用过多，即将触发系统OOM */
    public static let op_memory_kill = EPMClientOpenPlatformCommonPerformanceCode(code: 10006, level: OPMonitorLevelWarn, message: "op_memory_kill")

    /** 当前内存占用过多，即将触发内存警告 */
    public static let op_memory_warning = EPMClientOpenPlatformCommonPerformanceCode(code: 10007, level: OPMonitorLevelWarn, message: "op_memory_warning")

    /** 触发小程序内存回收 */
    public static let trigger_gadget_memory_optimize = EPMClientOpenPlatformCommonPerformanceCode(code: 10008, level: OPMonitorLevelWarn, message: "trigger_gadget_memory_optimize")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformCommonPerformanceCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.common.performance"
}