// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformApiLocationCode: OPMonitorCodeBase {

    /** 开始持续定位 */
    public static let start_location_update = EPMClientOpenPlatformApiLocationCode(code: 10000, level: OPMonitorLevelNormal, message: "start_location_update")

    /** 停止持续定位 */
    public static let stop_location_update = EPMClientOpenPlatformApiLocationCode(code: 10001, level: OPMonitorLevelNormal, message: "stop_location_update")

    /** getLocation 开始 plugin 处理 */
    public static let plugin_start_process_location = EPMClientOpenPlatformApiLocationCode(code: 10002, level: OPMonitorLevelNormal, message: "plugin_start_process_location")

    /** 统计使用 window.h5sdk.device.geolocation.get 的使用量 */
    public static let old_once_location_sum = EPMClientOpenPlatformApiLocationCode(code: 10003, level: OPMonitorLevelNormal, message: "old_once_location_sum")

    /** 统计使用 window.h5sdk.device.geolocation.start 的使用量 */
    public static let old_start_location_sum = EPMClientOpenPlatformApiLocationCode(code: 10004, level: OPMonitorLevelNormal, message: "old_start_location_sum")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformApiLocationCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.api.location"
}