// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformBlockitLynxCode: OPMonitorCodeBase {

    /** Block收到Lynx的报错 */
    public static let receive_lynx_error = EPMClientOpenPlatformBlockitLynxCode(code: 10000, level: OPMonitorLevelError, message: "receive_lynx_error")

    /** Block收到Lynx的onRuntimeReady */
    public static let lynx_runtime_ready = EPMClientOpenPlatformBlockitLynxCode(code: 10001, level: OPMonitorLevelNormal, message: "lynx_runtime_ready")

    /** Block收到Lynx的onFirstScreen */
    public static let lynx_first_screen = EPMClientOpenPlatformBlockitLynxCode(code: 10002, level: OPMonitorLevelNormal, message: "lynx_first_screen")

    /** Block收到Lynx的onReportComponentInfo */
    public static let lynx_report_component = EPMClientOpenPlatformBlockitLynxCode(code: 10003, level: OPMonitorLevelNormal, message: "lynx_report_component")

    /** Block jssdk存储路径不存在 */
    public static let bundle_jssdk_file_empty = EPMClientOpenPlatformBlockitLynxCode(code: 10004, level: OPMonitorLevelError, message: "bundle_jssdk_file_empty")

    /** 使用Lynx Devtool功能 */
    public static let use_lynx_devtool_result = EPMClientOpenPlatformBlockitLynxCode(code: 10005, level: OPMonitorLevelNormal, message: "use_lynx_devtool_result")

    /** Lynx Devtool插件化加载失败 */
    public static let lynx_devtool_plugin_fail = EPMClientOpenPlatformBlockitLynxCode(code: -10001, level: OPMonitorLevelError, message: "lynx_devtool_plugin_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformBlockitLynxCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.blockit.lynx"
}