// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformAppCenterCacheCode: OPMonitorCodeBase {

    /** 使用缓存加载模板化工作台 */
    public static let get_portal_cache = EPMClientOpenPlatformAppCenterCacheCode(code: 10001, level: OPMonitorLevelNormal, message: "get_portal_cache")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformAppCenterCacheCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.app_center.cache"
}