// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformGadgetDynamicComponentCode: OPMonitorCodeBase {

    /** loadPlugin 开始调用 */
    public static let native_load_plugin_start = EPMClientOpenPlatformGadgetDynamicComponentCode(code: 10000, level: OPMonitorLevelNormal, message: "native_load_plugin_start")

    /** loadPlugin 调用成功 */
    public static let native_load_plugin_success = EPMClientOpenPlatformGadgetDynamicComponentCode(code: 10001, level: OPMonitorLevelNormal, message: "native_load_plugin_success")

    /** loadPlugin 调用失败 */
    public static let native_load_plugin_fail = EPMClientOpenPlatformGadgetDynamicComponentCode(code: 10002, level: OPMonitorLevelError, message: "native_load_plugin_fail")

    /** loadPluginScript 开始调用 */
    public static let native_load_plugin_script_start = EPMClientOpenPlatformGadgetDynamicComponentCode(code: 10003, level: OPMonitorLevelNormal, message: "native_load_plugin_script_start")

    /** loadPluginScript 调用成功 */
    public static let native_load_plugin_script_suceess = EPMClientOpenPlatformGadgetDynamicComponentCode(code: 10004, level: OPMonitorLevelNormal, message: "native_load_plugin_script_suceess")

    /** loadPluginScript 调用失败 */
    public static let native_load_plugin_script_fail = EPMClientOpenPlatformGadgetDynamicComponentCode(code: 10005, level: OPMonitorLevelError, message: "native_load_plugin_script_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformGadgetDynamicComponentCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.gadget.dynamic_component"
}