// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientPassportMonitorLoginCode: OPMonitorCodeBase {

    /** 登录页输入登录凭证后点击下一步 */
    public static let login_page_goto_next_click = EPMClientPassportMonitorLoginCode(code: 10001, level: OPMonitorLevelNormal, message: "login_page_goto_next_click")

    /** 登录凭证接口成功，next_step */
    public static let login_credential_request_succ = EPMClientPassportMonitorLoginCode(code: 10002, level: OPMonitorLevelNormal, message: "login_credential_request_succ")

    /** 验证码下发接口成功 */
    public static let login_auth_code_apply_request_succ = EPMClientPassportMonitorLoginCode(code: 10003, level: OPMonitorLevelNormal, message: "login_auth_code_apply_request_succ")

    /** 验证码验证接口成功，next_step */
    public static let login_auth_code_verify_request_succ = EPMClientPassportMonitorLoginCode(code: 10004, level: OPMonitorLevelNormal, message: "login_auth_code_verify_request_succ")

    /** 密码验证接口成功，next_step */
    public static let login_auth_pwd_verify_request_succ = EPMClientPassportMonitorLoginCode(code: 10005, level: OPMonitorLevelNormal, message: "login_auth_pwd_verify_request_succ")

    /** OTP验证接口成功，next_step */
    public static let login_auth_otp_verify_request_succ = EPMClientPassportMonitorLoginCode(code: 10006, level: OPMonitorLevelNormal, message: "login_auth_otp_verify_request_succ")

    /** 用户列表页进入成功 */
    public static let login_goto_user_list_page_succ = EPMClientPassportMonitorLoginCode(code: 10007, level: OPMonitorLevelNormal, message: "login_goto_user_list_page_succ")

    /** 用户列表点击后进入应用接口请求成功，next_step */
    public static let login_user_list_app_request_succ = EPMClientPassportMonitorLoginCode(code: 10008, level: OPMonitorLevelNormal, message: "login_user_list_app_request_succ")

    /** 一键登录功能开始调用 */
    public static let onekey_login_start = EPMClientPassportMonitorLoginCode(code: 10009, level: OPMonitorLevelNormal, message: "onekey_login_start")

    /** 一键登录sdk取号请求开始 */
    public static let onekey_sdk_get_phone_request_start = EPMClientPassportMonitorLoginCode(code: 10010, level: OPMonitorLevelNormal, message: "onekey_sdk_get_phone_request_start")

    /** 一键登录sdk取号请求成功 */
    public static let onekey_sdk_get_phone_request_succ = EPMClientPassportMonitorLoginCode(code: 10011, level: OPMonitorLevelNormal, message: "onekey_sdk_get_phone_request_succ")

    /** 一键登录页面成功启动 */
    public static let onekey_login_page_entry = EPMClientPassportMonitorLoginCode(code: 10012, level: OPMonitorLevelNormal, message: "onekey_login_page_entry")

    /** 一键登录页面点击一键登录 */
    public static let onekey_login_page_goto_login = EPMClientPassportMonitorLoginCode(code: 10013, level: OPMonitorLevelNormal, message: "onekey_login_page_goto_login")

    /** 一键登录sdk获取token请求开始 */
    public static let onekey_sdk_get_token_request_start = EPMClientPassportMonitorLoginCode(code: 10014, level: OPMonitorLevelNormal, message: "onekey_sdk_get_token_request_start")

    /** 一键登录sdk获取token请求成功 */
    public static let onekey_sdk_get_token_request_succ = EPMClientPassportMonitorLoginCode(code: 10015, level: OPMonitorLevelNormal, message: "onekey_sdk_get_token_request_succ")

    /** 一键登录接口验证开始 */
    public static let onekey_mobile_auth_request_start = EPMClientPassportMonitorLoginCode(code: 10016, level: OPMonitorLevelNormal, message: "onekey_mobile_auth_request_start")

    /** 一键登录接口验证成功 */
    public static let onekey_mobile_auth_request_succ = EPMClientPassportMonitorLoginCode(code: 10017, level: OPMonitorLevelNormal, message: "onekey_mobile_auth_request_succ")

    /** 一键登录流程成功结束，跳转下一步 */
    public static let onekey_login_end_succ = EPMClientPassportMonitorLoginCode(code: 10018, level: OPMonitorLevelNormal, message: "onekey_login_end_succ")

    /** idp-b登录页输入域名后点击下一步 */
    public static let idp_b_company_login_next_click = EPMClientPassportMonitorLoginCode(code: 10019, level: OPMonitorLevelNormal, message: "idp_b_company_login_next_click")

    /** idp-b登录根据域名请求登录地址接口请求成功 */
    public static let idp_b_login_auth_url_request_succ = EPMClientPassportMonitorLoginCode(code: 10020, level: OPMonitorLevelNormal, message: "idp_b_login_auth_url_request_succ")

    /** idp-b跳转浏览器打开登录地址，browser_type */
    public static let idp_b_login_auth_url_browser_open = EPMClientPassportMonitorLoginCode(code: 10021, level: OPMonitorLevelNormal, message: "idp_b_login_auth_url_browser_open")

    /** idp-b登录浏览器验证成功 */
    public static let idp_b_login_browser_auth_succ = EPMClientPassportMonitorLoginCode(code: 10022, level: OPMonitorLevelNormal, message: "idp_b_login_browser_auth_succ")

    /** idp-b登录接口请求成功，next_step */
    public static let idp_b_login_idp_dispatch_request_succ = EPMClientPassportMonitorLoginCode(code: 10023, level: OPMonitorLevelNormal, message: "idp_b_login_idp_dispatch_request_succ")

    /** idp-b登录成功结束，成功进入下一个页面 */
    public static let idp_b_login_end_goto_next_succ = EPMClientPassportMonitorLoginCode(code: 10024, level: OPMonitorLevelNormal, message: "idp_b_login_end_goto_next_succ")

    /** idp-c登录google登录点击量 */
    public static let idp_c_google_login_click = EPMClientPassportMonitorLoginCode(code: 10025, level: OPMonitorLevelNormal, message: "idp_c_google_login_click")

    /** idp-c登录appleId登录点击量 */
    public static let idp_c_apple_login_click = EPMClientPassportMonitorLoginCode(code: 10026, level: OPMonitorLevelNormal, message: "idp_c_apple_login_click")

    /** 点击一键登录后进行了安全扫描 */
    public static let onekey_mobile_security_scan = EPMClientPassportMonitorLoginCode(code: 10027, level: OPMonitorLevelNormal, message: "onekey_mobile_security_scan")

    /** 点击一键登录后进行了安全扫描结果有风险，risk */
    public static let onekey_mobile_security_scan_risk = EPMClientPassportMonitorLoginCode(code: 10028, level: OPMonitorLevelNormal, message: "onekey_mobile_security_scan_risk")

    /** 进行了本地安全扫描并成功了 */
    public static let mobile_security_scan_succ = EPMClientPassportMonitorLoginCode(code: 10033, level: OPMonitorLevelNormal, message: "mobile_security_scan_succ")

    /** 本地安全扫描失败，reason */
    public static let mobile_security_scan_fail = EPMClientPassportMonitorLoginCode(code: 10034, level: OPMonitorLevelNormal, message: "mobile_security_scan_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientPassportMonitorLoginCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.passport.monitor.login"
}