// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformGadgetWebviewComponentCode: OPMonitorCodeBase {

    /** webview拦截不安全域名加载 */
    public static let intercept_unsafe_url = EPMClientOpenPlatformGadgetWebviewComponentCode(code: 10002, level: OPMonitorLevelNormal, message: "intercept_unsafe_url")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformGadgetWebviewComponentCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.gadget.webview.component"
}