// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformApiCommonCode: OPMonitorCodeBase {

    /** native收到js api调用 */
    public static let native_receive_invoke = EPMClientOpenPlatformApiCommonCode(code: 10002, level: OPMonitorLevelNormal, message: "native_receive_invoke")

    /** native回调js */
    public static let native_callback_invoke = EPMClientOpenPlatformApiCommonCode(code: 10003, level: OPMonitorLevelNormal, message: "native_callback_invoke")

    /** native开始派发执行api */
    public static let native_invoke_start = EPMClientOpenPlatformApiCommonCode(code: 10004, level: OPMonitorLevelNormal, message: "native_invoke_start")

    /** native完成API执行 */
    public static let native_invoke_result = EPMClientOpenPlatformApiCommonCode(code: 10005, level: OPMonitorLevelNormal, message: "native_invoke_result")

    /** native使用PM派发执行api */
    public static let native_pm_invoke_start = EPMClientOpenPlatformApiCommonCode(code: 10006, level: OPMonitorLevelNormal, message: "native_pm_invoke_start")

    /** native PM完成api执行 */
    public static let native_pm_invoke_result = EPMClientOpenPlatformApiCommonCode(code: 10007, level: OPMonitorLevelNormal, message: "native_pm_invoke_result")

    /** 新版plugin入参静默checker校验参数值不符合要求 */
    public static let plugin_silent_checker = EPMClientOpenPlatformApiCommonCode(code: 10008, level: OPMonitorLevelNormal, message: "plugin_silent_checker")

    /** 新版plugin入参类型是否符合要求(iOS在非requiredInConfigDict不会对参数类型进行校验,安卓新plugin框架会对类型进行校验, 因此不会有该问题) */
    public static let plugin_paramtype_checker = EPMClientOpenPlatformApiCommonCode(code: 10009, level: OPMonitorLevelNormal, message: "plugin_paramtype_checker")

    /** API 入参校验结果埋点 */
    public static let plugin_input_checker = EPMClientOpenPlatformApiCommonCode(code: 10010, level: OPMonitorLevelNormal, message: "plugin_input_checker")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformApiCommonCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.api.common"
}