// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientPassportMonitorUnspecifiedCode: OPMonitorCodeBase {

    /** 初始化tenant数据，检查是否需要升级session */
    public static let upgrade_session_check = EPMClientPassportMonitorUnspecifiedCode(code: 10001, level: OPMonitorLevelNormal, message: "upgrade_session_check")

    /** 需要升级，开始调用session升级接口upgrade/login，retry_count */
    public static let upgrade_session_request_start = EPMClientPassportMonitorUnspecifiedCode(code: 10002, level: OPMonitorLevelNormal, message: "upgrade_session_request_start")

    /** session升级处理成功，retry_count */
    public static let upgrade_session_end_succ = EPMClientPassportMonitorUnspecifiedCode(code: 10003, level: OPMonitorLevelNormal, message: "upgrade_session_end_succ")

    /** session升级处理失败，退出登录，retry_count */
    public static let upgrade_session_end_fail = EPMClientPassportMonitorUnspecifiedCode(code: 10004, level: OPMonitorLevelError, message: "upgrade_session_end_fail")

    /** env和前台用户不一致 */
    public static let env_not_equal_to_foreground_user = EPMClientPassportMonitorUnspecifiedCode(code: 10007, level: OPMonitorLevelError, message: "env_not_equal_to_foreground_user")

    /** global注册流程出发fallback */
    public static let env_global_register_fallback = EPMClientPassportMonitorUnspecifiedCode(code: 10008, level: OPMonitorLevelError, message: "env_global_register_fallback")

    /** passport测资源拦截检查情况 */
    public static let passport_falcon_intercept = EPMClientPassportMonitorUnspecifiedCode(code: 10011, level: OPMonitorLevelNormal, message: "passport_falcon_intercept")

    /** passport测资源更新耗时 */
    public static let passport_gecko_duration = EPMClientPassportMonitorUnspecifiedCode(code: 10012, level: OPMonitorLevelNormal, message: "passport_gecko_duration")

    /** global注册流程启动 */
    public static let env_global_register_enter = EPMClientPassportMonitorUnspecifiedCode(code: 10013, level: OPMonitorLevelError, message: "env_global_register_enter")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientPassportMonitorUnspecifiedCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.passport.monitor.unspecified"
}