// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformCommonBandageCode: OPMonitorCodeBase {

    /** 拉取止血配置结果 */
    public static let mp_fetch_silence_update_result = EPMClientOpenPlatformCommonBandageCode(code: 10000, level: OPMonitorLevelNormal, message: "mp_fetch_silence_update_result")

    /** 因止血而进行冷启动 */
    public static let mp_silence_update_cold_start = EPMClientOpenPlatformCommonBandageCode(code: 10001, level: OPMonitorLevelNormal, message: "mp_silence_update_cold_start")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformCommonBandageCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.common.bandage"
}