// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientPassportLoginCode: OPMonitorCodeBase {

    /** 暂无注释... */
    public static let passport_login_type_start = EPMClientPassportLoginCode(code: 10000, level: OPMonitorLevelNormal, message: "passport_login_type_start")

    /** biz_code 后端透出的业务错误码 */
    public static let passport_login_type_success = EPMClientPassportLoginCode(code: 10001, level: OPMonitorLevelNormal, message: "passport_login_type_success")

    /** 暂无注释... */
    public static let passport_login_type_fail = EPMClientPassportLoginCode(code: 10002, level: OPMonitorLevelError, message: "passport_login_type_fail")

    /** 暂无注释... */
    public static let passport_register_type_start = EPMClientPassportLoginCode(code: 10003, level: OPMonitorLevelNormal, message: "passport_register_type_start")

    /** 暂无注释... */
    public static let passport_register_type_success = EPMClientPassportLoginCode(code: 10004, level: OPMonitorLevelNormal, message: "passport_register_type_success")

    /** 暂无注释... */
    public static let passport_register_type_fail = EPMClientPassportLoginCode(code: 10005, level: OPMonitorLevelError, message: "passport_register_type_fail")

    /** 暂无注释... */
    public static let passport_bind_contact_start = EPMClientPassportLoginCode(code: 10006, level: OPMonitorLevelNormal, message: "passport_bind_contact_start")

    /** 暂无注释... */
    public static let passport_bind_contact_success = EPMClientPassportLoginCode(code: 10007, level: OPMonitorLevelNormal, message: "passport_bind_contact_success")

    /** 暂无注释... */
    public static let passport_bind_contact_fail = EPMClientPassportLoginCode(code: 10008, level: OPMonitorLevelError, message: "passport_bind_contact_fail")

    /** 暂无注释... */
    public static let passport_otp_apply_code_start = EPMClientPassportLoginCode(code: 10009, level: OPMonitorLevelNormal, message: "passport_otp_apply_code_start")

    /** 暂无注释... */
    public static let passport_otp_apply_code_success = EPMClientPassportLoginCode(code: 10010, level: OPMonitorLevelNormal, message: "passport_otp_apply_code_success")

    /** 暂无注释... */
    public static let passport_otp_apply_code_fail = EPMClientPassportLoginCode(code: 10011, level: OPMonitorLevelError, message: "passport_otp_apply_code_fail")

    /** 暂无注释... */
    public static let passport_otp_verify_code_start = EPMClientPassportLoginCode(code: 10012, level: OPMonitorLevelNormal, message: "passport_otp_verify_code_start")

    /** 暂无注释... */
    public static let passport_otp_verify_code_success = EPMClientPassportLoginCode(code: 10013, level: OPMonitorLevelNormal, message: "passport_otp_verify_code_success")

    /** 暂无注释... */
    public static let passport_otp_verify_code_fail = EPMClientPassportLoginCode(code: 10014, level: OPMonitorLevelError, message: "passport_otp_verify_code_fail")

    /** 暂无注释... */
    public static let passport_verify_pwd_start = EPMClientPassportLoginCode(code: 10015, level: OPMonitorLevelNormal, message: "passport_verify_pwd_start")

    /** 暂无注释... */
    public static let passport_verify_pwd_success = EPMClientPassportLoginCode(code: 10016, level: OPMonitorLevelNormal, message: "passport_verify_pwd_success")

    /** 暂无注释... */
    public static let passport_verify_pwd_fail = EPMClientPassportLoginCode(code: 10017, level: OPMonitorLevelError, message: "passport_verify_pwd_fail")

    /** 暂无注释... */
    public static let passport_app_start = EPMClientPassportLoginCode(code: 10018, level: OPMonitorLevelNormal, message: "passport_app_start")

    /** 暂无注释... */
    public static let passport_app_success = EPMClientPassportLoginCode(code: 10019, level: OPMonitorLevelNormal, message: "passport_app_success")

    /** 暂无注释... */
    public static let passport_app_fail = EPMClientPassportLoginCode(code: 10020, level: OPMonitorLevelError, message: "passport_app_fail")

    /** 暂无注释... */
    public static let passport_create_start = EPMClientPassportLoginCode(code: 10021, level: OPMonitorLevelNormal, message: "passport_create_start")

    /** 暂无注释... */
    public static let passport_create_success = EPMClientPassportLoginCode(code: 10022, level: OPMonitorLevelNormal, message: "passport_create_success")

    /** 暂无注释... */
    public static let passport_create_fail = EPMClientPassportLoginCode(code: 10023, level: OPMonitorLevelError, message: "passport_create_fail")

    /** 暂无注释... */
    public static let passport_auth_url_start = EPMClientPassportLoginCode(code: 10024, level: OPMonitorLevelNormal, message: "passport_auth_url_start")

    /** 暂无注释... */
    public static let passport_auth_url_success = EPMClientPassportLoginCode(code: 10025, level: OPMonitorLevelNormal, message: "passport_auth_url_success")

    /** 暂无注释... */
    public static let passport_auth_url_fail = EPMClientPassportLoginCode(code: 10026, level: OPMonitorLevelError, message: "passport_auth_url_fail")

    /** 暂无注释... */
    public static let passport_sso_url_start = EPMClientPassportLoginCode(code: 10027, level: OPMonitorLevelNormal, message: "passport_sso_url_start")

    /** 暂无注释... */
    public static let passport_sso_url_success = EPMClientPassportLoginCode(code: 10028, level: OPMonitorLevelNormal, message: "passport_sso_url_success")

    /** 暂无注释... */
    public static let passport_sso_url_fail = EPMClientPassportLoginCode(code: 10029, level: OPMonitorLevelError, message: "passport_sso_url_fail")

    /** 暂无注释... */
    public static let passport_set_pwd_start = EPMClientPassportLoginCode(code: 10030, level: OPMonitorLevelNormal, message: "passport_set_pwd_start")

    /** 暂无注释... */
    public static let passport_set_pwd_success = EPMClientPassportLoginCode(code: 10031, level: OPMonitorLevelNormal, message: "passport_set_pwd_success")

    /** 暂无注释... */
    public static let passport_set_pwd_fail = EPMClientPassportLoginCode(code: 10032, level: OPMonitorLevelError, message: "passport_set_pwd_fail")

    /** 暂无注释... */
    public static let passport_set_name_start = EPMClientPassportLoginCode(code: 10033, level: OPMonitorLevelNormal, message: "passport_set_name_start")

    /** 暂无注释... */
    public static let passport_set_name_success = EPMClientPassportLoginCode(code: 10034, level: OPMonitorLevelNormal, message: "passport_set_name_success")

    /** 暂无注释... */
    public static let passport_set_name_fail = EPMClientPassportLoginCode(code: 10035, level: OPMonitorLevelError, message: "passport_set_name_fail")

    /** 暂无注释... */
    public static let passport_official_email_join_start = EPMClientPassportLoginCode(code: 10036, level: OPMonitorLevelNormal, message: "passport_official_email_join_start")

    /** 暂无注释... */
    public static let passport_official_email_join_success = EPMClientPassportLoginCode(code: 10037, level: OPMonitorLevelNormal, message: "passport_official_email_join_success")

    /** 暂无注释... */
    public static let passport_official_email_join_fail = EPMClientPassportLoginCode(code: 10038, level: OPMonitorLevelError, message: "passport_official_email_join_fail")

    /** 暂无注释... */
    public static let passport_team_code_confirm_start = EPMClientPassportLoginCode(code: 10039, level: OPMonitorLevelNormal, message: "passport_team_code_confirm_start")

    /** 暂无注释... */
    public static let passport_team_code_confirm_success = EPMClientPassportLoginCode(code: 10040, level: OPMonitorLevelNormal, message: "passport_team_code_confirm_success")

    /** 暂无注释... */
    public static let passport_team_code_confirm_fail = EPMClientPassportLoginCode(code: 10041, level: OPMonitorLevelError, message: "passport_team_code_confirm_fail")

    /** 暂无注释... */
    public static let passport_team_code_join_start = EPMClientPassportLoginCode(code: 10042, level: OPMonitorLevelNormal, message: "passport_team_code_join_start")

    /** 暂无注释... */
    public static let passport_team_code_join_success = EPMClientPassportLoginCode(code: 10043, level: OPMonitorLevelNormal, message: "passport_team_code_join_success")

    /** 暂无注释... */
    public static let passport_team_code_join_fail = EPMClientPassportLoginCode(code: 10044, level: OPMonitorLevelError, message: "passport_team_code_join_fail")

    /** 暂无注释... */
    public static let passport_verify_token_start = EPMClientPassportLoginCode(code: 10045, level: OPMonitorLevelNormal, message: "passport_verify_token_start")

    /** 暂无注释... */
    public static let passport_verify_token_success = EPMClientPassportLoginCode(code: 10046, level: OPMonitorLevelNormal, message: "passport_verify_token_success")

    /** 暂无注释... */
    public static let passport_verify_token_fail = EPMClientPassportLoginCode(code: 10047, level: OPMonitorLevelError, message: "passport_verify_token_fail")

    /** 暂无注释... */
    public static let passport_login_m_auth_start = EPMClientPassportLoginCode(code: 10048, level: OPMonitorLevelNormal, message: "passport_login_m_auth_start")

    /** 暂无注释... */
    public static let passport_login_m_auth_success = EPMClientPassportLoginCode(code: 10049, level: OPMonitorLevelNormal, message: "passport_login_m_auth_success")

    /** 暂无注释... */
    public static let passport_login_m_auth_fail = EPMClientPassportLoginCode(code: 10050, level: OPMonitorLevelError, message: "passport_login_m_auth_fail")

    /** 暂无注释... */
    public static let passport_register_m_auth_start = EPMClientPassportLoginCode(code: 10051, level: OPMonitorLevelNormal, message: "passport_register_m_auth_start")

    /** 暂无注释... */
    public static let passport_register_m_auth_success = EPMClientPassportLoginCode(code: 10052, level: OPMonitorLevelNormal, message: "passport_register_m_auth_success")

    /** 暂无注释... */
    public static let passport_register_m_auth_fail = EPMClientPassportLoginCode(code: 10053, level: OPMonitorLevelError, message: "passport_register_m_auth_fail")

    /** 暂无注释... */
    public static let passport_recover_operator_start = EPMClientPassportLoginCode(code: 10054, level: OPMonitorLevelNormal, message: "passport_recover_operator_start")

    /** 暂无注释... */
    public static let passport_recover_operator_success = EPMClientPassportLoginCode(code: 10055, level: OPMonitorLevelNormal, message: "passport_recover_operator_success")

    /** 暂无注释... */
    public static let passport_recover_operator_fail = EPMClientPassportLoginCode(code: 10056, level: OPMonitorLevelError, message: "passport_recover_operator_fail")

    /** 暂无注释... */
    public static let passport_recover_bankcard_start = EPMClientPassportLoginCode(code: 10057, level: OPMonitorLevelNormal, message: "passport_recover_bankcard_start")

    /** 暂无注释... */
    public static let passport_recover_bankcard_success = EPMClientPassportLoginCode(code: 10058, level: OPMonitorLevelNormal, message: "passport_recover_bankcard_success")

    /** 暂无注释... */
    public static let passport_recover_bankcard_fail = EPMClientPassportLoginCode(code: 10059, level: OPMonitorLevelError, message: "passport_recover_bankcard_fail")

    /** 暂无注释... */
    public static let passport_recover_newmobile_start = EPMClientPassportLoginCode(code: 10060, level: OPMonitorLevelNormal, message: "passport_recover_newmobile_start")

    /** 暂无注释... */
    public static let passport_recover_newmobile_success = EPMClientPassportLoginCode(code: 10061, level: OPMonitorLevelNormal, message: "passport_recover_newmobile_success")

    /** 暂无注释... */
    public static let passport_recover_newmobile_fail = EPMClientPassportLoginCode(code: 10062, level: OPMonitorLevelError, message: "passport_recover_newmobile_fail")

    /** 暂无注释... */
    public static let passport_recover_face_start = EPMClientPassportLoginCode(code: 10063, level: OPMonitorLevelNormal, message: "passport_recover_face_start")

    /** 暂无注释... */
    public static let passport_recover_face_success = EPMClientPassportLoginCode(code: 10064, level: OPMonitorLevelNormal, message: "passport_recover_face_success")

    /** 暂无注释... */
    public static let passport_recover_face_fail = EPMClientPassportLoginCode(code: 10065, level: OPMonitorLevelError, message: "passport_recover_face_fail")

    /** 暂无注释... */
    public static let passport_recover_change_start = EPMClientPassportLoginCode(code: 10066, level: OPMonitorLevelNormal, message: "passport_recover_change_start")

    /** 暂无注释... */
    public static let passport_recover_change_success = EPMClientPassportLoginCode(code: 10067, level: OPMonitorLevelNormal, message: "passport_recover_change_success")

    /** 暂无注释... */
    public static let passport_recover_change_fail = EPMClientPassportLoginCode(code: 10068, level: OPMonitorLevelError, message: "passport_recover_change_fail")

    /** 暂无注释... */
    public static let passport_guest_login_start = EPMClientPassportLoginCode(code: 10069, level: OPMonitorLevelNormal, message: "passport_guest_login_start")

    /** 暂无注释... */
    public static let passport_guest_login_success = EPMClientPassportLoginCode(code: 10070, level: OPMonitorLevelNormal, message: "passport_guest_login_success")

    /** 暂无注释... */
    public static let passport_guest_login_fail = EPMClientPassportLoginCode(code: 10071, level: OPMonitorLevelError, message: "passport_guest_login_fail")

    /** 暂无注释... */
    public static let passport_verify_polling_start = EPMClientPassportLoginCode(code: 10072, level: OPMonitorLevelNormal, message: "passport_verify_polling_start")

    /** 暂无注释... */
    public static let passport_verify_polling_success = EPMClientPassportLoginCode(code: 10073, level: OPMonitorLevelNormal, message: "passport_verify_polling_success")

    /** 暂无注释... */
    public static let passport_verify_polling_fail = EPMClientPassportLoginCode(code: 10074, level: OPMonitorLevelError, message: "passport_verify_polling_fail")

    /** 暂无注释... */
    public static let passport_join_type_start = EPMClientPassportLoginCode(code: 10075, level: OPMonitorLevelNormal, message: "passport_join_type_start")

    /** 暂无注释... */
    public static let passport_join_type_success = EPMClientPassportLoginCode(code: 10076, level: OPMonitorLevelNormal, message: "passport_join_type_success")

    /** 暂无注释... */
    public static let passport_join_type_fail = EPMClientPassportLoginCode(code: 10077, level: OPMonitorLevelError, message: "passport_join_type_fail")

    /** 暂无注释... */
    public static let passport_otp_verify_otp_start = EPMClientPassportLoginCode(code: 10078, level: OPMonitorLevelNormal, message: "passport_otp_verify_otp_start")

    /** 暂无注释... */
    public static let passport_otp_verify_otp_success = EPMClientPassportLoginCode(code: 10079, level: OPMonitorLevelNormal, message: "passport_otp_verify_otp_success")

    /** 暂无注释... */
    public static let passport_otp_verify_otp_fail = EPMClientPassportLoginCode(code: 10080, level: OPMonitorLevelError, message: "passport_otp_verify_otp_fail")

    /** 将要切换环境 */
    public static let passport_env_will_switch = EPMClientPassportLoginCode(code: 10081, level: OPMonitorLevelNormal, message: "passport_env_will_switch")

    /** 环境切换完成 */
    public static let passport_env_did_switch = EPMClientPassportLoginCode(code: 10082, level: OPMonitorLevelNormal, message: "passport_env_did_switch")

    /** 收到来自 App Log 的 deviceID、installID */
    public static let passport_receive_app_log_info = EPMClientPassportLoginCode(code: 10083, level: OPMonitorLevelNormal, message: "passport_receive_app_log_info")

    /** Passport 本地存储来自 App Log 的 deviceID、installID */
    public static let passport_store_app_log_info = EPMClientPassportLoginCode(code: 10084, level: OPMonitorLevelNormal, message: "passport_store_app_log_info")

    /** App Log 获取 deviceID 失败 */
    public static let passport_did_receive_fail = EPMClientPassportLoginCode(code: 10085, level: OPMonitorLevelError, message: "passport_did_receive_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientPassportLoginCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.passport.login"
}