// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformGroupBotCode: OPMonitorCodeBase {

    /** 拉取机器人列表页数据成功 */
    public static let pull_groupbot_list_success = EPMClientOpenPlatformGroupBotCode(code: 10000, level: OPMonitorLevelNormal, message: "pull_groupbot_list_success")

    /** 拉取机器人列表页数据失败 */
    public static let pull_groupbot_list_fail = EPMClientOpenPlatformGroupBotCode(code: 10001, level: OPMonitorLevelError, message: "pull_groupbot_list_fail")

    /** 拉取可添加机器人列表数据成功 */
    public static let pull_groupbot_candidate_success = EPMClientOpenPlatformGroupBotCode(code: 10002, level: OPMonitorLevelNormal, message: "pull_groupbot_candidate_success")

    /** 拉取可添加机器人列表数据失败 */
    public static let pull_groupbot_candidate_fail = EPMClientOpenPlatformGroupBotCode(code: 10003, level: OPMonitorLevelError, message: "pull_groupbot_candidate_fail")

    /** 搜索机器人成功 */
    public static let search_groupbot_success = EPMClientOpenPlatformGroupBotCode(code: 10004, level: OPMonitorLevelNormal, message: "search_groupbot_success")

    /** 搜索机器人失败 */
    public static let search_groupbot_fail = EPMClientOpenPlatformGroupBotCode(code: 10005, level: OPMonitorLevelError, message: "search_groupbot_fail")

    /** 添加机器人进入群聊(非webhook)成功 */
    public static let add_groupbot_success = EPMClientOpenPlatformGroupBotCode(code: 10008, level: OPMonitorLevelNormal, message: "add_groupbot_success")

    /** 添加机器人进入群聊(非webhook)失败 */
    public static let add_groupbot_fail = EPMClientOpenPlatformGroupBotCode(code: 10009, level: OPMonitorLevelError, message: "add_groupbot_fail")

    /** 从群聊中删除机器人成功 */
    public static let delete_groupbot_success = EPMClientOpenPlatformGroupBotCode(code: 10018, level: OPMonitorLevelNormal, message: "delete_groupbot_success")

    /** 从群聊中删除机器人失败 */
    public static let delete_groupbot_fail = EPMClientOpenPlatformGroupBotCode(code: 10019, level: OPMonitorLevelError, message: "delete_groupbot_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformGroupBotCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.group_bot"
}