// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientPassportMonitorSessionInvalidCode: OPMonitorCodeBase {

    /** 失效处理触发，invoke_reason */
    public static let process_invalid_start = EPMClientPassportMonitorSessionInvalidCode(code: 10001, level: OPMonitorLevelNormal, message: "process_invalid_start")

    /** 检查状态接口请求开始 */
    public static let check_status_request_start = EPMClientPassportMonitorSessionInvalidCode(code: 10002, level: OPMonitorLevelNormal, message: "check_status_request_start")

    /** 检查状态接口请求成功，local_count:端上本地session列表size
	server_count: 接口返回的session列表size
	invalid_count：计算得到的失效session数目
	unregister_count：计算得到的注销session数目
	(invalid_reason_enum:count) session失效的根据原因聚类个数，kv埋点 */
    public static let check_status_request_succ = EPMClientPassportMonitorSessionInvalidCode(code: 10003, level: OPMonitorLevelNormal, message: "check_status_request_succ")

    /** 检查状态接口请求失败 */
    public static let check_status_request_fail = EPMClientPassportMonitorSessionInvalidCode(code: 10004, level: OPMonitorLevelError, message: "check_status_request_fail")

    /** 处理后台用户失效完成 */
    public static let process_invalid_bkg_user_end = EPMClientPassportMonitorSessionInvalidCode(code: 10005, level: OPMonitorLevelNormal, message: "process_invalid_bkg_user_end")

    /** 处理前台用户失效开始 */
    public static let process_invalid_front_user_start = EPMClientPassportMonitorSessionInvalidCode(code: 10006, level: OPMonitorLevelNormal, message: "process_invalid_front_user_start")

    /** 处理前台用户失效结束，block返回 */
    public static let process_invalid_front_user_end_block = EPMClientPassportMonitorSessionInvalidCode(code: 10007, level: OPMonitorLevelNormal, message: "process_invalid_front_user_end_block")

    /** 处理前台失效结束，前台用户转后台切换完成 */
    public static let process_invalid_front_user_end_goto_bkg = EPMClientPassportMonitorSessionInvalidCode(code: 10008, level: OPMonitorLevelNormal, message: "process_invalid_front_user_end_goto_bkg")

    /** 处理前台用户失效完成，切换租户失败退出全部 */
    public static let process_invalid_front_user_end_logout_all = EPMClientPassportMonitorSessionInvalidCode(code: 10009, level: OPMonitorLevelNormal, message: "process_invalid_front_user_end_logout_all")

    /** 处理前台用户失效完成，切换租户成功，switch_reason */
    public static let process_invalid_front_user_end_switch_succ = EPMClientPassportMonitorSessionInvalidCode(code: 10010, level: OPMonitorLevelNormal, message: "process_invalid_front_user_end_switch_succ")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientPassportMonitorSessionInvalidCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.passport.monitor.session_invalid"
}