// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformInfraFileLarkstorageCode: OPMonitorCodeBase {

    /** 开放平台接入LarkStorage */
    public static let openplatform_larkstorage_info = EPMClientOpenPlatformInfraFileLarkstorageCode(code: 10001, level: OPMonitorLevelNormal, message: "openplatform_larkstorage_info")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformInfraFileLarkstorageCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.infra.file_larkstorage"
}