// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientPassportUniversalCode: OPMonitorCodeBase {

    /** Passport Log */
    public static let passport_universal_log = EPMClientPassportUniversalCode(code: 10000, level: OPMonitorLevelNormal, message: "passport_universal_log")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientPassportUniversalCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.passport.universal"
}