// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformWorkerLoadCode: OPMonitorCodeBase {

    /** worker启动 */
    public static let worker_load_result = EPMClientOpenPlatformWorkerLoadCode(code: 10001, level: OPMonitorLevelNormal, message: "worker_load_result")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformWorkerLoadCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.worker.load"
}