// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformCardv2LoadingCode: OPMonitorCodeBase {

    /** 新版本消息卡片，端侧开始处理消息卡片时，上报该埋点。(解析开始) */
    public static let messagecardv2_process_start = EPMClientOpenPlatformCardv2LoadingCode(code: 10000, level: OPMonitorLevelNormal, message: "messagecardv2_process_start")

    /** 新版本消息卡片，消息卡片渲染结束，无任何异常(渲染结束意味着消息卡片整体流程结束) */
    public static let messagecardv2_process_success = EPMClientOpenPlatformCardv2LoadingCode(code: 10001, level: OPMonitorLevelNormal, message: "messagecardv2_process_success")

    /** 新版本消息卡片，消息卡片流程结束(发生阻断性异常 || 不影响整体流程的异常) */
    public static let messagecardv2_process_fail = EPMClientOpenPlatformCardv2LoadingCode(code: 10002, level: OPMonitorLevelNormal, message: "messagecardv2_process_fail")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformCardv2LoadingCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.cardv2.loading"
}