// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformShareCode: OPMonitorCodeBase {

    /** 分享各个入口触发点 */
    public static let share_entry_start = EPMClientOpenPlatformShareCode(code: 10001, level: OPMonitorLevelNormal, message: "share_entry_start")

    /** 分享接口参数校验失败（GadgetAPI，H5-JSSDK） */
    public static let share_api_verify_failed = EPMClientOpenPlatformShareCode(code: 10002, level: OPMonitorLevelError, message: "share_api_verify_failed")

    /** 分享上传图片成功 */
    public static let share_upload_image_success = EPMClientOpenPlatformShareCode(code: 10003, level: OPMonitorLevelNormal, message: "share_upload_image_success")

    /** 分享上传图片失败 */
    public static let share_upload_image_failed = EPMClientOpenPlatformShareCode(code: 10004, level: OPMonitorLevelError, message: "share_upload_image_failed")

    /** 分享逻辑唤起分享容器（新旧版本） */
    public static let share_container_start = EPMClientOpenPlatformShareCode(code: 10005, level: OPMonitorLevelNormal, message: "share_container_start")

    /** 分享容器关闭 */
    public static let share_container_close = EPMClientOpenPlatformShareCode(code: 10006, level: OPMonitorLevelNormal, message: "share_container_close")

    /** 分享卡片成功 */
    public static let share_card_success = EPMClientOpenPlatformShareCode(code: 10007, level: OPMonitorLevelNormal, message: "share_card_success")

    /** 分享卡片失败 */
    public static let share_card_failed = EPMClientOpenPlatformShareCode(code: 10008, level: OPMonitorLevelError, message: "share_card_failed")

    /** 分享转换短链成功 */
    public static let share_convert_short_link_success = EPMClientOpenPlatformShareCode(code: 10009, level: OPMonitorLevelNormal, message: "share_convert_short_link_success")

    /** 分享转换短链失败 */
    public static let share_convert_short_link_failed = EPMClientOpenPlatformShareCode(code: 10010, level: OPMonitorLevelNormal, message: "share_convert_short_link_failed")

    /** 分享容器复制分享链接成功 */
    public static let share_link_copy = EPMClientOpenPlatformShareCode(code: 10011, level: OPMonitorLevelNormal, message: "share_link_copy")

    /** 分享容器保存二维码成功 */
    public static let share_qrcode_save_success = EPMClientOpenPlatformShareCode(code: 10012, level: OPMonitorLevelNormal, message: "share_qrcode_save_success")

    /** 分享容器保存二维码失败 */
    public static let share_qrcode_save_failed = EPMClientOpenPlatformShareCode(code: 10013, level: OPMonitorLevelError, message: "share_qrcode_save_failed")

    /** 接口：获取分享应用信息成功 */
    public static let share_get_app_info_success = EPMClientOpenPlatformShareCode(code: 10014, level: OPMonitorLevelNormal, message: "share_get_app_info_success")

    /** 接口：获取分享应用信息失败 */
    public static let share_get_app_info_failed = EPMClientOpenPlatformShareCode(code: 10015, level: OPMonitorLevelError, message: "share_get_app_info_failed")

    /** 触发/client/app_share/open */
    public static let share_applink_start = EPMClientOpenPlatformShareCode(code: 10016, level: OPMonitorLevelNormal, message: "share_applink_start")

    /** 分享 applink 参数校验失败 */
    public static let share_applink_verify_failed = EPMClientOpenPlatformShareCode(code: 10017, level: OPMonitorLevelError, message: "share_applink_verify_failed")

    /** 分享applink: /client/app_share/open 打开对应能力 */
    public static let share_applink_open_ability = EPMClientOpenPlatformShareCode(code: 10018, level: OPMonitorLevelNormal, message: "share_applink_open_ability")

    /** 分享应用链接成功 */
    public static let share_link_success = EPMClientOpenPlatformShareCode(code: 10019, level: OPMonitorLevelNormal, message: "share_link_success")

    /** 分享应用链接成功 */
    public static let share_link_failed = EPMClientOpenPlatformShareCode(code: 10020, level: OPMonitorLevelError, message: "share_link_failed")

    /** 分享应用二维码成功 */
    public static let share_qrcode_success = EPMClientOpenPlatformShareCode(code: 10021, level: OPMonitorLevelNormal, message: "share_qrcode_success")

    /** 分享应用二维码失败 */
    public static let share_qrcode_failed = EPMClientOpenPlatformShareCode(code: 10022, level: OPMonitorLevelError, message: "share_qrcode_failed")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformShareCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.share"
}