// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformGadgetLifecycleCode: OPMonitorCodeBase {

    /** 展示进入，包括第一次进入或back导致的页面重新展示 */
    public static let page_appear = EPMClientOpenPlatformGadgetLifecycleCode(code: 10000, level: OPMonitorLevelNormal, message: "page_appear")

    /** 页面加载完成(首次) */
    public static let page_onready = EPMClientOpenPlatformGadgetLifecycleCode(code: 10001, level: OPMonitorLevelNormal, message: "page_onready")

    /** 离开页面，包括进入下一级页面或back导致的离开页面 */
    public static let page_disappear = EPMClientOpenPlatformGadgetLifecycleCode(code: 10002, level: OPMonitorLevelNormal, message: "page_disappear")

    /** 小程序进入前台 */
    public static let gadget_foreground = EPMClientOpenPlatformGadgetLifecycleCode(code: 10003, level: OPMonitorLevelNormal, message: "gadget_foreground")

    /** 小程序进入后台 */
    public static let gadget_background = EPMClientOpenPlatformGadgetLifecycleCode(code: 10004, level: OPMonitorLevelNormal, message: "gadget_background")

    /** 小程序关闭（手动点击关闭，可能与gadget_background存在部分重合） */
    public static let gadget_close = EPMClientOpenPlatformGadgetLifecycleCode(code: 10007, level: OPMonitorLevelNormal, message: "gadget_close")

    /** 小程序心跳埋点 */
    public static let gadget_heartbeat = EPMClientOpenPlatformGadgetLifecycleCode(code: 10008, level: OPMonitorLevelNormal, message: "gadget_heartbeat")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformGadgetLifecycleCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.gadget.lifecycle"
}