// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformGadgetLaunchRenderCode: OPMonitorCodeBase {

    /** render 加载结束 */
    public static let render_load_result = EPMClientOpenPlatformGadgetLaunchRenderCode(code: 10000, level: OPMonitorLevelNormal, message: "render_load_result")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformGadgetLaunchRenderCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.gadget.launch.render"
}