// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformAppCenterRouterCode: OPMonitorCodeBase {

    /** 打开小程序失败，url不合法 */
    public static let open_mini_program_url_invalid = EPMClientOpenPlatformAppCenterRouterCode(code: 10000, level: OPMonitorLevelError, message: "open_mini_program_url_invalid")

    /** 打开H5失败，url不合法 */
    public static let open_h5_url_invalid = EPMClientOpenPlatformAppCenterRouterCode(code: 10001, level: OPMonitorLevelError, message: "open_h5_url_invalid")

    /** 打开H5拼接app_id失败 */
    public static let open_h5_url_miss_app_id = EPMClientOpenPlatformAppCenterRouterCode(code: 10002, level: OPMonitorLevelError, message: "open_h5_url_miss_app_id")

    /** 打开bot缺少botid */
    public static let open_bot_chat_id_empty = EPMClientOpenPlatformAppCenterRouterCode(code: 10003, level: OPMonitorLevelError, message: "open_bot_chat_id_empty")

    /** 打开一方应用，找不到tab */
    public static let open_native_app_tab_empty = EPMClientOpenPlatformAppCenterRouterCode(code: 10004, level: OPMonitorLevelError, message: "open_native_app_tab_empty")

    /** 打开applink失败，url不合法 */
    public static let open_app_link_url_invalid = EPMClientOpenPlatformAppCenterRouterCode(code: 10005, level: OPMonitorLevelError, message: "open_app_link_url_invalid")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformAppCenterRouterCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.app_center.router"
}