// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMClientOpenPlatformAppCenterBackgroundCode: OPMonitorCodeBase {

    /** 背景拉取相关数据上报 */
    public static let workplace_background_fetch_result = EPMClientOpenPlatformAppCenterBackgroundCode(code: 10000, level: OPMonitorLevelNormal, message: "workplace_background_fetch_result")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMClientOpenPlatformAppCenterBackgroundCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "client.open_platform.app_center.background"
}