// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMJsOpenPlatformGadgetAppShortCutCode: OPMonitorCodeBase {

    /** 导索页获取数据成功 */
    public static let guide_page_request_data_success = EPMJsOpenPlatformGadgetAppShortCutCode(code: 10000, level: OPMonitorLevelNormal, message: "guide_page_request_data_success")

    /** 导索页获取数据失败 */
    public static let guide_page_request_data_fail = EPMJsOpenPlatformGadgetAppShortCutCode(code: 10001, level: OPMonitorLevelError, message: "guide_page_request_data_fail")

    /** +号列表数据正常执行（整体） */
    public static let keyboard_items_event = EPMJsOpenPlatformGadgetAppShortCutCode(code: 10002, level: OPMonitorLevelNormal, message: "keyboard_items_event")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMJsOpenPlatformGadgetAppShortCutCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "js.open_platform.gadget.app_short_cut"
}