// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMJsOpenPlatformGadgetAppMsgActionCode: OPMonitorCodeBase {

    /** message action普通事件 */
    public static let message_action_event = EPMJsOpenPlatformGadgetAppMsgActionCode(code: 10000, level: OPMonitorLevelNormal, message: "message_action_event")

    /** message action查询消息详情失败 */
    public static let message_action_get_detail_error = EPMJsOpenPlatformGadgetAppMsgActionCode(code: 10001, level: OPMonitorLevelError, message: "message_action_get_detail_error")

    /** message action查询消息详情事件 */
    public static let message_action_get_detail_event = EPMJsOpenPlatformGadgetAppMsgActionCode(code: 10002, level: OPMonitorLevelNormal, message: "message_action_get_detail_event")

    /** message action查询消息js-api查询 */
    public static let message_action_get_js_api_call = EPMJsOpenPlatformGadgetAppMsgActionCode(code: 10003, level: OPMonitorLevelNormal, message: "message_action_get_js_api_call")

    /** message action解析失败 */
    public static let message_action_get_detail_decode_error = EPMJsOpenPlatformGadgetAppMsgActionCode(code: 10004, level: OPMonitorLevelError, message: "message_action_get_detail_decode_error")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMJsOpenPlatformGadgetAppMsgActionCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "js.open_platform.gadget.app_msg_action"
}