// DO NOT EDIT.
//
// Generated by the iOS generator for OPMonitorCode.
// Source:   

import Foundation

@objcMembers
public final class EPMMonitorBaseHeartbeatCode: OPMonitorCodeBase {

    /** 心跳埋点 monitor */
    public static let heartbeat_report = EPMMonitorBaseHeartbeatCode(code: 10000, level: OPMonitorLevelNormal, message: "heartbeat_report")


    private init(code: Int, level:  OPMonitorLevel, message: String) {
        super.init(domain: EPMMonitorBaseHeartbeatCode.domain, code: code, level: level, message: message)
    }

    static public let domain = "monitor.base.heartbeat"
}