//
//  EmotionHelper.swift
//  LarkEmotion
//
//  Created by 李勇 on 2021/3/3.
//

import UIKit
import Foundation

/// EmotionHelper
final class EmotionHelper {
    /// 读取指定文件名.plist
    static func readPlistContent(_ name: String) -> Any {
        // lint:disable:next lark_storage_check - 从 Bundle 读取，不涉及加解密，无需接入统一存储
        return NSArray(contentsOfFile: BundleConfig.LarkEmotionBundle.path(forResource: name, ofType: "plist")!)!
    }

    /// 根据名字读取图片
    static func image(named: String) -> UIImage? {
        return UIImage(named: named, in: BundleConfig.LarkEmotionBundle, compatibleWith: nil)
    }

    static let keyToSkinKeysMap: [String: [String]] = [
        "Lark_Emoji_Thumbsup_0": ["MediumLightThumbsup", "LightThumbsup",
                                  "Lark_Emoji_Thumbsup_0", "MediumThumbsup",
                                  "MediumDarkThumbsup", "DarkThumbsup"],
        "THUMBSUP": ["MediumLightThumbsup", "LightThumbsup",
                                  "Lark_Emoji_Thumbsup_0", "MediumThumbsup",
                                  "MediumDarkThumbsup", "DarkThumbsup"],
        "Lark_Emoji_Thanks_0": ["MediumLightThanks", "LightThanks",
                                "Lark_Emoji_Thanks_0", "MediumThanks",
                                "MediumDarkThanks", "DarkThanks"],
        "THANKS": ["MediumLightThanks", "LightThanks",
                                "Lark_Emoji_Thanks_0", "MediumThanks",
                                "MediumDarkThanks", "DarkThanks"],
        "Lark_Emoji_Fighting_0": ["MediumLightFightOn", "LightFightOn",
                                  "Lark_Emoji_Fighting_0", "MediumFightOn",
                                  "MediumDarkFightOn", "DarkFightOn"],
        "MUSCLE": ["MediumLightFightOn", "LightFightOn",
                                  "Lark_Emoji_Fighting_0", "MediumFightOn",
                                  "MediumDarkFightOn", "DarkFightOn"],
        "Lark_Emoji_FingerHeart_0": ["MediumLightFingerHeart", "LightFingerHeart",
                                     "Lark_Emoji_FingerHeart_0", "MediumFingerHeart",
                                     "MediumDarkFingerHeart", "DarkFingerHeart"],
        "FINGERHEART": ["MediumLightFingerHeart", "LightFingerHeart",
                                     "Lark_Emoji_FingerHeart_0", "MediumFingerHeart",
                                     "MediumDarkFingerHeart", "DarkFingerHeart"],
        "Lark_Emoji_Applaud_0": ["MediumLightApplaud", "LightApplaud",
                                 "Lark_Emoji_Applaud_0", "MediumApplaud",
                                 "MediumDarkApplaud", "DarkApplaud"],
        "APPLAUSE": ["MediumLightApplaud", "LightApplaud",
                                 "Lark_Emoji_Applaud_0", "MediumApplaud",
                                 "MediumDarkApplaud", "DarkApplaud"],
        "Lark_Emoji_FistBump_0": ["MediumLightFistBump", "LightFistBump",
                                  "Lark_Emoji_FistBump_0", "MediumFistBump",
                                  "MediumDarkFistBump", "DarkFistBump"],
        "FISTBUMP": ["MediumLightFistBump", "LightFistBump",
                                  "Lark_Emoji_FistBump_0", "MediumFistBump",
                                  "MediumDarkFistBump", "DarkFistBump"],
        "Lark_Emoji_HighFive_0": ["MediumLightHighFive", "LightHighFive",
                                  "Lark_Emoji_HighFive_0", "MediumHighFive",
                                  "MediumDarkHighFive", "DarkHighFive"],
        "HIGHFIVE": ["MediumLightHighFive", "LightHighFive",
                                  "Lark_Emoji_HighFive_0", "MediumHighFive",
                                  "MediumDarkHighFive", "DarkHighFive"],
        "Lark_Emoji_UpperLeft_0": ["MediumLightClick", "LightClick",
                                   "Lark_Emoji_UpperLeft_0", "MediumClick",
                                   "MediumDarkClick", "DarkClick"],
        "UPPERLEFT": ["MediumLightClick", "LightClick",
                                   "Lark_Emoji_UpperLeft_0", "MediumClick",
                                   "MediumDarkClick", "DarkClick"],
        "ThumbsDown": ["MediumLightThumbsDown", "LightThumbsDown", "ThumbsDown",
                       "MediumThumbsDown", "MediumDarkThumbsDown", "DarkThumbsDown"],
        "Salute": ["MediumLightSalute", "LightSalute", "Salute",
                  "MediumSalute", "MediumDarkSalute", "DarkSalute"],
        "SALUTE": ["MediumLightSalute", "LightSalute", "Salute",
                  "MediumSalute", "MediumDarkSalute", "DarkSalute"],
        "Lark_Emoji_Shake_0": ["MediumLightShake", "LightShake", "Lark_Emoji_Shake_0",
                               "MediumShake", "MediumDarkShake", "DarkShake"],
        "SHAKE": ["MediumLightShake", "LightShake", "Lark_Emoji_Shake_0",
                               "MediumShake", "MediumDarkShake", "DarkShake"],
        "WavingHand": ["MediumlightWavingHand", "LightWavingHand", "WavingHand", "MediumWavingHand", "MediumdarkWavingHand", "DarkWavingHand"],
        "YouAreTheBest": ["MediumlightYouAreTheBest", "LightYouAreTheBest", "YouAreTheBest", "MediumYouAreTheBest", "MediumdarkYouAreTheBest", "DarkYouAreTheBest"]
    ]

    /// 如果是5个，配置为：(国内ImageKey, 国际化文案key, EmotionKey, 国内ImageName, ReactionKey)
    /// 如果是7个，配置为：(国内ImageKey, 国际化文案key, EmotionKey, 国内ImageName, ReactionKey, 英文/海外ImageName, 英文/海外ImageKey)
    /// 启动耗时优化，去掉plist文件读取，直接写数据
    static let emotionInfos: [[String]] = [
        ["emoji_smile.png", BundleI18n.LarkEmotion.Emoji_Smile, "Lark_Emoji_Smile_0", "1", "SMILE"],
        ["emoji_drool.png", BundleI18n.LarkEmotion.Emoji_Drool, "Lark_Emoji_Drool_0", "2", "DROOL"],
        ["emoji_scowl.png", BundleI18n.LarkEmotion.Emoji_Scowl, "Lark_Emoji_Scowl_0", "3", "SCOWL"],
        ["emoji_irritated_v2.png", BundleI18n.LarkEmotion.Emoji_Irritated, "Lark_Emoji_haughty_0", "4", "HAUGHTY"],
        ["emoji_nosepick.png", BundleI18n.LarkEmotion.Emoji_NosePick, "Lark_Emoji_NosePick_0", "5", "NOSEPICK"],
        ["emoji_sob.png", BundleI18n.LarkEmotion.Emoji_Sob, "Lark_Emoji_Sob_0", "6", "SOB"],
        ["emoji_angry.png", BundleI18n.LarkEmotion.Emoji_Angry, "Lark_Emoji_Angry_0", "7", "ANGRY"],
        ["emoji_grin.png", BundleI18n.LarkEmotion.Emoji_Grin, "Lark_Emoji_Grin_0", "8", "BLUSH"],
        ["emoji_sleep.png", BundleI18n.LarkEmotion.Emoji_Sleep, "Lark_Emoji_Sleep_0", "9", "SLEEP"],
        ["emoji_shy.png", BundleI18n.LarkEmotion.Emoji_Shy, "Lark_Emoji_Shy_0", "10", "SHY"],
        ["emoji_wink.png", BundleI18n.LarkEmotion.Emoji_Wink, "Lark_Emoji_Wink_0", "11", "WINK"],
         ["emoji_dizzy.png", BundleI18n.LarkEmotion.Emoji_Dizzy, "Lark_Emoji_Dizzy_0", "12", "DIZZY"],
        ["emoji_toasted.png", BundleI18n.LarkEmotion.Emoji_Toasted, "Lark_Emoji_Toasted_0", "13", "TOASTED"],
        ["emoji_silent.png", BundleI18n.LarkEmotion.Emoji_Silent, "Lark_Emoji_Silent_0", "14", "SILENT"],
        ["emoji_smart.png", BundleI18n.LarkEmotion.Emoji_Smart, "Lark_Emoji_Smart_0", "15", "SMART"],
        ["emoji_attention.png", BundleI18n.LarkEmotion.Emoji_Attention, "Lark_Emoji_Attention_0", "16", "ATTENTION"],
        ["emoji_witty.png", BundleI18n.LarkEmotion.Emoji_Witty, "Lark_Emoji_Witty_0", "17", "WITTY"],
        ["emoji_yeah.png", BundleI18n.LarkEmotion.Emoji_Yeah, "Lark_Emoji_Yeah_0", "18", "YEAH"],
        ["emoji_facepalm.png", BundleI18n.LarkEmotion.Emoji_Facepalm, "Lark_Emoji_Facepalm_0", "19", "FACEPALM"],
        ["emoji_slap.png", BundleI18n.LarkEmotion.Emoji_Slap, "Lark_Emoji_Slap_0", "20", "SLAP"],
        ["emoji_laugh.png", BundleI18n.LarkEmotion.Emoji_Laugh, "Lark_Emoji_Laugh_0", "21", "LAUGH"],
        ["emoji_yawn.png", BundleI18n.LarkEmotion.Emoji_Yawn, "Lark_Emoji_Yawn_0", "22", "YAWN"],
        ["emoji_shocked.png", BundleI18n.LarkEmotion.Emoji_Shocked, "Lark_Emoji_Shocked_0", "23", "SHOCKED"],
        ["emoji_love.png", BundleI18n.LarkEmotion.Emoji_Love, "Lark_Emoji_Love_0", "24", "LOVE"],
        ["emoji_drowsy.png", BundleI18n.LarkEmotion.Emoji_Drowsy, "Lark_Emoji_Drowsy_0", "25", "DROWSY"],
        ["emoji_what.png", BundleI18n.LarkEmotion.Emoji_What, "Lark_Emoji_What_0", "26", "WHAT"],
        ["emoji_cry.png", BundleI18n.LarkEmotion.Emoji_Cry, "Lark_Emoji_Cry_0", "27", "CRY"],
        ["emoji_clap.png", BundleI18n.LarkEmotion.Emoji_Clap, "Lark_Emoji_Clap_0", "28", "CLAP"],
        ["emoji_showoff.png", BundleI18n.LarkEmotion.Emoji_ShowOff, "Lark_Emoji_ShowOff_0", "29", "SHOWOFF"],
        ["emoji_chuckle.png", BundleI18n.LarkEmotion.Emoji_Chuckle, "Lark_Emoji_Chuckle_0", "30", "CHUCKLE"],
        ["emoji_petrified.png", BundleI18n.LarkEmotion.Emoji_Petrified, "Lark_Emoji_Petrified_0", "31", "PETRIFIED"],
        ["emoji_thinking.png", BundleI18n.LarkEmotion.Emoji_Thinking, "Lark_Emoji_Thinking_0", "32", "THINKING"],
        ["emoji_spitblood.png", BundleI18n.LarkEmotion.Emoji_SpitBlood, "Lark_Emoji_SpitBlood_0", "33", "SPITBLOOD"],
        ["emoji_whimper.png", BundleI18n.LarkEmotion.Emoji_Whimper, "Lark_Emoji_Whimper_0", "34", "WHIMPER"],
        ["emoji_shhh.png", BundleI18n.LarkEmotion.Emoji_Shhh, "Lark_Emoji_Shhh_0", "35", "SHHH"],
        ["emoji_smug.png", BundleI18n.LarkEmotion.Emoji_Smug, "Lark_Emoji_Smug_0", "36", "SMUG"],
        ["emoji_errr.png", BundleI18n.LarkEmotion.Emoji_Errr, "Lark_Emoji_Errr_0", "37", "ERROR"],
        ["emoji_lol.png", BundleI18n.LarkEmotion.Emoji_Lol, "Lark_Emoji_Lol_0", "38", "LOL"],
        ["emoji_sick.png", BundleI18n.LarkEmotion.Emoji_Sick, "Lark_Emoji_Sick_0", "39", "SICK"],
        ["emoji_smirk.png", BundleI18n.LarkEmotion.Emoji_Smirk, "Lark_Emoji_Smirk_0", "40", "SMIRK"],
        ["emoji_proud.png", BundleI18n.LarkEmotion.Emoji_Proud, "Lark_Emoji_Proud_0", "41", "PROUD"],
        ["emoji_trick.png", BundleI18n.LarkEmotion.Emoji_Trick, "Lark_Emoji_Trick_0", "42", "TRICK"],
        ["emoji_crazy.png", BundleI18n.LarkEmotion.Emoji_Crazy, "Lark_Emoji_Crazy_0", "43", "CRAZY"],
        ["emoji_tears.png", BundleI18n.LarkEmotion.Emoji_Tears, "Lark_Emoji_Tears_0", "44", "TEARS"],
        ["emoji_money.png", BundleI18n.LarkEmotion.Emoji_Money, "Lark_Emoji_Money_0", "45", "MONEY", "45_lark", "emoji_dollar.png"],
        ["emoji_kiss.png", BundleI18n.LarkEmotion.Emoji_Kiss, "Lark_Emoji_Kiss_0", "46", "KISS"],
        ["emoji_terror.png", BundleI18n.LarkEmotion.Emoji_Terror, "Lark_Emoji_Terror_0", "47", "TERROR"],
        ["emoji_joyful.png", BundleI18n.LarkEmotion.Emoji_Joyful, "Lark_Emoji_Joyful_0", "48", "JOYFUL"],
        ["emoji_blubber.png", BundleI18n.LarkEmotion.Emoji_Blubber, "Lark_Emoji_Blubber_0", "49", "BLUBBER"],
        ["emoji_husky.png", BundleI18n.LarkEmotion.Emoji_Husky, "Lark_Emoji_Husky_0", "50", "HUSKY"],
        ["emoji_followme.png", BundleI18n.LarkEmotion.Emoji_FollowMe, "Lark_Emoji_FollowMe_0", "51", "FOLLOWME"],
        ["emoji_ok_v2.png", BundleI18n.LarkEmotion.Emoji_OK, "Lark_Emoji_OK_0", "99", "OK", "99_lark", "emoji_ok_v2.png"],
        ["emoji_heart.png", BundleI18n.LarkEmotion.Emoji_Heart, "Lark_Emoji_Heart_0", "107", "HEART"],
        ["emoji_lips_v1.png", BundleI18n.LarkEmotion.Emoji_Lips_new, "Lark_Emoji_Lips_0", "55", "LIPS"],
        ["emoji_detergent.png", BundleI18n.LarkEmotion.Emoji_Detergent, "Lark_Emoji_Detergent_0", "56", "DETERGENT"],
        ["emoji_awesome.png", BundleI18n.LarkEmotion.Emoji_Awesome, "Lark_Emoji_Awesome_0", "57", "AWESOME"],
        ["emoji_rose.png", BundleI18n.LarkEmotion.Emoji_Rose, "Lark_Emoji_Rose_0", "58", "ROSE"],
        ["emoji_cucumber_v3.png", BundleI18n.LarkEmotion.Emoji_Cucumber, "Lark_Emoji_Cucumber_0", "59", "CUCUMBER"],
        ["emoji_beer.png", BundleI18n.LarkEmotion.Emoji_Beer, "Lark_Emoji_Beer_0", "60", "BEER"],
        ["emoji_enough.png", BundleI18n.LarkEmotion.Emoji_Enough, "Lark_Emoji_Enough_0", "61", "ENOUGH"],
        ["emoji_wronged.png", BundleI18n.LarkEmotion.Emoji_Wronged, "Lark_Emoji_Wronged_0", "62", "WRONGED"],
        ["emoji_hearts_v2.png", BundleI18n.LarkEmotion.Emoji_Hearts, "Lark_Emoji_Obsessed_0", "63", "OBSESSED"],
        ["emoji_lookdown.png", BundleI18n.LarkEmotion.Emoji_LookDown, "Lark_Emoji_LookDown_0", "64", "LOOKDOWN"],
        ["emoji_smooch.png", BundleI18n.LarkEmotion.Emoji_Smooch, "Lark_Emoji_Smooch_0", "65", "SMOOCH"],
        ["emoji_wave.png", BundleI18n.LarkEmotion.Emoji_Wave, "Lark_Emoji_Wave_0", "66", "WAVE"],
        ["emoji_donnotgo.png", BundleI18n.LarkEmotion.Emoji_DonnotGo, "Lark_Emoji_DonnotGo_0", "67", "DONNOTGO"],
        ["emoji_headset_v3.png", BundleI18n.LarkEmotion.Emoji_Headset, "Lark_Emoji_Headset_0", "68", "HEADSET"],
        ["emoji_hug.png", BundleI18n.LarkEmotion.Emoji_Hug, "Lark_Emoji_Hug_0", "69", "HUG"],
        ["emoji_dullstare.png", BundleI18n.LarkEmotion.Emoji_DullStare, "Lark_Emoji_DullStare_0", "70", "DULLSTARE"],
        ["emoji_innocentsmile.png", BundleI18n.LarkEmotion.Emoji_InnocentSmile, "Lark_Emoji_InnocentSmile_0", "71", "INNOCENTSMILE"],
        ["emoji_tongue.png", BundleI18n.LarkEmotion.Emoji_Tongue, "Lark_Emoji_Tongue_0", "72", "TONGUE"],
        ["emoji_dull.png", BundleI18n.LarkEmotion.Emoji_Dull, "Lark_Emoji_Dull_0", "73", "DULL"],
        ["emoji_glance.png", BundleI18n.LarkEmotion.Emoji_Glance, "Lark_Emoji_Glance_0", "74", "GLANCE"],
        ["emoji_slight.png", BundleI18n.LarkEmotion.Emoji_Slight, "Lark_Emoji_Slight_0", "75", "SLIGHT"],
        ["emoji_bear.png", BundleI18n.LarkEmotion.Emoji_Bear, "Lark_Emoji_Bear_0", "76", "BEAR"],
        ["emoji_skull.png", BundleI18n.LarkEmotion.Emoji_Skull, "Lark_Emoji_Skull_0", "77", "SKULL"],
        ["emoji_blackface.png", BundleI18n.LarkEmotion.Emoji_BlackFace, "Lark_Emoji_BlackFace_0", "78", "BLACKFACE"],
        ["emoji_eating.png", BundleI18n.LarkEmotion.Emoji_Eating, "Lark_Emoji_Eating_0", "79", "EATING"],
        ["emoji_betrayed.png", BundleI18n.LarkEmotion.Emoji_Betrayed, "Lark_Emoji_Betrayed_0", "80", "BETRAYED", "80_lark", "emoji_mad.png"],
        ["emoji_sweat.png", BundleI18n.LarkEmotion.Emoji_Sweat, "Lark_Emoji_Sweat_0", "81", "SWEAT"],
        ["emoji_comfort.png", BundleI18n.LarkEmotion.Emoji_Comfort, "Lark_Emoji_Comfort_0", "82", "COMFORT"],
        ["emoji_frown.png", BundleI18n.LarkEmotion.Emoji_Frown, "Lark_Emoji_Frown_0", "83", "FROWN"],
        ["emoji_speechless.png", BundleI18n.LarkEmotion.Emoji_Speechless, "Lark_Emoji_Speechless_0", "84", "SPEECHLESS"],
        ["emoji_blush.png", BundleI18n.LarkEmotion.Emoji_Blush, "Lark_Emoji_Blush_0", "85", "XBLUSH"],
        ["emoji_embarrassed.png", BundleI18n.LarkEmotion.Emoji_Embarrassed, "Lark_Emoji_Embarrassed_0", "86", "EMBARRASSED"],
        ["emoji_tease.png", BundleI18n.LarkEmotion.Emoji_Tease, "Lark_Emoji_Tease_0", "87", "TEASE"],
        ["emoji_praise.png", BundleI18n.LarkEmotion.Emoji_Praise, "Lark_Emoji_Praise_0", "88", "PRAISE"],
        ["emoji_bigkiss.png", BundleI18n.LarkEmotion.Emoji_BigKiss, "Lark_Emoji_BigKiss_0", "89", "BIGKISS"],
        ["emoji_puke.png", BundleI18n.LarkEmotion.Emoji_Puke, "Lark_Emoji_Puke_0", "90", "PUKE"],
        ["emoji_wow.png", BundleI18n.LarkEmotion.Emoji_Wow, "Lark_Emoji_Wow_0", "91", "WOW"],
        ["emoji_hammer_v1.png", BundleI18n.LarkEmotion.Emoji_Hammer, "Lark_Emoji_Hammer_0", "92", "HAMMER"],
        ["emoji_strive.png", BundleI18n.LarkEmotion.Emoji_Strive, "Lark_Emoji_Strive_0", "93", "STRIVE"],
        ["emoji_rainbowpuke_v2.png", BundleI18n.LarkEmotion.Emoji_RainbowPuke, "Lark_Emoji_RainbowPuke_0", "94", "RAINBOWPUKE"],
        ["emoji_wail.png", BundleI18n.LarkEmotion.Emoji_Wail, "Lark_Emoji_Wail_0", "95", "WAIL"],
        ["emoji_done.png", BundleI18n.LarkEmotion.Emoji_Done, "Done", "117", "DONE"],
        ["emoji_eighteen.png", BundleI18n.LarkEmotion.Emoji_Eighteen, "Lark_Emoji_18x_0", "103", "18X"],
        ["emoji_cleaver_v3.png", BundleI18n.LarkEmotion.Emoji_Cleaver, "Lark_Emoji_Cleaver_0", "104", "CLEAVER"],
        ["emoji_plusone.png", BundleI18n.LarkEmotion.Emoji_PlusOne, "+1", "116", "JIAYI"],
        ["emoji_welldone.png", BundleI18n.LarkEmotion.Emoji_WellDone, "Lark_Emoji_WellDone_0", "105", "WELLDONE"],
        ["emoji_goodjob.png", BundleI18n.LarkEmotion.Emoji_GoodJob, "Lark_Emoji_GoodJob_0", "106", "GOODJOB"],
        ["emoji_heartbroken.png", BundleI18n.LarkEmotion.Emoji_HeartBroken, "Lark_Emoji_HeartBroken_0", "108", "HEARTBROKEN"],
        ["emoji_poop.png", BundleI18n.LarkEmotion.Emoji_Poop, "Lark_Emoji_Poop_0", "109", "POOP"],
        ["emoji_gift_v2.png", BundleI18n.LarkEmotion.Emoji_Gift, "Lark_Emoji_Gift_0", "110", "GIFT"],
        ["emoji_cake_v2.png", BundleI18n.LarkEmotion.Emoji_Cake, "Lark_Emoji_Cake_0", "111", "CAKE"],
        ["emoji_party.png", BundleI18n.LarkEmotion.Emoji_Party, "Lark_Emoji_Party_0", "112", "PARTY"],
        ["emoji_eyesclosed.png", BundleI18n.LarkEmotion.Emoji_EyesClosed, "Lark_Emoji_EyesClosed_0", "113", "EYESCLOSED"],
        ["emoji_bomb.png", BundleI18n.LarkEmotion.Emoji_Bomb, "Lark_Emoji_Bomb_0", "114", "BOMB"],
        ["emoji_fireworks_v2.png", BundleI18n.LarkEmotion.Emoji_Fireworks, "Fireworks", "118", "FIREWORKS"],
        ["emoji_bull.png", BundleI18n.LarkEmotion.Emoji_Bull, "Bull", "119", "BULL"],
        ["emoji_calf.png", BundleI18n.LarkEmotion.Emoji_Calf, "Calf", "120", "CALF"],
        ["emoji_awesomen_v2.png", BundleI18n.LarkEmotion.Emoji_Awesomen, "Awesomen", "121", "AWESOMEN", "121_lark", "emoji_socool_v2.png"],
        ["emoji_twentytwentyone_v2.png", BundleI18n.LarkEmotion.Emoji_TwentyTwentyone, "2021", "122", "2021", "122_lark", "emoji_balloon_v2.png"],
        ["emoji_candiedhaws.png", BundleI18n.LarkEmotion.Emoji_Candiedhaws, "Candiedhaws", "123", "CANDIEDHAWS"],
        ["emoji_redpacket.png", BundleI18n.LarkEmotion.Emoji_Redpacket, "Redpacket", "124", "REDPACKET"],
        ["emoji_fortune.png", BundleI18n.LarkEmotion.Emoji_Fortune, "Fortune", "125", "FORTUNE", "125_lark", "emoji_gold.png"],
        ["emoji_luck.png", BundleI18n.LarkEmotion.Emoji_Luck, "Luck", "126", "LUCK"],
        ["emoji_firecracker_v3.png", BundleI18n.LarkEmotion.Emoji_Firecracker, "Firecracker", "127", "FIRECRACKER"],
        ["emoji_eatingfood_v2.png", BundleI18n.LarkEmotion.Emoji_EatingFood, "EatingFood", "128", "EatingFood"],
        ["emoji_typing.png", BundleI18n.LarkEmotion.Emoji_Typing, "Typing", "129", "Typing"],
        ["emoji_lemon_v2.png", BundleI18n.LarkEmotion.Emoji_Lemon, "Lemon", "130", "Lemon"],
        ["emoji_get_v3.png", BundleI18n.LarkEmotion.Emoji_Get, "Get", "131", "Get", "131_lark", "emoji_gotit_v1.png"],
        ["emoji_lgtm_v3.png", BundleI18n.LarkEmotion.Emoji_LGTM, "LGTM", "132", "LGTM"],
        ["emoji_drumstick.png", BundleI18n.LarkEmotion.Emoji_Drumstick, "Drumstick", "134", "Drumstick"],
        ["emoji_pepper.png", BundleI18n.LarkEmotion.Emoji_Pepper, "Pepper", "135", "Pepper"],
        ["emoji_bubbletea.png", BundleI18n.LarkEmotion.Emoji_BubbleTea, "BubbleTea", "136", "BubbleTea"],
        ["emoji_coffee.png", BundleI18n.LarkEmotion.Emoji_Coffee, "Coffee", "137", "Coffee"],
        ["emoji_yes_v2.png", BundleI18n.LarkEmotion.Emoji_Yes, "Yes", "138", "Yes"],
        ["emoji_no_v3.png", BundleI18n.LarkEmotion.Emoji_No, "No", "139", "No"],
        ["emoji_okr.png", BundleI18n.LarkEmotion.Emoji_OKR, "OKR", "140", "OKR"],
        ["emoji_checkmark.png", BundleI18n.LarkEmotion.Emoji_CheckMark, "CheckMark", "141", "CheckMark"],
        ["emoji_crossmark.png", BundleI18n.LarkEmotion.Emoji_CrossMark, "CrossMark", "142", "CrossMark"],
        ["emoji_minusone_v3.png", BundleI18n.LarkEmotion.Emoji_MinusOne, "MinusOne", "143", "MinusOne"],
        ["emoji_hundred.png", BundleI18n.LarkEmotion.Emoji_Hundred, "Hundred", "144", "Hundred"],
        ["emoji_pin.png", BundleI18n.LarkEmotion.Emoji_Pin, "Pin", "145", "Pin"],
        ["emoji_alarm.png", BundleI18n.LarkEmotion.Emoji_Alarm, "Alarm", "146", "Alarm"],
        ["emoji_loudspeaker.png", BundleI18n.LarkEmotion.Emoji_Loudspeaker, "Loudspeaker", "147", "Loudspeaker"],
        ["emoji_trophy.png", BundleI18n.LarkEmotion.Emoji_Trophy, "Trophy", "148", "Trophy"],
        ["emoji_fire.png", BundleI18n.LarkEmotion.Emoji_Fire, "Fire", "149", "Fire"],
        ["emoji_music_v2.png", BundleI18n.LarkEmotion.Emoji_Music, "Music", "150", "Music"],
        ["emoji_basketball_v2.png", BundleI18n.LarkEmotion.Emoji_Basketball, "Basketball", "151", "Basketball"],
        ["emoji_soccer_v2.png", BundleI18n.LarkEmotion.Emoji_Soccer, "Soccer", "152", "Soccer"],
        ["emoji_generaldonotdisturb_v3.png", BundleI18n.LarkEmotion.Emoji_GeneralDoNotDisturb, "GeneralDoNotDisturb", "153", "GeneralDoNotDisturb"],
        ["emoji_generalInmeetingbusy_v2.png", BundleI18n.LarkEmotion.Emoji_GeneralInMeetingBusy, "GeneralInMeetingBusy", "154", "GeneralInMeetingBusy"],
        ["emoji_coffee_v2.png", BundleI18n.LarkEmotion.Emoji_Coffee, "Coffee", "155", "Coffee"],
        ["emoji_generalbusinesstrip_v2.png", BundleI18n.LarkEmotion.Emoji_GeneralBusinessTrip, "GeneralBusinessTrip", "156", "GeneralBusinessTrip"],
        ["emoji_generalworkfromhome.png", BundleI18n.LarkEmotion.Emoji_GeneralWorkFromHome, "GeneralWorkFromHome", "157", "GeneralWorkFromHome"],
        ["emoji_statusenjoylife.png", BundleI18n.LarkEmotion.Emoji_StatusEnjoyLife, "StatusEnjoyLife", "158", "StatusEnjoyLife"],
        ["emoji_generaltravellingcar.png", BundleI18n.LarkEmotion.Emoji_GeneralTravellingCar, "GeneralTravellingCar", "159", "GeneralTravellingCar"],
        ["emoji_statusbus.png", BundleI18n.LarkEmotion.Emoji_StatusBus, "StatusBus", "160", "StatusBus"],
        ["emoji_statusinflight.png", BundleI18n.LarkEmotion.Emoji_StatusInFlight, "StatusInFlight", "161", "StatusInFlight"],
        ["emoji_generalsun.png", BundleI18n.LarkEmotion.Emoji_GeneralSun, "GeneralSun", "162", "GeneralSun"],
        ["emoji_generalmoonrest.png", BundleI18n.LarkEmotion.Emoji_GeneralMoonRest, "GeneralMoonRest", "163", "GeneralMoonRest"],
        ["emoji_statusreading.png", BundleI18n.LarkEmotion.Emoji_StatusReading, "StatusReading", "164", "StatusReading"],
        ["emoji_status_privatemessage.png", BundleI18n.LarkEmotion.Emoji_Status_PrivateMessage, "Status_PrivateMessage", "165", "Status_PrivateMessage"],
        ["emoji_statusflashofInspiration.png", BundleI18n.LarkEmotion.Emoji_StatusFlashOfInspiration, "StatusFlashOfInspiration", "166", "StatusFlashOfInspiration"],
        ["emoji_twentytwentytwo.png", BundleI18n.LarkEmotion.Emoji_2022, "2022", "167", "2022"],
        // thumbsup skins
        ["emoji_mediumlightthumbsup_v2.png", BundleI18n.LarkEmotion.Emoji_Thumbsup, "MediumLightThumbsup", "168", "MediumLightThumbsup"],
        ["emoji_lightthumbsup_v2.png", BundleI18n.LarkEmotion.Emoji_Thumbsup, "LightThumbsup", "169", "LightThumbsup"],
        ["emoji_mediumthumbsup_v2.png", BundleI18n.LarkEmotion.Emoji_Thumbsup, "MediumThumbsup", "170", "MediumThumbsup"],
        ["emoji_mediumdarkthumbsup_v2.png", BundleI18n.LarkEmotion.Emoji_Thumbsup, "MediumDarkThumbsup", "171", "MediumDarkThumbsup"],
        ["emoji_darkthumbsup_v2.png", BundleI18n.LarkEmotion.Emoji_Thumbsup, "DarkThumbsup", "172", "DarkThumbsup"],
        ["emoji_thumbsup_v2.png", BundleI18n.LarkEmotion.Emoji_Thumbsup, "Lark_Emoji_Thumbsup_0", "52", "THUMBSUP"],
        // thanks skins
        ["emoji_mediumlightthanks_v2.png", BundleI18n.LarkEmotion.Emoji_Thanks, "MediumLightThanks", "173", "MediumLightThanks"],
        ["emoji_lightthanks_v2.png", BundleI18n.LarkEmotion.Emoji_Thanks, "LightThanks", "174", "LightThanks"],
        ["emoji_mediumthanks_v2.png", BundleI18n.LarkEmotion.Emoji_Thanks, "MediumThanks", "175", "MediumThanks"],
        ["emoji_mediumdarkthanks_v2.png", BundleI18n.LarkEmotion.Emoji_Thanks, "MediumDarkThanks", "176", "MediumDarkThanks"],
        ["emoji_darkthanks_v2.png", BundleI18n.LarkEmotion.Emoji_Thanks, "DarkThanks", "177", "DarkThanks"],
        ["emoji_thanks_v2.png", BundleI18n.LarkEmotion.Emoji_Thanks, "Lark_Emoji_Thanks_0", "54", "THANKS"],
        // fighton skins
        ["emoji_mediumlightfighton_v2.png", BundleI18n.LarkEmotion.Emoji_Fighting, "MediumLightFightOn", "178", "MediumLightFightOn"],
        ["emoji_lightfighton_v2.png", BundleI18n.LarkEmotion.Emoji_Fighting, "LightFightOn", "179", "LightFightOn"],
        ["emoji_mediumfighton_v2.png", BundleI18n.LarkEmotion.Emoji_Fighting, "MediumFightOn", "180", "MediumFightOn"],
        ["emoji_mediumdarkfighton_v2.png", BundleI18n.LarkEmotion.Emoji_Fighting, "MediumDarkFightOn", "181", "MediumDarkFightOn"],
        ["emoji_darkfighton_v2.png", BundleI18n.LarkEmotion.Emoji_Fighting, "DarkFightOn", "182", "DarkFightOn"],
        ["emoji_fighton_v2.png", BundleI18n.LarkEmotion.Emoji_Fighting, "Lark_Emoji_Fighting_0", "97", "MUSCLE"],
        // fingerheart skins
        ["emoji_mediumlightfingerheart_v2.png", BundleI18n.LarkEmotion.Emoji_FingerHeart, "MediumLightFingerHeart", "183", "MediumLightFingerHeart"],
        ["emoji_lightfingerheart_v2.png", BundleI18n.LarkEmotion.Emoji_FingerHeart, "LightFingerHeart", "184", "LightFingerHeart"],
        ["emoji_mediumfingerheart_v2.png", BundleI18n.LarkEmotion.Emoji_FingerHeart, "MediumFingerHeart", "185", "MediumFingerHeart"],
        ["emoji_mediumdarkfingerheart_v2.png", BundleI18n.LarkEmotion.Emoji_FingerHeart, "MediumDarkFingerHeart", "186", "MediumDarkFingerHeart"],
        ["emoji_darkfingerheart_v2.png", BundleI18n.LarkEmotion.Emoji_FingerHeart, "DarkFingerHeart", "187", "DarkFingerHeart"],
        ["emoji_fingerheart_v2.png", BundleI18n.LarkEmotion.Emoji_FingerHeart, "Lark_Emoji_FingerHeart_0", "96", "FINGERHEART"],
        // applaud skins
        ["emoji_mediumlightapplaud_v2.png", BundleI18n.LarkEmotion.Emoji_Applaud, "MediumLightApplaud", "188", "MediumLightApplaud"],
        ["emoji_lightapplaud_v2.png", BundleI18n.LarkEmotion.Emoji_Applaud, "LightApplaud", "189", "LightApplaud"],
        ["emoji_mediumapplaud_v2.png", BundleI18n.LarkEmotion.Emoji_Applaud, "MediumApplaud", "190", "MediumApplaud"],
        ["emoji_mediumdarkapplaud_v2.png", BundleI18n.LarkEmotion.Emoji_Applaud, "MediumDarkApplaud", "191", "MediumDarkApplaud"],
        ["emoji_darkapplaud_v2.png", BundleI18n.LarkEmotion.Emoji_Applaud, "DarkApplaud", "192", "DarkApplaud"],
        ["emoji_applaud_v2.png", BundleI18n.LarkEmotion.Emoji_Applaud, "Lark_Emoji_Applaud_0", "53", "APPLAUSE"],
        // fistbump skins
        ["emoji_mediumlightfistbump_v2.png", BundleI18n.LarkEmotion.Emoji_FistBump, "MediumLightFistBump", "193", "MediumLightFistBump"],
        ["emoji_lightfistbump_v2.png", BundleI18n.LarkEmotion.Emoji_FistBump, "LightFistBump", "194", "LightFistBump"],
        ["emoji_mediumfistbump_v2.png", BundleI18n.LarkEmotion.Emoji_FistBump, "MediumFistBump", "195", "MediumFistBump"],
        ["emoji_mediumdarkfistbump_v2.png", BundleI18n.LarkEmotion.Emoji_FistBump, "MediumDarkFistBump", "196", "MediumDarkFistBump"],
        ["emoji_darkfistbump_v2.png", BundleI18n.LarkEmotion.Emoji_FistBump, "DarkFistBump", "197", "DarkFistBump"],
        ["emoji_fistbump_v2.png", BundleI18n.LarkEmotion.Emoji_FistBump, "Lark_Emoji_FistBump_0", "98", "FISTBUMP"],
        // highfive skins
        ["emoji_mediumlighthighfive_v2.png", BundleI18n.LarkEmotion.Emoji_HighFive, "MediumLightHighFive", "198", "MediumLightHighFive"],
        ["emoji_lighthighfive_v2.png", BundleI18n.LarkEmotion.Emoji_HighFive, "LightHighFive", "199", "LightHighFive"],
        ["emoji_mediumhighfive_v2.png", BundleI18n.LarkEmotion.Emoji_HighFive, "MediumHighFive", "200", "MediumHighFive"],
        ["emoji_mediumdarkhighfive_v2.png", BundleI18n.LarkEmotion.Emoji_HighFive, "MediumDarkHighFive", "201", "MediumDarkHighFive"],
        ["emoji_darkhighfive_v2.png", BundleI18n.LarkEmotion.Emoji_HighFive, "DarkHighFive", "202", "DarkHighFive"],
        ["emoji_highfive_v2.png", BundleI18n.LarkEmotion.Emoji_HighFive, "Lark_Emoji_HighFive_0", "100", "HIGHFIVE"],
        // click skins
        ["emoji_mediumlightclick_v2.png", BundleI18n.LarkEmotion.Emoji_UpperLeft, "MediumLightClick", "203", "MediumLightClick"],
        ["emoji_lightclick_v2.png", BundleI18n.LarkEmotion.Emoji_UpperLeft, "LightClick", "204", "LightClick"],
        ["emoji_mediumclick_v2.png", BundleI18n.LarkEmotion.Emoji_UpperLeft, "MediumClick", "205", "MediumClick"],
        ["emoji_mediumdarkclick_v2.png", BundleI18n.LarkEmotion.Emoji_UpperLeft, "MediumDarkClick", "206", "MediumDarkClick"],
        ["emoji_darkclick_v2.png", BundleI18n.LarkEmotion.Emoji_UpperLeft, "DarkClick", "207", "DarkClick"],
        ["emoji_click_v2.png", BundleI18n.LarkEmotion.Emoji_UpperLeft, "Lark_Emoji_UpperLeft_0", "101", "UPPERLEFT"],
        // thumbsdown skins
        ["emoji_mediumlightthumbsdown_v2.png", BundleI18n.LarkEmotion.Emoji_ThumbsDown, "MediumLightThumbsDown", "208", "MediumLightThumbsDown"],
        ["emoji_lightthumbsdown_v2.png", BundleI18n.LarkEmotion.Emoji_ThumbsDown, "LightThumbsDown", "209", "LightThumbsDown"],
        ["emoji_mediumthumbsdown_v2.png", BundleI18n.LarkEmotion.Emoji_ThumbsDown, "MediumThumbsDown", "210", "MediumThumbsDown"],
        ["emoji_mediumdarkthumbsdown_v2.png", BundleI18n.LarkEmotion.Emoji_ThumbsDown, "MediumDarkThumbsDown", "211", "MediumDarkThumbsDown"],
        ["emoji_darkthumbsdown_v2.png", BundleI18n.LarkEmotion.Emoji_ThumbsDown, "DarkThumbsDown", "212", "DarkThumbsDown"],
        ["emoji_thumbsdown_v2.png", BundleI18n.LarkEmotion.Emoji_ThumbsDown, "ThumbsDown", "133", "ThumbsDown"],
        // salute skins
        ["emoji_mediumlightsalute_v2.png", BundleI18n.LarkEmotion.Emoji_Salute, "MediumLightSalute", "213", "MediumLightSalute"],
        ["emoji_lightsalute_v2.png", BundleI18n.LarkEmotion.Emoji_Salute, "LightSalute", "214", "LightSalute"],
        ["emoji_mediumsalute_v2.png", BundleI18n.LarkEmotion.Emoji_Salute, "MediumSalute", "215", "MediumSalute"],
        ["emoji_mediumdarksalute_v2.png", BundleI18n.LarkEmotion.Emoji_Salute, "MediumDarkSalute", "216", "MediumDarkSalute"],
        ["emoji_darksalute_v2.png", BundleI18n.LarkEmotion.Emoji_Salute, "DarkSalute", "217", "DarkSalute"],
        ["emoji_salute_v2.png", BundleI18n.LarkEmotion.Emoji_Salute, "Salute", "115", "SALUTE"],
        // shake skins
        ["emoji_mediumlightshake_v2.png", BundleI18n.LarkEmotion.Emoji_Shake, "MediumLightShake", "218", "MediumLightShake"],
        ["emoji_lightshake_v2.png", BundleI18n.LarkEmotion.Emoji_Shake, "LightShake", "219", "LightShake"],
        ["emoji_mediumshake_v2.png", BundleI18n.LarkEmotion.Emoji_Shake, "MediumShake", "220", "MediumShake"],
        ["emoji_mediumdarkshake_v2.png", BundleI18n.LarkEmotion.Emoji_Shake, "MediumDarkShake", "221", "MediumDarkShake"],
        ["emoji_darkshake_v2.png", BundleI18n.LarkEmotion.Emoji_Shake, "DarkShake", "222", "DarkShake"],
        ["emoji_shake_v2.png", BundleI18n.LarkEmotion.Emoji_Shake, "Lark_Emoji_Shake_0", "102", "SHAKE"],
        // wavinghand skins
        ["emoji_wavinghand_v1.png", BundleI18n.LarkEmotion.Emoji_WavingHand, "WavingHand", "260", "WavingHand"],
        ["emoji_mediumlightwavinghand_v1.png", BundleI18n.LarkEmotion.Emoji_WavingHand, "MediumlightWavingHand", "261", "MediumlightWavingHand"],
        ["emoji_lightwavinghand_v1.png", BundleI18n.LarkEmotion.Emoji_WavingHand, "LightWavingHand", "262", "LightWavingHand"],
        ["emoji_mediumwavinghand_v1.png", BundleI18n.LarkEmotion.Emoji_WavingHand, "MediumWavingHand", "263", "MediumWavingHand"],
        ["emoji_mediumdarkwavinghand_v1.png", BundleI18n.LarkEmotion.Emoji_WavingHand, "MediumdarkWavingHand", "264", "MediumdarkWavingHand"],
        ["emoji_darkwavinghand_v1.png", BundleI18n.LarkEmotion.Emoji_WavingHand, "DarkWavingHand", "265", "DarkWavingHand"],
        // others
        ["emoji_xmastree.png", BundleI18n.LarkEmotion.Emoji_XmasTree, "XmasTree", "223", "XmasTree"],
        ["emoji_snowman.png", BundleI18n.LarkEmotion.Emoji_Snowman, "Snowman", "224", "Snowman"],
        ["emoji_xmashat.png", BundleI18n.LarkEmotion.Emoji_XmasHat, "XmasHat", "225", "XmasHat"],
        ["emoji_onit_v1.png", BundleI18n.LarkEmotion.Emoji_OnIt, "OnIt", "226", "OnIt"],
        ["emoji_onesecond.png", BundleI18n.LarkEmotion.Emoji_OneSecond, "OneSecond", "227", "OneSecond"],
        ["emoji_sigh.png", BundleI18n.LarkEmotion.Emoji_Sigh, "Sigh", "228", "Sigh"],
        ["emoji_roarforyou.png", BundleI18n.LarkEmotion.Emoji_RoarForYou, "RoarForYou", "229", "RoarForYou"],
        ["emoji_stickyriceballs.png", BundleI18n.LarkEmotion.Emoji_StickyRiceBalls, "StickyRiceBalls", "230", "StickyRiceBalls"],
        ["emoji_mememe.png", BundleI18n.LarkEmotion.Emoji_MeMeMe, "MeMeMe", "231", "MeMeMe"],
        // youarethebest skins
        ["emoji_youarethebest.png", BundleI18n.LarkEmotion.Emoji_YouAreTheBest, "YouAreTheBest", "232", "YouAreTheBest"],
        ["emoji_mediumlightyouarethebest_v1.png", BundleI18n.LarkEmotion.Emoji_YouAreTheBest, "MediumlightYouAreTheBest", "266", "MediumlightYouAreTheBest"],
        ["emoji_lightyouarethebest_v1.png", BundleI18n.LarkEmotion.Emoji_YouAreTheBest, "LightYouAreTheBest", "267", "LightYouAreTheBest"],
        ["emoji_mediumyouarethebest_v1.png", BundleI18n.LarkEmotion.Emoji_YouAreTheBest, "MediumYouAreTheBest", "269", "MediumYouAreTheBest"],
        ["emoji_mediumdarkyouarethebest_v1.png", BundleI18n.LarkEmotion.Emoji_YouAreTheBest, "MediumdarkYouAreTheBest", "270", "MediumdarkYouAreTheBest"],
        ["emoji_darkyouarethebest_v1.png", BundleI18n.LarkEmotion.Emoji_YouAreTheBest, "DarkYouAreTheBest", "271", "DarkYouAreTheBest"],
        // others
        ["emoji_onleavestatus.png", BundleI18n.LarkEmotion.Emoji_GeneralVacation, "GeneralVacation", "233", "GeneralVacation"],
        ["emoji_mooncake_v2.png", BundleI18n.LarkEmotion.Emoji_Mooncake, "Mooncake", "242", "Mooncake"],
        ["emoji_moonrabbit_v2.png", BundleI18n.LarkEmotion.Emoji_MoonRabbit, "MoonRabbit", "243", "MoonRabbit"],
        ["emoji_partying_v1.png", BundleI18n.LarkEmotion.Emoji_Partying, "Partying", "244", "Partying"],
        ["emoji_gogogo_v4.png", BundleI18n.LarkEmotion.Emoji_GoGoGo, "GoGoGo", "245", "GoGoGo"],
        ["emoji_tv_v1.png", BundleI18n.LarkEmotion.Emoji_TV, "TV", "246", "TV"],
        ["emoji_movie_v1.png", BundleI18n.LarkEmotion.Emoji_Movie, "Movie", "247", "Movie"],
        ["emoji_pumpkin_v1.png", BundleI18n.LarkEmotion.Emoji_Pumpkin, "Pumpkin", "248", "Pumpkin"],
        ["emoji_2023_v4.png", BundleI18n.LarkEmotion.Emoji_2023, "2023", "249", "2023"],
        ["emoji_jubilantrabbit_v1.png", BundleI18n.LarkEmotion.Emoji_JubilantRabbit, "JubilantRabbit", "250", "JubilantRabbit"],
        ["emoji_vrheadset_v1.png", BundleI18n.LarkEmotion.Emoji_VRHeadset, "VRHeadset", "251", "VRHeadset"],
        ["emoji_fullmoonface_v1.png.png", BundleI18n.LarkEmotion.Emoji_FullMoonFace, "FullMoonFace", "252", "FullMoonFace"],
        ["emoji_coldsweat_v1.png", BundleI18n.LarkEmotion.Emoji_ColdSweat, "ColdSweat", "253", "ColdSweat"],
        ["emoji_delighted_v1.png", BundleI18n.LarkEmotion.Emoji_Delighted, "Delighted", "254", "Delighted"],
        ["emoji_beamingface_v1.png", BundleI18n.LarkEmotion.Emoji_BeamingFace, "BeamingFace", "255", "BeamingFace"],
        ["emoji_thanksface_v1.png", BundleI18n.LarkEmotion.Emoji_ThanksFace, "ThanksFace", "256", "ThanksFace"],
        ["emoji_saluteface_v1.png", BundleI18n.LarkEmotion.Emoji_SaluteFace, "SaluteFace", "257", "SaluteFace"],
        ["emoji_shrug_v1.png", BundleI18n.LarkEmotion.Emoji_Shrug, "Shrug", "258", "Shrug"],
        ["emoji_clownface_v1.png", BundleI18n.LarkEmotion.Emoji_ClownFace, "ClownFace", "259", "ClownFace"],
        ["emoji_2024_v1.png", BundleI18n.LarkEmotion.Emoji_2024, "2024", "272", "2024"],
        ["emoji_happydragon_v3.png", BundleI18n.LarkEmotion.Emoji_HappyDragon, "HappyDragon", "273", "HappyDragon"],
        // lark values
        ["emoji_pursueultimate_v2.png", BundleI18n.LarkEmotion.Emoji_PursueUltimate, "PursueUltimate", "234", "PursueUltimate", "235", "emoji_pursueultimate_en.png"],
        ["emoji_customersuccess_v2.png", BundleI18n.LarkEmotion.Emoji_CustomerSuccess, "CustomerSuccess", "236", "CustomerSuccess", "237", "emoji_customersuccess_en.png"],
        ["emoji_bereliableandtakeownership.png", BundleI18n.LarkEmotion.Emoji_BeReliableAndTakeOwnership, "Responsible", "238", "Responsible", "239", "emoji_bereliableandtakeownership_en.png"],
        ["emoji_bereliableandtakeownership.png", BundleI18n.LarkEmotion.Emoji_BeReliableAndTakeOwnership, "Reliable", "238", "Reliable", "239", "emoji_bereliableandtakeownership_en.png"],
        ["emoji_bepatientandthinklongterm.png", BundleI18n.LarkEmotion.Emoji_BePatientAndThinkLongTerm, "Ambitious", "240", "Ambitious", "241", "emoji_bepatientandthinklongterm_en.png"],
        ["emoji_bepatientandthinklongterm.png", BundleI18n.LarkEmotion.Emoji_BePatientAndThinkLongTerm, "Patient", "240", "Patient", "241", "emoji_bepatientandthinklongterm_en.png"]
    ]
}
