disabled_rules:
  - cyclomatic_complexity
  - line_length
  - type_body_length
  - function_body_length
  - file_length
  - orphaned_doc_comment
  - for_where
  - multiple_closures_with_trailing_closure
  - nesting
  - comment_spacing
  - todo
  - inclusive_language
  - opening_brace

function_parameter_count: 20
identifier_name:
  min_length: 1
  max_length: 100
  allowed_symbols: "_"
  excluded:
    - i
type_name:
  max_length: 50
  allowed_symbols: "_"
  excluded:
    - lk
large_tuple: 3
vertical_whitespace:
  max_empty_lines: 2
