//
//  OpenPluginShowMsgCardDateTimePickerModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 25422
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginShowMsgCardDateTimePickerRequest
public final class OpenPluginShowMsgCardDateTimePickerRequest: OpenAPIBaseParams {
    
    /// description: 初始时间数据
    @OpenAPIOptionalParam(
            jsonKey: "initialDate")
    public var initialDate: String?
    
    /// description: 时间选择器的类型
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "tag")
    public var tag: String
    
    /// description: 消息id
    @OpenAPIOptionalParam(
            jsonKey: "msgID")
    public var msgID: String?
    
    /// description: 点击使用的id
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "actionID")
    public var actionID: String
    
    /// description: 确认面板相关信息
    @OpenAPIOptionalParam(
            jsonKey: "confirm")
    public var confirm: ConfirmObject?
    
    /// description: 组件Id
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "elementID")
    public var elementID: String
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_initialDate, _tag, _msgID, _actionID, _confirm, _elementID]
    }

    // MARK: ConfirmObject
    public final class ConfirmObject: OpenAPIBaseParams {

        /// description: 面板的title
        @OpenAPIOptionalParam(
            jsonKey: "title")
        public var title: String?

        /// description: 面板的text
        @OpenAPIOptionalParam(
            jsonKey: "text")
        public var text: String?

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_title, _text]
        }
    }
}
