//
//  UDColor+Store.swift
//  UniverseDesignColor
//
//  Created by dongwei.1615 on 2023年06月09日 14:50:17.
//  ！！本文件由脚本生成，如需改动，请修改 colorBase.py 脚本！！
//

import Foundation
import LKLoadable

extension UDColor {
    // swiftlint:disable all
    static func getToken() -> [UDColor.Name: UIColor] {
        var store: [UDColor.Name: UIColor] = [:]
        SwiftLoadable.startOnlyOnce(key: "UniverseDesignColor_UDColor_registToken")

        if UIDevice.current.userInterfaceIdiom == .pad {
            store[UDColor.Name("bg-base")] = UDColor.N100 & UDColor.rgb(0x171717)
        } else {
            store[UDColor.Name("bg-base")] = UDColor.N100 & UDColor.N00
        }
        store[UDColor.Name("bg-body")] = UDColor.N00 & UDColor.N50
        store[UDColor.Name("bg-body-overlay")] = UDColor.N50 & UDColor.N100
        store[UDColor.Name("bg-content-base")] = UDColor.rgb(0xF8F9FA) & UDColor.rgb(0x121212)
        store[UDColor.Name("bg-filler")] = UDColor.N200
        store[UDColor.Name("bg-float")] = UDColor.N00 & UDColor.N100
        store[UDColor.Name("bg-float-base")] = UDColor.N100 & UDColor.N50
        store[UDColor.Name("bg-float-overlay")] = UDColor.N50 & UDColor.N200
        store[UDColor.Name("bg-float-push")] = UDColor.N00.withAlphaComponent(0.8) & UDColor.N100.withAlphaComponent(0.8)
        store[UDColor.Name("bg-mask")] = UDColor.rgb(0x000000).withAlphaComponent(0.55) & UDColor.rgb(0x000000).withAlphaComponent(0.6)
        store[UDColor.Name("bg-pricolor")] = UDColor.primaryPri400
        store[UDColor.Name("bg-sub-navigation")] = UDColor.bgBodyOverlay & UDColor.rgb(0x262626)
        store[UDColor.Name("bg-text-selection")] = UDColor.B600.withAlphaComponent(0.3)
        store[UDColor.Name("bg-tips")] = UDColor.N900 & UDColor.N350
        store[UDColor.Name("fill-active")] = UDColor.primaryFillTransparent02
        store[UDColor.Name("fill-disabled")] = UDColor.N400
        store[UDColor.Name("fill-focus")] = UDColor.N900.withAlphaComponent(0.12)
        store[UDColor.Name("fill-hover")] = UDColor.N900.withAlphaComponent(0.05)
        store[UDColor.Name("fill-img-mask")] = UDColor.N00.withAlphaComponent(0.0) & UDColor.rgb(0x000000).withAlphaComponent(0.12)
        store[UDColor.Name("fill-loading-mask")] = UDColor.N00.withAlphaComponent(0.6)
        store[UDColor.Name("fill-pressed")] = UDColor.N900.withAlphaComponent(0.12)
        store[UDColor.Name("fill-selected")] = UDColor.primaryFillTransparent01
        store[UDColor.Name("fill-tag")] = UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("function-danger-100")] = UDColor.R100
        store[UDColor.Name("function-danger-200")] = UDColor.R200
        store[UDColor.Name("function-danger-300")] = UDColor.R300
        store[UDColor.Name("function-danger-350")] = UDColor.R350
        store[UDColor.Name("function-danger-400")] = UDColor.R400
        store[UDColor.Name("function-danger-50")] = UDColor.R50
        store[UDColor.Name("function-danger-500")] = UDColor.R500
        store[UDColor.Name("function-danger-600")] = UDColor.R600
        store[UDColor.Name("function-danger-700")] = UDColor.R700
        store[UDColor.Name("function-danger-800")] = UDColor.R800
        store[UDColor.Name("function-danger-900")] = UDColor.R900
        store[UDColor.Name("function-danger-on-danger-fill")] = UDColor.staticWhite
        store[UDColor.Name("function-danger-content-default")] = UDColor.functionDanger400 & UDColor.functionDanger500
        store[UDColor.Name("function-danger-content-hover")] = UDColor.functionDanger350 & UDColor.functionDanger400
        store[UDColor.Name("function-danger-content-pressed")] = UDColor.functionDanger500 & UDColor.functionDanger600
        store[UDColor.Name("function-danger-content-loading")] = UDColor.functionDanger300
        store[UDColor.Name("function-danger-fill-default")] = UDColor.functionDanger400
        store[UDColor.Name("function-danger-fill-hover")] = UDColor.functionDanger350
        store[UDColor.Name("function-danger-fill-pressed")] = UDColor.functionDanger500
        store[UDColor.Name("function-danger-fill-loading")] = UDColor.functionDanger300
        store[UDColor.Name("function-danger-fill-solid-01")] = UDColor.functionDanger50
        store[UDColor.Name("function-danger-fill-solid-02")] = UDColor.functionDanger100
        store[UDColor.Name("function-danger-fill-solid-03")] = UDColor.functionDanger200
        store[UDColor.Name("function-danger-fill-transparent-01")] = UDColor.functionDanger500.withAlphaComponent(0.1) & UDColor.functionDanger500.withAlphaComponent(0.15)
        store[UDColor.Name("function-danger-fill-transparent-02")] = UDColor.functionDanger500.withAlphaComponent(0.15) & UDColor.functionDanger500.withAlphaComponent(0.2)
        store[UDColor.Name("function-danger-fill-transparent-03")] = UDColor.functionDanger500.withAlphaComponent(0.2) & UDColor.functionDanger500.withAlphaComponent(0.3)
        store[UDColor.Name("text-caption")] = UDColor.N600
        store[UDColor.Name("function-info-100")] = UDColor.B100
        store[UDColor.Name("function-info-200")] = UDColor.B200
        store[UDColor.Name("function-info-300")] = UDColor.B300
        store[UDColor.Name("function-info-350")] = UDColor.B350
        store[UDColor.Name("function-info-400")] = UDColor.B400
        store[UDColor.Name("function-info-50")] = UDColor.B50
        store[UDColor.Name("function-info-500")] = UDColor.B500
        store[UDColor.Name("function-info-600")] = UDColor.B600
        store[UDColor.Name("function-info-700")] = UDColor.B700
        store[UDColor.Name("function-info-800")] = UDColor.B800
        store[UDColor.Name("function-info-900")] = UDColor.B900
        store[UDColor.Name("function-info-on-info-fill")] = UDColor.staticWhite
        store[UDColor.Name("function-info-content-default")] = UDColor.functionInfo600 & UDColor.functionInfo500
        store[UDColor.Name("function-info-content-hover")] = UDColor.functionInfo500 & UDColor.functionInfo400
        store[UDColor.Name("function-info-content-pressed")] = UDColor.functionInfo700 & UDColor.functionInfo600
        store[UDColor.Name("function-info-content-loading")] = UDColor.functionInfo300
        store[UDColor.Name("function-info-fill-default")] = UDColor.functionInfo600 & UDColor.functionInfo400
        store[UDColor.Name("function-info-fill-hover")] = UDColor.functionInfo500 & UDColor.functionInfo350
        store[UDColor.Name("function-info-fill-pressed")] = UDColor.functionInfo700 & UDColor.functionInfo500
        store[UDColor.Name("function-info-fill-loading")] = UDColor.functionInfo300
        store[UDColor.Name("function-info-fill-solid-01")] = UDColor.functionInfo50
        store[UDColor.Name("function-info-fill-solid-02")] = UDColor.functionInfo100
        store[UDColor.Name("function-info-fill-solid-03")] = UDColor.functionInfo200
        store[UDColor.Name("function-info-fill-transparent-01")] = UDColor.functionInfo600.withAlphaComponent(0.1) & UDColor.functionInfo500.withAlphaComponent(0.15)
        store[UDColor.Name("function-info-fill-transparent-02")] = UDColor.functionInfo600.withAlphaComponent(0.15) & UDColor.functionInfo500.withAlphaComponent(0.2)
        store[UDColor.Name("function-info-fill-transparent-03")] = UDColor.functionInfo600.withAlphaComponent(0.2) & UDColor.functionInfo500.withAlphaComponent(0.3)
        store[UDColor.Name("function-success-100")] = UDColor.G100
        store[UDColor.Name("function-success-200")] = UDColor.G200
        store[UDColor.Name("function-success-300")] = UDColor.G300
        store[UDColor.Name("function-success-350")] = UDColor.G350
        store[UDColor.Name("function-success-400")] = UDColor.G400
        store[UDColor.Name("function-success-50")] = UDColor.G50
        store[UDColor.Name("function-success-500")] = UDColor.G500
        store[UDColor.Name("function-success-600")] = UDColor.G600
        store[UDColor.Name("function-success-700")] = UDColor.G700
        store[UDColor.Name("function-success-800")] = UDColor.G800
        store[UDColor.Name("function-success-900")] = UDColor.G900
        store[UDColor.Name("function-success-on-success-fill")] = UDColor.staticWhite
        store[UDColor.Name("function-success-content-default")] = UDColor.functionSuccess400 & UDColor.functionSuccess600
        store[UDColor.Name("function-success-content-hover")] = UDColor.functionSuccess350 & UDColor.functionSuccess500
        store[UDColor.Name("function-success-content-pressed")] = UDColor.functionSuccess500 & UDColor.functionSuccess700
        store[UDColor.Name("function-success-content-loading")] = UDColor.functionSuccess300
        store[UDColor.Name("function-success-fill-default")] = UDColor.functionSuccess350 & UDColor.functionSuccess500
        store[UDColor.Name("function-success-fill-hover")] = UDColor.functionSuccess300 & UDColor.functionSuccess400
        store[UDColor.Name("function-success-fill-pressed")] = UDColor.functionSuccess400 & UDColor.functionSuccess600
        store[UDColor.Name("function-success-fill-loading")] = UDColor.functionSuccess300
        store[UDColor.Name("function-success-fill-solid-01")] = UDColor.functionSuccess50
        store[UDColor.Name("function-success-fill-solid-02")] = UDColor.functionSuccess100
        store[UDColor.Name("function-success-fill-solid-03")] = UDColor.functionSuccess200
        store[UDColor.Name("function-success-fill-transparent-01")] = UDColor.functionSuccess350.withAlphaComponent(0.1) & UDColor.functionSuccess500.withAlphaComponent(0.15)
        store[UDColor.Name("function-success-fill-transparent-02")] = UDColor.functionSuccess350.withAlphaComponent(0.15) & UDColor.functionSuccess500.withAlphaComponent(0.2)
        store[UDColor.Name("function-success-fill-transparent-03")] = UDColor.functionSuccess350.withAlphaComponent(0.2) & UDColor.functionSuccess500.withAlphaComponent(0.3)
        store[UDColor.Name("function-warning-100")] = UDColor.O100
        store[UDColor.Name("function-warning-200")] = UDColor.O200
        store[UDColor.Name("function-warning-300")] = UDColor.O300
        store[UDColor.Name("function-warning-350")] = UDColor.O350
        store[UDColor.Name("function-warning-400")] = UDColor.O400
        store[UDColor.Name("function-warning-50")] = UDColor.O50
        store[UDColor.Name("function-warning-500")] = UDColor.O500
        store[UDColor.Name("function-warning-600")] = UDColor.O600
        store[UDColor.Name("function-warning-700")] = UDColor.O700
        store[UDColor.Name("function-warning-800")] = UDColor.O800
        store[UDColor.Name("function-warning-900")] = UDColor.O900
        store[UDColor.Name("icon-disabled")] = UDColor.N400
        store[UDColor.Name("icon-n1")] = UDColor.N800
        store[UDColor.Name("icon-n2")] = UDColor.N600
        store[UDColor.Name("icon-n3")] = UDColor.N500
        store[UDColor.Name("line-border-card")] = UDColor.N300 & UDColor.N900.withAlphaComponent(0.15)
        store[UDColor.Name("line-border-component")] = UDColor.N350 & UDColor.N900.withAlphaComponent(0.2)
        store[UDColor.Name("line-divider-default")] = UDColor.N900.withAlphaComponent(0.15) & UDColor.N650.withAlphaComponent(0.15)
        store[UDColor.Name("line-divider-module")] = UDColor.N900.withAlphaComponent(0.15) & UDColor.staticBlack
        store[UDColor.Name("primary-pri-100")] = UDColor.B100
        store[UDColor.Name("primary-pri-200")] = UDColor.B200
        store[UDColor.Name("primary-pri-300")] = UDColor.B300
        store[UDColor.Name("primary-pri-350")] = UDColor.B350
        store[UDColor.Name("primary-pri-400")] = UDColor.B400
        store[UDColor.Name("primary-pri-50")] = UDColor.B50
        store[UDColor.Name("primary-pri-500")] = UDColor.B500
        store[UDColor.Name("primary-pri-600")] = UDColor.B600
        store[UDColor.Name("primary-pri-700")] = UDColor.B700
        store[UDColor.Name("primary-pri-800")] = UDColor.B800
        store[UDColor.Name("primary-pri-900")] = UDColor.B900
        store[UDColor.Name("shadow-default")] = UDColor.N900 & UDColor.rgb(0x000000)
        store[UDColor.Name("shadow-default-lg")] = UDColor.N900.withAlphaComponent(0.08) & UDColor.rgb(0x000000).withAlphaComponent(0.24)
        store[UDColor.Name("shadow-default-md")] = UDColor.N900.withAlphaComponent(0.1) & UDColor.rgb(0x000000).withAlphaComponent(0.28)
        store[UDColor.Name("shadow-default-sm")] = UDColor.N900.withAlphaComponent(0.12) & UDColor.rgb(0x000000).withAlphaComponent(0.32)
        store[UDColor.Name("shadow-pri")] = UDColor.primaryPri600 & UDColor.rgb(0x245BDB)
        store[UDColor.Name("shadow-pri-lg")] = UDColor.primaryPri500.withAlphaComponent(0.24) & UDColor.primaryPri200.withAlphaComponent(0.48)
        store[UDColor.Name("shadow-pri-md")] = UDColor.primaryPri600.withAlphaComponent(0.24) & UDColor.primaryPri200.withAlphaComponent(0.48)
        store[UDColor.Name("static-black")] = UDColor.rgb(0x000000)
        store[UDColor.Name("static-white")] = UDColor.rgb(0xFFFFFF)
        store[UDColor.Name("static-white-hover")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.1)
        store[UDColor.Name("static-white-pressed")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.2)
        store[UDColor.Name("text-disabled")] = UDColor.N400
        store[UDColor.Name("text-link-disabled")] = UDColor.N400
        store[UDColor.Name("text-link-hover")] = UDColor.B500 & UDColor.B400
        store[UDColor.Name("text-link-loading")] = UDColor.B300
        store[UDColor.Name("text-link-normal")] = UDColor.B600 & UDColor.B500
        store[UDColor.Name("text-link-pressed")] = UDColor.B700 & UDColor.B600
        store[UDColor.Name("text-placeholder")] = UDColor.N500
        store[UDColor.Name("text-title")] = UDColor.N900
        store[UDColor.Name("N00-10")] = UDColor.N00.withAlphaComponent(0.1)
        store[UDColor.Name("N00-15")] = UDColor.N00.withAlphaComponent(0.15)
        store[UDColor.Name("N00-20")] = UDColor.N00.withAlphaComponent(0.2)
        store[UDColor.Name("N00-30")] = UDColor.N00.withAlphaComponent(0.3)
        store[UDColor.Name("N00-40")] = UDColor.N00.withAlphaComponent(0.4)
        store[UDColor.Name("N00-5")] = UDColor.N00.withAlphaComponent(0.05)
        store[UDColor.Name("N00-50")] = UDColor.N00.withAlphaComponent(0.5)
        store[UDColor.Name("N00-60")] = UDColor.N00.withAlphaComponent(0.6)
        store[UDColor.Name("N00-70")] = UDColor.N00.withAlphaComponent(0.7)
        store[UDColor.Name("N00-80")] = UDColor.N00.withAlphaComponent(0.8)
        store[UDColor.Name("N00-90")] = UDColor.N00.withAlphaComponent(0.9)
        store[UDColor.Name("N900-10")] = UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("N900-15")] = UDColor.N900.withAlphaComponent(0.15)
        store[UDColor.Name("N900-20")] = UDColor.N900.withAlphaComponent(0.2)
        store[UDColor.Name("N900-30")] = UDColor.N900.withAlphaComponent(0.3)
        store[UDColor.Name("N900-40")] = UDColor.N900.withAlphaComponent(0.4)
        store[UDColor.Name("N900-5")] = UDColor.N900.withAlphaComponent(0.05)
        store[UDColor.Name("N900-50")] = UDColor.N900.withAlphaComponent(0.5)
        store[UDColor.Name("N900-60")] = UDColor.N900.withAlphaComponent(0.6)
        store[UDColor.Name("N900-70")] = UDColor.N900.withAlphaComponent(0.7)
        store[UDColor.Name("N900-80")] = UDColor.N900.withAlphaComponent(0.8)
        store[UDColor.Name("N900-90")] = UDColor.N900.withAlphaComponent(0.9)
        store[UDColor.Name("static-black-10")] = UDColor.rgb(0x000000).withAlphaComponent(0.1)
        store[UDColor.Name("static-black-15")] = UDColor.rgb(0x000000).withAlphaComponent(0.15)
        store[UDColor.Name("static-black-20")] = UDColor.rgb(0x000000).withAlphaComponent(0.2)
        store[UDColor.Name("static-black-30")] = UDColor.rgb(0x000000).withAlphaComponent(0.3)
        store[UDColor.Name("static-black-40")] = UDColor.rgb(0x000000).withAlphaComponent(0.4)
        store[UDColor.Name("static-black-5")] = UDColor.rgb(0x000000).withAlphaComponent(0.05)
        store[UDColor.Name("static-black-50")] = UDColor.rgb(0x000000).withAlphaComponent(0.5)
        store[UDColor.Name("static-black-60")] = UDColor.rgb(0x000000).withAlphaComponent(0.6)
        store[UDColor.Name("static-black-70")] = UDColor.rgb(0x000000).withAlphaComponent(0.7)
        store[UDColor.Name("static-black-80")] = UDColor.rgb(0x000000).withAlphaComponent(0.8)
        store[UDColor.Name("static-black-90")] = UDColor.rgb(0x000000).withAlphaComponent(0.9)
        store[UDColor.Name("static-white-10")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.1)
        store[UDColor.Name("static-white-15")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.15)
        store[UDColor.Name("static-white-20")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.2)
        store[UDColor.Name("static-white-30")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.3)
        store[UDColor.Name("static-white-40")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.4)
        store[UDColor.Name("static-white-5")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.05)
        store[UDColor.Name("static-white-50")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.5)
        store[UDColor.Name("static-white-60")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.6)
        store[UDColor.Name("static-white-70")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.7)
        store[UDColor.Name("static-white-80")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.8)
        store[UDColor.Name("static-white-90")] = UDColor.rgb(0xFFFFFF).withAlphaComponent(0.9)
        store[UDColor.Name("primary-on-primary-fill")] = UDColor.staticWhite
        store[UDColor.Name("primary-content-default")] = UDColor.primaryPri600 & UDColor.primaryPri500
        store[UDColor.Name("primary-content-hover")] = UDColor.primaryPri500 & UDColor.primaryPri400
        store[UDColor.Name("primary-content-pressed")] = UDColor.primaryPri700 & UDColor.primaryPri600
        store[UDColor.Name("primary-content-loading")] = UDColor.primaryPri300
        store[UDColor.Name("colorful-blue")] = UDColor.B500
        store[UDColor.Name("colorful-red")] = UDColor.R400 & UDColor.R500
        store[UDColor.Name("colorful-orange")] = UDColor.O350 & UDColor.O600
        store[UDColor.Name("colorful-yellow")] = UDColor.Y350 & UDColor.Y500
        store[UDColor.Name("colorful-green")] = UDColor.G350 & UDColor.G500
        store[UDColor.Name("colorful-wathet")] = UDColor.W350 & UDColor.W500
        store[UDColor.Name("colorful-indigo")] = UDColor.I500 & UDColor.I400
        store[UDColor.Name("colorful-purple")] = UDColor.P500 & UDColor.P400
        store[UDColor.Name("colorful-violet")] = UDColor.V500 & UDColor.V400
        store[UDColor.Name("colorful-carmine")] = UDColor.C400
        store[UDColor.Name("colorful-sunflower")] = UDColor.S350 & UDColor.S500
        store[UDColor.Name("colorful-turquoise")] = UDColor.T350 & UDColor.T500
        store[UDColor.Name("colorful-lime")] = UDColor.L350 & UDColor.L600
        store[UDColor.Name("colorful-neutral")] = UDColor.N500
        store[UDColor.Name("primary-fill-default")] = UDColor.primaryPri600 & UDColor.primaryPri400
        store[UDColor.Name("primary-fill-hover")] = UDColor.primaryPri500 & UDColor.primaryPri350
        store[UDColor.Name("primary-fill-pressed")] = UDColor.primaryPri700 & UDColor.primaryPri500
        store[UDColor.Name("primary-fill-loading")] = UDColor.primaryPri300
        store[UDColor.Name("primary-fill-solid-01")] = UDColor.primaryPri50
        store[UDColor.Name("primary-fill-solid-02")] = UDColor.primaryPri100
        store[UDColor.Name("primary-fill-solid-03")] = UDColor.primaryPri200
        store[UDColor.Name("primary-fill-transparent-01")] = UDColor.primaryPri600.withAlphaComponent(0.1) & UDColor.primaryPri500.withAlphaComponent(0.15)
        store[UDColor.Name("primary-fill-transparent-02")] = UDColor.primaryPri600.withAlphaComponent(0.15) & UDColor.primaryPri500.withAlphaComponent(0.2)
        store[UDColor.Name("primary-fill-transparent-03")] = UDColor.primaryPri600.withAlphaComponent(0.2) & UDColor.primaryPri500.withAlphaComponent(0.3)
        store[UDColor.Name("function-warning-on-warning-fill")] = UDColor.staticWhite
        store[UDColor.Name("function-warning-content-default")] = UDColor.functionWarning400 & UDColor.functionWarning600
        store[UDColor.Name("function-warning-content-hover")] = UDColor.functionWarning350 & UDColor.functionWarning500
        store[UDColor.Name("function-warning-content-pressed")] = UDColor.functionWarning500 & UDColor.functionWarning700
        store[UDColor.Name("function-warning-content-loading")] = UDColor.functionWarning300
        store[UDColor.Name("function-warning-fill-default")] = UDColor.functionWarning350 & UDColor.functionWarning600
        store[UDColor.Name("function-warning-fill-hover")] = UDColor.functionWarning300 & UDColor.functionWarning500
        store[UDColor.Name("function-warning-fill-pressed")] = UDColor.functionWarning400 & UDColor.functionWarning700
        store[UDColor.Name("function-warning-fill-loading")] = UDColor.functionWarning300
        store[UDColor.Name("function-warning-fill-solid-01")] = UDColor.functionWarning50
        store[UDColor.Name("function-warning-fill-solid-02")] = UDColor.functionWarning100
        store[UDColor.Name("function-warning-fill-solid-03")] = UDColor.functionWarning200
        store[UDColor.Name("function-warning-fill-transparent-01")] = UDColor.functionWarning400.withAlphaComponent(0.1) & UDColor.functionWarning600.withAlphaComponent(0.15)
        store[UDColor.Name("function-warning-fill-transparent-02")] = UDColor.functionWarning400.withAlphaComponent(0.15) & UDColor.functionWarning600.withAlphaComponent(0.2)
        store[UDColor.Name("function-warning-fill-transparent-03")] = UDColor.functionWarning400.withAlphaComponent(0.2) & UDColor.functionWarning600.withAlphaComponent(0.3)
        store[UDColor.Name("Vnext-bg-sub-navigation")] = UDColor.rgb(0xF5F5F5).withAlphaComponent(0.7) & UDColor.rgb(0x1E1E1E).withAlphaComponent(0.5)
        store[UDColor.Name("Vnext-bg-thirdly-navigation")] = UDColor.rgb(0xFCFCFC).withAlphaComponent(0.9) & UDColor.rgb(0x1A1A1A).withAlphaComponent(0.7)
        store[UDColor.Name("Vnext-bg-content-header")] = UDColor.rgb(0xFCFCFC) & UDColor.rgb(0x222222)
        store[UDColor.Name("illustration-blue-a")] = UDColor.B900 & UDColor.N700
        store[UDColor.Name("AI-cursor")] = UDColor.I600 & UDColor.I400
        store[UDColor.Name("illustration-blue-b")] = UDColor.B900 & UDColor.staticWhite.withAlphaComponent(0.4)
        store[UDColor.Name("illustration-blue-c")] = UDColor.B900 & UDColor.N400
        store[UDColor.Name("illustration-blue-d")] = UDColor.B900 & UDColor.B300
        store[UDColor.Name("illustration-blue-e")] = UDColor.B500
        store[UDColor.Name("illustration-neutral-a")] = UDColor.N00 & UDColor.N900
        store[UDColor.Name("illustration-neutral-b")] = UDColor.N00 & UDColor.N200
        store[UDColor.Name("illustration-neutral-c")] = UDColor.N400.withAlphaComponent(0.45) & UDColor.staticWhite.withAlphaComponent(0.3)
        store[UDColor.Name("illustration-neutral-d")] = UDColor.N500 & UDColor.staticWhite.withAlphaComponent(0.4)
        store[UDColor.Name("illustration-orange")] = UDColor.O350 & UDColor.O600
        store[UDColor.Name("illustration-red")] = UDColor.R400 & UDColor.R500
        store[UDColor.Name("illustration-static-black")] = UDColor.staticBlack
        store[UDColor.Name("illustration-static-white")] = UDColor.staticWhite
        store[UDColor.Name("illustration-turquoise")] = UDColor.T300 & UDColor.T700
        store[UDColor.Name("illustration-wathet")] = UDColor.W300 & UDColor.W700
        store[UDColor.Name("illustration-yellow")] = UDColor.Y350 & UDColor.Y500
        store[UDColor.Name("udtoken-block-view-inline-bg-nopermission")] = UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("udtoken-block-view-inline-bg-other")] = UDColor.primaryPri300.withAlphaComponent(0.18) & UDColor.primaryPri300.withAlphaComponent(0.35)
        store[UDColor.Name("udtoken-block-view-inline-bg-self")] = UDColor.primaryPri600
        store[UDColor.Name("udtoken-btn-ghost-bg")] = UDColor.N00.withAlphaComponent(0.0)
        store[UDColor.Name("udtoken-btn-pri-text-disabled")] = UDColor.staticWhite & UDColor.N900.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-btn-se-bg-danger-focus")] = UDColor.functionDangerFillSolid02 & UDColor.functionDangerFillTransparent02
        store[UDColor.Name("udtoken-btn-se-bg-danger-hover")] = UDColor.functionDangerFillSolid02 & UDColor.functionDangerFillTransparent02
        store[UDColor.Name("udtoken-btn-se-bg-danger-pressed")] = UDColor.functionDangerFillSolid03 & UDColor.functionDangerFillTransparent03
        store[UDColor.Name("udtoken-btn-se-bg-neutral-focus")] = UDColor.N100 & UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("udtoken-btn-se-bg-neutral-hover")] = UDColor.N100 & UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("udtoken-btn-se-bg-neutral-pressed")] = UDColor.N200 & UDColor.N900.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-btn-se-bg-pri-focus")] = UDColor.primaryFillSolid02 & UDColor.primaryFillTransparent02
        store[UDColor.Name("udtoken-btn-se-bg-pri-hover")] = UDColor.primaryFillSolid02 & UDColor.primaryFillTransparent02
        store[UDColor.Name("udtoken-btn-se-bg-pri-pressed")] = UDColor.primaryFillSolid03 & UDColor.primaryFillTransparent03
        store[UDColor.Name("udtoken-btn-text-bg-danger-focus")] = UDColor.functionDangerFillTransparent01 & UDColor.functionDangerFillTransparent02
        store[UDColor.Name("udtoken-btn-text-bg-danger-hover")] = UDColor.functionDangerFillTransparent01 & UDColor.functionDangerFillTransparent02
        store[UDColor.Name("udtoken-btn-text-bg-danger-pressed")] = UDColor.functionDangerFillTransparent03
        store[UDColor.Name("udtoken-btn-text-bg-neutral-focus")] = UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("udtoken-btn-text-bg-neutral-hover")] = UDColor.N900.withAlphaComponent(0.1)
        store[UDColor.Name("udtoken-btn-text-bg-neutral-pressed")] = UDColor.N900.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-btn-text-bg-pri-focus")] = UDColor.primaryFillTransparent01 & UDColor.primaryFillTransparent02
        store[UDColor.Name("udtoken-btn-text-bg-pri-hover")] = UDColor.primaryFillTransparent01 & UDColor.primaryFillTransparent02
        store[UDColor.Name("udtoken-btn-text-bg-pri-pressed")] = UDColor.primaryFillTransparent03
        store[UDColor.Name("udtoken-btn-selected-bg-danger-hover")] = UDColor.functionDangerFillSolid02 & UDColor.functionDangerFillTransparent03
        store[UDColor.Name("udtoken-btn-selected-bg-danger-normal")] = UDColor.functionDangerFillSolid01 & UDColor.functionDangerFillTransparent01
        store[UDColor.Name("udtoken-btn-selected-bg-danger-press")] = UDColor.functionDangerFillSolid03 & UDColor.functionDangerFillTransparent03
        store[UDColor.Name("udtoken-btn-selected-bg-neutral-hover")] = UDColor.N900.withAlphaComponent(0.1) & UDColor.N900.withAlphaComponent(0.12)
        store[UDColor.Name("udtoken-btn-selected-bg-neutral-normal")] = UDColor.N900.withAlphaComponent(0.06) & UDColor.N900.withAlphaComponent(0.08)
        store[UDColor.Name("udtoken-btn-selected-bg-neutral-press")] = UDColor.N900.withAlphaComponent(0.14) & UDColor.N900.withAlphaComponent(0.16)
        store[UDColor.Name("udtoken-btn-selected-bg-success-hover")] = UDColor.functionSuccessFillSolid02 & UDColor.functionSuccessFillTransparent02
        store[UDColor.Name("udtoken-btn-selected-bg-success-normal")] = UDColor.functionSuccessFillSolid01 & UDColor.functionSuccessFillTransparent01
        store[UDColor.Name("udtoken-btn-selected-bg-success-press")] = UDColor.functionSuccessFillSolid03 & UDColor.functionSuccessFillTransparent03
        store[UDColor.Name("udtoken-btn-selected-border-neutral")] = UDColor.N1000.withAlphaComponent(0.3) & UDColor.N1000.withAlphaComponent(0.5)
        store[UDColor.Name("udtoken-btn-selected-text-danger")] = UDColor.R600 & UDColor.R500
        store[UDColor.Name("udtoken-btn-selected-text-success")] = UDColor.G500
        store[UDColor.Name("udtoken-component-outlined-bg")] = UDColor.bgBody & UDColor.N00.withAlphaComponent(0.0)
        store[UDColor.Name("udtoken-component-text-disabled-loading")] = UDColor.N500
        store[UDColor.Name("udtoken-dropdown-button-divider")] = UDColor.N00.withAlphaComponent(0.5) & UDColor.lineBorderComponent
        store[UDColor.Name("udtoken-input-bg-disabled")] = UDColor.N200 & UDColor.N900.withAlphaComponent(0.12)
        store[UDColor.Name("udtoken-message-card-bg-blue")] = UDColor.B100
        store[UDColor.Name("udtoken-message-card-bg-carmine")] = UDColor.C100
        store[UDColor.Name("udtoken-message-card-bg-green")] = UDColor.G100
        store[UDColor.Name("udtoken-message-card-bg-indigo")] = UDColor.I100
        store[UDColor.Name("udtoken-message-card-bg-light-neutral")] = UDColor.N100 & UDColor.N200
        store[UDColor.Name("udtoken-message-card-bg-lime")] = UDColor.L100
        store[UDColor.Name("udtoken-message-card-bg-mask-general")] = UDColor.N00.withAlphaComponent(0.5) & UDColor.N00.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-message-card-bg-mask-special")] = UDColor.N00.withAlphaComponent(0.2) & UDColor.N00.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-message-card-bg-neutral")] = UDColor.N500 & UDColor.N300
        store[UDColor.Name("udtoken-message-card-bg-orange")] = UDColor.O100
        store[UDColor.Name("udtoken-message-card-bg-purple")] = UDColor.P100
        store[UDColor.Name("udtoken-message-card-bg-red")] = UDColor.R100
        store[UDColor.Name("udtoken-message-card-bg-turquoise")] = UDColor.T100
        store[UDColor.Name("udtoken-message-card-bg-violet")] = UDColor.V100
        store[UDColor.Name("udtoken-message-card-bg-wathet")] = UDColor.W100
        store[UDColor.Name("udtoken-message-card-bg-yellow")] = UDColor.Y100
        store[UDColor.Name("udtoken-message-card-text-blue")] = UDColor.B600 & UDColor.B700
        store[UDColor.Name("udtoken-message-card-text-carmine")] = UDColor.C600 & UDColor.C700
        store[UDColor.Name("udtoken-message-card-text-green")] = UDColor.G600 & UDColor.G700
        store[UDColor.Name("udtoken-message-card-text-indigo")] = UDColor.I600 & UDColor.I700
        store[UDColor.Name("udtoken-message-card-text-lime")] = UDColor.L600 & UDColor.L700
        store[UDColor.Name("udtoken-message-card-text-neutral")] = UDColor.N00 & UDColor.N650
        store[UDColor.Name("udtoken-message-card-text-orange")] = UDColor.O500 & UDColor.O700
        store[UDColor.Name("udtoken-message-card-text-purple")] = UDColor.P600 & UDColor.P700
        store[UDColor.Name("udtoken-message-card-text-red")] = UDColor.R600 & UDColor.R700
        store[UDColor.Name("udtoken-message-card-text-turquoise")] = UDColor.T600 & UDColor.T700
        store[UDColor.Name("udtoken-message-card-text-violet")] = UDColor.V600 & UDColor.V700
        store[UDColor.Name("udtoken-message-card-text-wathet")] = UDColor.W600 & UDColor.W700
        store[UDColor.Name("udtoken-message-card-text-yellow")] = UDColor.Y500 & UDColor.Y700
        store[UDColor.Name("udtoken-navigation-bar-resize-handle")] = UDColor.rgb(0x4599ff)
        store[UDColor.Name("udtoken-navigation-bar-tab-bg-black")] = UDColor.rgb(0x1c2435) & UDColor.rgb(0x0d0e12)
        store[UDColor.Name("udtoken-navigation-bar-tab-bg-blue")] = UDColor.rgb(0x1b429c) & UDColor.rgb(0x141c2a)
        store[UDColor.Name("udtoken-navigation-bar-tab-bg-gray")] = UDColor.rgb(0xe5e5e9) & UDColor.rgb(0x242424)
        store[UDColor.Name("udtoken-progress-bg")] = UDColor.N300 & UDColor.N900.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-quote-bar-bg")] = UDColor.N400
        store[UDColor.Name("udtoken-reaction-bg-grey")] = UDColor.N900.withAlphaComponent(0.05) & UDColor.rgb(0x101010)
        store[UDColor.Name("udtoken-reaction-bg-grey-float")] = UDColor.N900.withAlphaComponent(0.05) & UDColor.rgb(0x1f1f1f)
        store[UDColor.Name("udtoken-skeleton-bg")] = UDColor.N900.withAlphaComponent(0.08) & UDColor.rgb(0xf0f0f0).withAlphaComponent(0.08)
        store[UDColor.Name("udtoken-skeleton-fg")] = UDColor.N900.withAlphaComponent(0.05) & UDColor.rgb(0xf0f0f0).withAlphaComponent(0.05)
        store[UDColor.Name("udtoken-sliding-block-bg-disabled-loading")] = UDColor.N00 & UDColor.N500
        store[UDColor.Name("udtoken-steps-bg-hover")] = UDColor.primaryFillTransparent01
        store[UDColor.Name("udtoken-tab-pri-bg")] = UDColor.primaryFillTransparent03 & UDColor.primaryFillSolid03
        store[UDColor.Name("udtoken-tab-pri-text")] = UDColor.primaryContentDefault
        store[UDColor.Name("udtoken-tab-se-bg-unselected")] = UDColor.N900.withAlphaComponent(0.1) & UDColor.N900.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-table-bg-expand")] = UDColor.N100 & UDColor.N00
        store[UDColor.Name("udtoken-table-bg-grey")] = UDColor.N50 & UDColor.N100
        store[UDColor.Name("udtoken-table-bg-head")] = UDColor.N100 & UDColor.N200
        store[UDColor.Name("udtoken-table-bg-hover")] = UDColor.N200 & UDColor.N350
        store[UDColor.Name("udtoken-table-bg-pressed")] = UDColor.N300 & UDColor.N400
        store[UDColor.Name("udtoken-table-bg-selected")] = UDColor.primaryFillSolid01 & UDColor.primaryFillSolid02
        store[UDColor.Name("udtoken-tag-bg-blue")] = UDColor.B600.withAlphaComponent(0.2) & UDColor.B500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-blue-solid")] = UDColor.B200 & UDColor.B100
        store[UDColor.Name("udtoken-tag-bg-blue-default")] = UDColor.B600.withAlphaComponent(0.12)
        store[UDColor.Name("udtoken-tag-bg-blue-hover")] = UDColor.B600.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-blue-pressed")] = UDColor.B600.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-carmine")] = UDColor.C500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-carmine-solid")] = UDColor.C200 & UDColor.C100
        store[UDColor.Name("udtoken-tag-bg-carmine-hover")] = UDColor.C500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-green")] = UDColor.G350.withAlphaComponent(0.2) & UDColor.G500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-green-solid")] = UDColor.G200 & UDColor.G100
        store[UDColor.Name("udtoken-tag-bg-green-hover")] = UDColor.G350.withAlphaComponent(0.3) & UDColor.G500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-indigo")] = UDColor.I500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-indigo-solid")] = UDColor.I200 & UDColor.I100
        store[UDColor.Name("udtoken-tag-bg-indigo-hover")] = UDColor.I500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-lime")] = UDColor.L350.withAlphaComponent(0.2) & UDColor.L500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-lime-solid")] = UDColor.L200 & UDColor.L100
        store[UDColor.Name("udtoken-tag-bg-lime-hover")] = UDColor.L350.withAlphaComponent(0.3) & UDColor.L500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-orange")] = UDColor.O350.withAlphaComponent(0.15) & UDColor.O500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-orange-solid")] = UDColor.O200 & UDColor.O100
        store[UDColor.Name("udtoken-tag-bg-orange-hover")] = UDColor.O350.withAlphaComponent(0.3) & UDColor.O500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-orange-pressed")] = UDColor.O350.withAlphaComponent(0.35) & UDColor.O500.withAlphaComponent(0.35)
        store[UDColor.Name("udtoken-tag-bg-purple")] = UDColor.P500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-purple-solid")] = UDColor.P200 & UDColor.P100
        store[UDColor.Name("udtoken-tag-bg-purple-hover")] = UDColor.P500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-red")] = UDColor.R400.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-red-solid")] = UDColor.R200 & UDColor.R100
        store[UDColor.Name("udtoken-tag-bg-red-hover")] = UDColor.R400.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-turquoise")] = UDColor.T300.withAlphaComponent(0.2) & UDColor.T500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-turquoise-solid")] = UDColor.T200 & UDColor.T100
        store[UDColor.Name("udtoken-tag-bg-turquoise-hover")] = UDColor.T300.withAlphaComponent(0.3) & UDColor.T500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-violet")] = UDColor.V500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-violet-solid")] = UDColor.V200 & UDColor.V100
        store[UDColor.Name("udtoken-tag-bg-violet-hover")] = UDColor.V500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-wathet")] = UDColor.W300.withAlphaComponent(0.2) & UDColor.W500.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-bg-wathet-solid")] = UDColor.W200 & UDColor.W100
        store[UDColor.Name("udtoken-tag-bg-wathet-hover")] = UDColor.W300.withAlphaComponent(0.3) & UDColor.W500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-bg-yellow")] = UDColor.Y300.withAlphaComponent(0.2) & UDColor.Y400.withAlphaComponent(0.15)
        store[UDColor.Name("udtoken-tag-bg-yellow-solid")] = UDColor.Y200 & UDColor.Y100
        store[UDColor.Name("udtoken-tag-bg-yellow-hover")] = UDColor.Y300.withAlphaComponent(0.4) & UDColor.Y500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-close-blue-disabled")] = UDColor.B600.withAlphaComponent(0.8)
        store[UDColor.Name("udtoken-tag-close-blue-hover")] = UDColor.B600
        store[UDColor.Name("udtoken-tag-close-blue-normal")] = UDColor.B600.withAlphaComponent(0.6)
        store[UDColor.Name("udtoken-tag-close-blue-pressed")] = UDColor.B600.withAlphaComponent(0.8)
        store[UDColor.Name("udtoken-tag-close-orange-disabled")] = UDColor.O350.withAlphaComponent(0.3) & UDColor.O500.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-close-orange-hover")] = UDColor.O350 & UDColor.O500
        store[UDColor.Name("udtoken-tag-close-orange-normal")] = UDColor.O350.withAlphaComponent(0.6) & UDColor.O500.withAlphaComponent(0.6)
        store[UDColor.Name("udtoken-tag-close-orange-pressed")] = UDColor.O350.withAlphaComponent(0.8) & UDColor.O500.withAlphaComponent(0.8)
        store[UDColor.Name("udtoken-tag-neutral-bg-inverse")] = UDColor.N500 & UDColor.N400
        store[UDColor.Name("udtoken-tag-neutral-bg-inverse-opacity")] = UDColor.N900.withAlphaComponent(0.4)
        store[UDColor.Name("udtoken-tag-neutral-bg-normal")] = UDColor.N900.withAlphaComponent(0.1) & UDColor.N600.withAlphaComponent(0.2)
        store[UDColor.Name("udtoken-tag-neutral-bg-normal-hover")] = UDColor.N900.withAlphaComponent(0.15) & UDColor.N900.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-neutral-bg-normal-pressed")] = UDColor.N900.withAlphaComponent(0.2) & UDColor.N900.withAlphaComponent(0.4)
        store[UDColor.Name("udtoken-tag-neutral-bg-solid")] = UDColor.N200
        store[UDColor.Name("udtoken-tag-neutral-close-disabled")] = UDColor.textTitle.withAlphaComponent(0.3)
        store[UDColor.Name("udtoken-tag-neutral-close-hover")] = UDColor.textTitle
        store[UDColor.Name("udtoken-tag-neutral-close-normal")] = UDColor.textTitle.withAlphaComponent(0.6)
        store[UDColor.Name("udtoken-tag-neutral-close-pressed")] = UDColor.textTitle.withAlphaComponent(0.8)
        store[UDColor.Name("udtoken-tag-neutral-text-inverse")] = UDColor.N00 & UDColor.N1000
        store[UDColor.Name("udtoken-tag-neutral-text-inverse-opacity")] = UDColor.N00 & UDColor.N1000
        store[UDColor.Name("udtoken-tag-neutral-text-normal")] = UDColor.N600
        store[UDColor.Name("udtoken-tag-neutral-text-solid")] = UDColor.N600
        store[UDColor.Name("udtoken-tag-state-blue-light")] = UDColor.B500
        store[UDColor.Name("udtoken-tag-state-green-light")] = UDColor.G500
        store[UDColor.Name("udtoken-tag-state-grey-light")] = UDColor.N500
        store[UDColor.Name("udtoken-tag-state-orange-light")] = UDColor.O350 & UDColor.O500
        store[UDColor.Name("udtoken-tag-state-purple-light")] = UDColor.P500
        store[UDColor.Name("udtoken-tag-state-red-light")] = UDColor.R500
        store[UDColor.Name("udtoken-tag-text-s-blue")] = UDColor.B600 & UDColor.B700
        store[UDColor.Name("udtoken-tag-text-s-carmine")] = UDColor.C600 & UDColor.C700
        store[UDColor.Name("udtoken-tag-text-s-green")] = UDColor.G600 & UDColor.G700
        store[UDColor.Name("udtoken-tag-text-s-indigo")] = UDColor.I600 & UDColor.I700
        store[UDColor.Name("udtoken-tag-text-s-lime")] = UDColor.L600 & UDColor.L700
        store[UDColor.Name("udtoken-tag-text-s-orange")] = UDColor.O500 & UDColor.O700
        store[UDColor.Name("udtoken-tag-text-s-purple")] = UDColor.P600 & UDColor.P700
        store[UDColor.Name("udtoken-tag-text-s-red")] = UDColor.R600 & UDColor.R700
        store[UDColor.Name("udtoken-tag-text-s-turquoise")] = UDColor.T600 & UDColor.T700
        store[UDColor.Name("udtoken-tag-text-s-violet")] = UDColor.V600 & UDColor.V700
        store[UDColor.Name("udtoken-tag-text-s-wathet")] = UDColor.W600 & UDColor.W700
        store[UDColor.Name("udtoken-tag-text-s-yellow")] = UDColor.Y500 & UDColor.Y700
        store[UDColor.Name("udtoken-tag-text-blue")] = UDColor.B900 & UDColor.B700
        store[UDColor.Name("udtoken-tag-text-carmine")] = UDColor.C900 & UDColor.C700
        store[UDColor.Name("udtoken-tag-text-green")] = UDColor.G900 & UDColor.G700
        store[UDColor.Name("udtoken-tag-text-indigo")] = UDColor.I900 & UDColor.I700
        store[UDColor.Name("udtoken-tag-text-lime")] = UDColor.L900 & UDColor.L700
        store[UDColor.Name("udtoken-tag-text-orange")] = UDColor.O900 & UDColor.O700
        store[UDColor.Name("udtoken-tag-text-purple")] = UDColor.P900 & UDColor.P700
        store[UDColor.Name("udtoken-tag-text-red")] = UDColor.R900 & UDColor.R700
        store[UDColor.Name("udtoken-tag-text-turquoise")] = UDColor.T900 & UDColor.T700
        store[UDColor.Name("udtoken-tag-text-violet")] = UDColor.V900 & UDColor.V700
        store[UDColor.Name("udtoken-tag-text-wathet")] = UDColor.W900 & UDColor.W700
        store[UDColor.Name("udtoken-tag-text-yellow")] = UDColor.Y900 & UDColor.Y700
        store[UDColor.Name("udtoken-upload-bg-error")] = UDColor.N200 & UDColor.N900.withAlphaComponent(0.12)
        store[UDColor.Name("udtoken-upload-mask-img")] = UDColor.N900.withAlphaComponent(0.4) & UDColor.rgb(0x000000).withAlphaComponent(0.7)
        store[UDColor.Name("udtoken-colorpicker-carmine")] = UDColor.C400
        store[UDColor.Name("udtoken-colorpicker-red")] = UDColor.R400 & UDColor.R500
        store[UDColor.Name("udtoken-colorpicker-orange")] = UDColor.O350 & UDColor.O700
        store[UDColor.Name("udtoken-colorpicker-yellow")] = UDColor.Y350 & UDColor.Y600
        store[UDColor.Name("udtoken-colorpicker-green")] = UDColor.G350 & UDColor.G600
        store[UDColor.Name("udtoken-colorpicker-turquoise")] = UDColor.T300 & UDColor.T700
        store[UDColor.Name("udtoken-colorpicker-blue")] = UDColor.B500
        store[UDColor.Name("udtoken-colorpicker-wathet")] = UDColor.W300 & UDColor.W700
        store[UDColor.Name("udtoken-colorpicker-indigo")] = UDColor.I600 & UDColor.I400
        store[UDColor.Name("udtoken-colorpicker-purple")] = UDColor.P600 & UDColor.P400
        store[UDColor.Name("udtoken-colorpicker-violet")] = UDColor.V500
        store[UDColor.Name("udtoken-colorpicker-sunflower")] = UDColor.S200 & UDColor.S700
        store[UDColor.Name("udtoken-colorpicker-lime")] = UDColor.L300 & UDColor.L700
        store[UDColor.Name("udtoken-colorpicker-neutral")] = UDColor.N500
        store[UDColor.Name("udtoken-switch-handle-disabled")] = UDColor.staticWhite.withAlphaComponent(0.6) & UDColor.staticWhite.withAlphaComponent(0.3)
        return store
    }
    // swiftlint:enable all
}
