//
//  OpenPluginGetStorageInfoModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 24169
//  

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginGetStorageInfoResponse
final class OpenPluginGetStorageInfoResponse: OpenAPIBaseResult {
    
    /// description: 本地数据缓存中的所有键名列表，如果没有本地数据则返回空数组
    public let keys: [String]
    
    /// description: 占用空间大小，以 `KB` 为单位
    public let currentSize: Double
    
    /// description: 存储空间上限，以 `KB` 为单位，一般来说会返回 `10240`
    public let limitSize: Double
    
    public init(keys: [String], currentSize: Double, limitSize: Double) {
        self.keys = keys
        self.currentSize = currentSize
        self.limitSize = limitSize
        super.init()
    }
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["keys"] = keys
        result["currentSize"] = currentSize
        result["limitSize"] = limitSize
        return result
    }
}
