//
//  OpenPluginDoMsgCardActionModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 25761
//
//  类型声明默认为internal, 如需被外部Module引用, 请自行添加public声明, 并在上下行以
//  /** anycode-lint-ignore */
//  public class XXXModel
//  /** anycode-lint-ignore */
//  包裹.

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginDoMsgCardActionRequest
/** anycode-lint-ignore */
public
/** anycode-lint-ignore */
final class OpenPluginDoMsgCardActionRequest: OpenAPIBaseParams {
    
    /// description: 组件ID
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "elementID")
    public var elementID: String
    
    /// description: 二次确认弹窗
    @OpenAPIOptionalParam(
            jsonKey: "confirm")
    public var confirm: ConfirmObject?
    
    /// description: action相关信息
    @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "action")
    public var action: ActionObject
    
    /// description: 标签
    @OpenAPIOptionalParam(
            jsonKey: "tag")
    public var tag: String?
    
    /// description: 是否是复合交互
    @OpenAPIOptionalParam(
            jsonKey: "isMultiAction")
    public var isMultiAction: Bool?
    
    public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
        return [_elementID, _confirm, _action, _tag, _isMultiAction]
    }

    // MARK: ConfirmObject
    /** anycode-lint-ignore */
    public
    /** anycode-lint-ignore */
    final class ConfirmObject: OpenAPIBaseParams {

        /// description: 二次确认弹窗的title
        @OpenAPIOptionalParam(
                jsonKey: "title")
        public var title: String?

        /// description: 二次确认弹窗的text
        @OpenAPIOptionalParam(
                jsonKey: "text")
        public var text: String?

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_title, _text]
        }
    }

    // MARK: ActionObject
    /** anycode-lint-ignore */
    public
    /** anycode-lint-ignore */
    final class ActionObject: OpenAPIBaseParams {

        /// description: type = open_url 打开链接
        /// type = action_request 请求接口
        @OpenAPIRequiredParam(
            userRequiredWithJsonKey: "type")
        public var type: TypeEnum

        /// description: "action_request" 使用
        @OpenAPIOptionalParam(
            jsonKey: "actionID")
        public var actionID: String?

        /// description: "open_url" 使用
        @OpenAPIOptionalParam(
            jsonKey: "url")
        public var url: String?

        public override var autoCheckProperties: [OpenAPIParamPropertyProtocol] {
            return [_type, _actionID, _url]
        }
    }

    // MARK: TypeEnum
    /** anycode-lint-ignore */
    public
    /** anycode-lint-ignore */
    enum TypeEnum: String, OpenAPIEnum {

        /// description: 打开链接
        case open_url = "open_url"

        /// description: 请求接口
        case action_request = "action_request"

    }
}

