//
//  OpenPluginStartPasswordVerifyModel.swift
//  LarkOpenApis
//
//  GENERATED BY ANYCODE. DO NOT MODIFY!!!
//  TICKETID: 26126
//

import Foundation
import LarkOpenAPIModel


// MARK: - OpenPluginStartPasswordVerifyResponse
final class OpenPluginStartPasswordVerifyResponse: OpenAPIBaseResult {
    
    /// description: 认证 token 信息
    public let token: String?
    
    public init(token: String?) {
        self.token = token
        super.init()
    }
    
    public override func toJSONDict() -> [AnyHashable : Any] {
        var result: [AnyHashable : Any] = [:]
        result["token"] = token
        return result
    }
}

